#config_version=5

mode:
  start_events:
    - start_pre_qualify_mystery
  stop_events:
    - mode_invid_invasion_stopped
    - mode_genesis_pit_stopped
    - ball_ending
    - qualify_mystery
  restart_on_next_ball: false
  priority: 7900

counters:
  qualify_mystery_rollover_group:
    count_events: mystery_targets_rollover_group_hit_complete
    starting_count: 0
    direction: up
    count_complete_value: 1
    events_when_complete: qualify_mystery
    #persist_state: true
    reset_on_complete: false #true
    disable_on_complete: true #false
    debug: true

shot_groups:
  mystery_targets_rollover_group:
    shots:
      - mystery_rollover_rand
      - mystery_rollover_rook
      - mystery_rollover_lancer
    enable_events:
      #- enable_mystery_invid_targets
      #- mode_pre_qualify_mystery_started
      # - mode_pre_qualify_mystery_started
      # - mode_annie_mode_stopped
      - mode_skill_shot_stopped
      - mode_corg_mode_stopped
      # - mode_rook_mode_stopping
      # - mode_lunk_mode_stopped
      # - mode_rand_mode_stopped
      #- stop_qualify_mystery
    disable_events:
    #   - mode_pre_qualify_mystery_stopped
      #- mystery_targets_invid_group_hit_complete
      #- mode_bonus_will_start
      # - mode_invid_invasion_starting
      # - mode_intro_rand_mode_starting
      # - mode_annie_mode_starting
      - mode_skill_shot_started
      - mode_intro_corg_mode_started
      # - mode_intro_rook_mode_starting
      # - mode_lunk_mode_starting
    reset_events:
      - mystery_targets_rollover_group_hit_complete
      - ball_ending
    debug: true

shot_profiles:
  mystery_profile:
    show_when_disabled: false
    states:
      - name: flashing
        show: pre_mystery_flash_show
        sync_ms: 1500
        speed: 6
      - name: hit
        show: color_green_on

shots:
  mystery_rollover_rand:
    switch: s_left_rollover
    profile: mystery_profile
    show_tokens:
      leds: llock_rollover
    debug: true
  mystery_rollover_rook:
    switch: s_right_rollover
    profile: mystery_profile
    show_tokens:
      leds: rlock_rollover
    debug: true
  mystery_rollover_lancer:
    switch: s_right_orbit_rollover
    profile: mystery_profile
    show_tokens:
      leds: rorbit_rollover
    debug: true


sound_player:
  mystery_targets_rollover_group_flashing_hit:
    collect2:
      action: play
