#config_version=5

mode:
  start_events:
    - ball_starting
    - mode_end_invid_invasion_stopped
  stop_events:
    - end_skill_shot_mode
    # - top_lanes_skill_hit
    # - invid_targets_skill_hit
    # - saucer_skill_group_hit
    # #- timer_skillshot_invid_stop_timer_complete
    # - timer_skillshot_saucer_stop_timer_complete
    # - ball_save_default_saving_ball
    # - super_skill_sequence_hit #|1s
    # - sdf_skill_group_hit
    # - s_top_target_active
  priority: 1900

event_player:
  # mode_skill_shot_will_start:
  #   - ramp_down_enable
  mode_skill_shot_started:
    - orbit_gate_enable
    - ramp_down_active
    - drop_reset_up
    # - start_character_modes{device.achievement.invid_invasion_mission_1.state == "complete"}
  mode_skill_shot_stopping:
    - orbit_gate_disable
    - ramp_up_active{device.switches.s_up_down_ramp_switch.state == 1}
    #- start_pre_qualify_invid_invasion
    - drop_reset_up
    - start_annie_mode{device.achievements.annie_mode_collect.state=="enabled"}
    #- ramp_down_active{mode.qualify_invid_invasion.active}
  lanes_invid_skill_cancel_sequence_timeout:
    # - disable_top_lanes_skill
    # - disable_invid_targets_skill
    # - change_tick_interval_timer_up
    - ramp_up_active
    - start_skillshot_saucer_timer
    #- disable_sdf_skill_group
    - orbit_gate_disable
  top_lanes_skill_flashing_hit:
    - start_kickback_mode
    - skill_shot_made
    - end_skill_shot_mode
  invid_targets_skill_flashing_hit:
    - start_kickback_mode
    #- skill_shot_made
    - end_skill_shot_mode
  saucer_skill_group_flashing_hit:
    - start_kickback_mode
    - skill_shot_made
    - end_skill_shot_mode
  sdf_skill_group_flashing_hit:
    - start_kickback_mode
    #- skill_shot_made
    - end_skill_shot_mode
  top_target_skill_group_flashing_hit:
    - start_kickback_mode
    - skill_shot_made
    - end_skill_shot_mode
  #super skill shot
  super_skill_sequence_hit:
    - start_kickback_mode
    - skill_shot_made
    - end_skill_shot_mode
    #- orbit_gate_enable
  #lanes_invid_skill_cancel_sequence_hit:
  s_gate_top_right_active:
    - ramp_up_active
    - start_skillshot_saucer_timer
  # timer_skillshot_invid_stop_timer_complete:
  #   - disable_invid_targets_skill
  s_back_ramp_active:
     - start_kickback_mode
     - skill_shot_made
     - end_skill_shot_mode
  top_lanes_skill_unlit_hit:
    - skill_shot_missed
    - end_skill_shot_mode
  invid_targets_skill_unlit_hit:
    #- skill_shot_missed
    - end_skill_shot_mode
  saucer_skill_group_hit_hit:
    - skill_shot_missed
    - end_skill_shot_mode
  sdf_skill_group_unlit_hit:
    #- skill_shot_missed
    - end_skill_shot_mode
  timer_skillshot_saucer_stop_timer_complete:
    - skill_shot_missed
    - end_skill_shot_mode
  ball_save_default_saving_ball:
    - end_skill_shot_mode
  shatz_skill_sequence_hit:
    - start_kickback_mode
    - shatz_skill_shot_made
    - end_skill_shot_mode

timers:
  top_lanes_target_rotator:
    start_running: true
    tick_interval: 1s
    control_events:
      - action: stop
        event: s_right_orbit_rollover_active
    #debug: true
  invid_targets_target_rotator:
    start_running: true
    tick_interval: 0.25s
    control_events:
      - action: stop
        event: s_left_orbit_active
      - action: stop
        event: end_skill_shot_mode
      # - event: lanes_invid_skill_cancel_sequence_timeout
      #   action: change_tick_interval #set_tick_interval
      #   value: 1
    debug: true
  # skillshot_invid_stop_timer:
  #   start_value: 0
  #   end_value: 5
  #   direction: up
  #   tick_interval: 1s
  #   start_running: no
  #   control_events:
  #     - action: start
  #       event: s_left_orbit_active
  #   #debug: true
  skillshot_saucer_stop_timer:
    start_value: 0
    end_value: 8
    direction: up
    tick_interval: 1s
    start_running: no
    control_events:
      - action: start
        event: start_skillshot_saucer_timer

sequence_shots:
  lanes_invid_skill_cancel_sequence:
    switch_sequence:
      - s_right_orbit_rollover
      - s_gate_top_right
    sequence_timeout: 2s
    #debug: true
  super_skill_sequence:
    switch_sequence:
      - s_spinner
      #- s_right_orbit_rollover
      - s_gate_top_right
      - s_left_orbit
    sequence_timeout: 2s
    #cancel_switches: s_r_top_lane, s_o1_top_lane, s_b_top_lane, s_o2_top_lane
  shatz_skill_sequence:
    switch_sequence:
      - s_left_orbit
      - s_left_flipper
      - s_right_inlane_c
    sequence_timeout: 2s


shows:
  flash_led_skill_show:
    - time: 0
      lights:
        (leds): (color)
    - time: +1
      lights:
        (leds): black
  flash_saucer_skill_show:
    - time: 0
      lights:
        (leds): (color)
    - time: +1
      lights:
        (leds): black
  flash_sdf_skill_show:
    - time: 0
      lights:
        (leds): (color)
    - time: +1
      lights:
        (leds): black
  pulse_super_skill_show:
    - time: 0
      lights:
        l_right_orbit_arrow: white-f500ms
    - time: +1
      lights:
        l_right_orbit_arrow: black-f500ms
  flash_top_target_show:
    - time: 0
      lights:
        (leds): (color)
    - time: +1
      lights:
        (leds): black
  flash_led_skill_show_hit:
    - time: 0
      lights:
        (leds): (color)
    - time: +1
      lights:
        (leds): white
  skill_led_hit_show:
    - time: 0
      lights:
        (leds): (color)
    - time: -1


show_player:
  mode_skill_shot_started:
    pulse_super_skill_show:
      action: play
      speed: 1
      loops: -1
    flash_top_target_show:
      action: play
      speed: 3
      loops: -1
    color_blue_on:
      action: play
      show_tokens:
        leds: l_sdf_arrow_led
  lanes_invid_skill_cancel_sequence_timeout:
    pulse_super_skill_show:
      action: stop

shot_profiles:
  top_lanes_skill:
    block: false
    states:
    - name: unlit
      show: off
    - name: flashing
      show: flash_led_skill_show
      show_tokens:
        color: green
      loops: -1
      speed: 10
    - name: hit
      show: off
      #advance_on_hit: false
      #debug: true
  invid_targets_skill:
    advance_on_hit: false #testing 11-5
    block: false #true
    states:
    - name: unlit
      show: off
    - name: flashing
      show: flash_led_skill_show
      show_tokens:
        color: 2E0854 #purple
      loops: -1
      speed: 10
    - name: hit
      show: off
      # show: on
      #debug: true
  saucer_targets_skill:
    block: false #true
    states:
    - name: flashing
      show: flash_saucer_skill_show
      show_tokens:
        color: yellow
      loops: -1
      speed: 13
    - name: hit
      show: skill_led_hit_show
      show_tokens:
        color: yellow
  sdf_targets_skill:
    advance_on_hit: false
    block: false
    states:
    - name: unlit
      show: off
    - name: flashing
      show: flash_sdf_skill_show
      show_tokens:
        color: blue
      loops: -1
      speed: 13
    - name: hit
      show: off
      # show: skill_led_hit_show
      # show_tokens:
      #   color: blue
  top_target_skill:
    advance_on_hit: false
    states:
    - name: unlit
      show: off
    - name: flashing
      show: flash_top_target_show
      show_tokens:
        color: orange
      loops: -1
      speed: 13
    - name: hit
      show: off


shot_groups:
  top_lanes_skill:
    shots: skill_r_top_lane_shot, skill_o1_top_lane_shot, skill_b_top_lane_shot, skill_o2_top_lane_shot
    rotate_right_events: timer_top_lanes_target_rotator_tick
    reset_events: mode_skill_shot_starting
    enable_events: mode_skill_shot_starting #ball_started
    disable_events: disable_top_lanes_skill #, super_skill_sequence_hit #s_left_orbit_active
    #debug: true
  invid_targets_skill:
    shots: skill_invid1_shot, skill_invid2_shot, skill_invid3_shot, skill_invid4_shot, skill_invid5_shot, skill_invid6_shot
    rotate_left_events: timer_invid_targets_target_rotator_tick
    reset_events: mode_skill_shot_starting
    enable_events: mode_skill_shot_starting #ball_started
    disable_events: disable_invid_targets_skill, skill_shot_missed, skill_shot_made #,super_skill_sequence_hit
    #advance_events: disable_invid_targets_skill #added 11/4 to test
    #debug: true
  saucer_skill_group:
    shots: left_saucer_skill, top_saucer_skill, right_saucer_skill
    enable_events: mode_skill_shot_starting #ball_started #start_skillshot_saucer_timer
    #disable_events: #super_skill_sequence_hit
    #debug: true
  sdf_skill_group:
    shots: s_skill, d_skill, f_skill
    enable_events: mode_skill_shot_starting #ball_started
    disable_events: disable_sdf_skill_group #, super_skill_sequence_hit
  top_target_skill_group:
    shots: top_target_10k_skill, top_target_20k_skill, top_target_50k_skill
    enable_events: mode_skill_shot_starting #ball_started
    disable_events: disable_top_target_skill_group, #super_skill_sequence_hit

shots:
  skill_r_top_lane_shot:
    switch: s_r_top_lane
    profile: top_lanes_skill
    advance_events: mode_skill_shot_started|1
    show_tokens:
      leds: l_r_light
    #debug: true
  skill_o1_top_lane_shot:
    switch: s_o1_top_lane
    profile: top_lanes_skill
    show_tokens:
      leds: l_o_light
    #debug: true
  skill_b_top_lane_shot:
    switch: s_b_top_lane
    profile: top_lanes_skill
    show_tokens:
      leds: l_b_light
    #debug: true
  skill_o2_top_lane_shot:
    switch: s_o2_top_lane
    profile: top_lanes_skill
    show_tokens:
      leds: l_o2_light
  skill_invid1_shot:
    switch: s_left_target
    profile: invid_targets_skill
    show_tokens:
      leds: l_t1
    #advance_events: lanes_invid_skill_cancel_sequence_timeout #testing 11-5
    #debug: true
  skill_invid2_shot:
    switch: s_middle_target
    profile: invid_targets_skill
    show_tokens:
      leds: l_t2
    #advance_events: lanes_invid_skill_cancel_sequence_timeout #testing 11-5
    #debug: true
  skill_invid3_shot:
    switch: s_right_target
    profile: invid_targets_skill
    show_tokens:
      leds: l_t3
    #advance_events: lanes_invid_skill_cancel_sequence_timeout #testing 11-5
    #advance_events: mode_skill_shot_started|1
    #debug: true
  skill_invid4_shot:
    switch: s_left_drop_target
    profile: invid_targets_skill
    show_tokens:
      leds: l_t4
    #debug: true
  skill_invid5_shot:
    switch: s_middle_drop_target
    profile: invid_targets_skill
    show_tokens:
      leds: l_t5
    #debug: true
  skill_invid6_shot:
    switch: s_right_drop_target
    profile: invid_targets_skill
    advance_events: mode_skill_shot_started|1
    show_tokens:
      leds: l_t6
    #debug: true
  left_saucer_skill:
    switch: s_left_lock_kickout
    profile: saucer_targets_skill
    show_tokens:
      leds: l_llock_arrow
  top_saucer_skill:
    switch: s_top_lock_kickout
    profile: saucer_targets_skill
    show_tokens:
      leds: l_left_orbit_arrow
  right_saucer_skill:
    switch: s_right_lock_kickout
    profile: saucer_targets_skill
    show_tokens:
      leds: l_rlock_arrow
  s_skill:
    switch: s_s_target
    profile: sdf_targets_skill
    show_tokens:
      leds: l_s_led
    advance_events: mode_skill_shot_started{ball==1}, s_skill_sdf_targets_skill_flashing_hit
  d_skill:
    switch: s_d_target
    profile: sdf_targets_skill
    show_tokens:
      leds: l_d_led
    advance_events: s_skill_sdf_targets_skill_flashing_hit, d_skill_sdf_targets_skill_flashing_hit
  f_skill:
    switch: s_f_target
    profile: sdf_targets_skill
    show_tokens:
      leds: l_f_led
    advance_events: d_skill_sdf_targets_skill_flashing_hit, f_skill_sdf_targets_skill_flashing_hit
  top_target_10k_skill:
    switch: s_top_target
    profile: top_target_skill
    show_tokens:
      leds: l_10k
    advance_events: mode_skill_shot_started{ball==1}, top_target_10k_skill_top_target_skill_flashing_hit
  top_target_20k_skill:
    switch: s_top_target
    profile: top_target_skill
    show_tokens:
      leds: l_20k
    advance_events: top_target_10k_skill_top_target_skill_flashing_hit, top_target_20k_skill_top_target_skill_flashing_hit
  top_target_50k_skill:
    switch: s_top_target
    profile: top_target_skill
    show_tokens:
      leds: l_50k
    advance_events: top_target_20k_skill_top_target_skill_flashing_hit, top_target_50k_skill_top_target_skill_flashing_hit


counters:
  top_lanes_skillshot_made:
    count_events: top_lanes_skill_flashing_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: award_extra_ball, award_50k_bonus
    debug: true
  invid_targets_skillshot_made:
    count_events: invid_targets_skill_flashing_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: award_extra_ball, award_50k_bonus
    #debug: true
  saucer_skillshot_made:
    count_events: saucer_skill_group_flashing_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: award_extra_ball, award_50k_bonus
    #debug: true
  sdf_skillshot_made:
    count_events: sdf_skill_group_flashing_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: award_extra_ball, award_50k_bonus
    #debug: true
  top_target_shot_made:
    count_events: top_target_skill_group_flashing_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: award_extra_ball, award_50k_bonus
  super_skill_shot_made:
    count_events: super_skill_sequence_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: award_extra_ball, award_50k_bonus
  secret_skill_shot_made:
    count_events: s_back_ramp_active
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: award_extra_ball, award_50k_bonus
  shatz_skillshot_made:
    count_events: shatz_skill_sequence_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: award_extra_ball, award_50k_bonus

accruals:
  three_different_skillshots:
    events:
      - top_lanes_skill_flashing_hit
      - invid_targets_skill_flashing_hit
      - saucer_skill_group_flashing_hit
    persist_state: true
    events_when_complete: award_extra_ball, award_50k_bonus

#sequences:


variable_player:
  r_top_lane_shot_unlit_hit:
    score: 0|block
  o1_top_lane_shot_unlit_hit:
    score: 0|block
  b_top_lane_shot_unlit_hit:
    score: 0|block
  o2_top_lane_shot_unlit_hit:
    score: 0|block
  top_lanes_skill_unlit_hit:
    score: 1000
  s_left_lock_kickout_active:
    score: 0|block
  saucer_skill_group_flashing_hit:
    skill_shot_value:
      int: 5000 * device.counters.saucer_skillshot_made.value
      action: set
    score: 5000 * device.counters.saucer_skillshot_made.value
  top_lanes_skill_flashing_hit:
    skill_shot_value:
      int: 5000 * device.counters.top_lanes_skillshot_made.value
      action: set
    score: 5000 * device.counters.top_lanes_skillshot_made.value
  invid_targets_skill_flashing_hit:
    skill_shot_value:
      int: 5000 * device.counters.invid_targets_skillshot_made.value
      action: set
    score: 5000 * device.counters.invid_targets_skillshot_made.value
  sdf_skill_group_flashing_hit:
    skill_shot_value:
      int: 5000 * device.counters.sdf_skillshot_made.value
      action: set
    score: 5000 * device.counters.sdf_skillshot_made.value
  super_skill_sequence_hit:
    skill_shot_value:
      int: 10000 * device.counters.super_skill_shot_made.value
      action: set
    score: 10000 * device.counters.super_skill_shot_made.value
  top_target_skill_group_flashing_hit:
    skill_shot_value:
      int: 5000 * device.counters.top_target_shot_made.value
      action: set
    score: 5000 * device.counters.top_target_shot_made.value
  #secret skill shot
  s_back_ramp_active:
    skill_shot_value:
      int: 10000 * device.counters.secret_skill_shot_made.value
      action: set
    score: 10000 * device.counters.secret_skill_shot_made.value
  #shatz skill shot
  shatz_skill_sequence_hit:
    skill_shot_value:
      int: 25000 * device.counters.shatz_skillshot_made.value
      action: set
    score: 25000 * device.counters.shatz_skillshot_made.value
  award_50k_bonus:
    skill_shots_bonus: 1

# slides:
#   skill_shot_invid_hit_video:
#     - type: video
#       video: skill_shot_saucer.mp4
#
# slide_player:
#    saucer_skill_group_lit_hit:
#      skill_shot_invid_hit_video
state_machines:
  skill_shot_success:
    debug: True
    states:
      start:
        label: Skill shot ready
      success:
        label: Skill made
        events_when_started: skill_shot_made
      failed:
        label: Skill missed
        events_when_started: skill_shot_missed
    transitions:
      - source: start
        target: success
        events: sdf_skill_group_flashing_hit, invid_targets_skill_flashing_hit
      - source: start
        target: failed
        events: sdf_skill_group_unlit_hit, invid_targets_skill_unlit_hit
