#config_version=5

mode:
   start_events:
     - enable_corg_mode
   stop_events:
     - stop_qualify_corg_mode
   restart_on_next_ball: true
   priority: 7900

event_player:
  start_corg_mode_shot_flashing_hit:
    - start_intro_corg_mode
    - stop_qualify_corg_mode


shot_profiles:
  start_corg_mode_shot_profile:
    show_when_disabled: false
    states:
      - name: flashing
        show: flash_corg_blue_show
        sync_ms: 1500
        loops: -1
        speed: 5
      - name: hit
        show: off

shots:
  start_corg_mode_shot:
    switch: s_top_lock_kickout
    profile: start_corg_mode_shot_profile
    show_tokens:
      leds: l_corg_arrow
    enable_events:
      - mode_skill_shot_stopped
      - mode_rand_mode_stopped
      - mode_annie_mode_stopped
      - mode_rook_mode_stopped
      - mode_lunk_mode_stopped
      - achievement_corg_state_enabled
    disable_events:
      - mode_skill_shot_started
      - mode_intro_rand_mode_started
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
    debug: true
