#config_version=5

mode:
   start_events:
     - start_intro_invid_invasion
   stop_events:
     - mode_invid_invasion_started
   restart_on_next_ball: false
   priority: 800

event_player:
  flipper_cancel: start_invid_invasion
  timer_intro_invid_invasion_timer_complete: start_invid_invasion

queue_event_player:
  mode_intro_invid_invasion_started:
    queue_event: my_queue
    events_when_finished: start_invid_invasion

queue_relay_player:
  my_queue:
    post: start_mode_multiball_intro
    wait_for: mode_multiball_show_ended
  balldevice_bd_trough_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: mode_multiball_show_ended
  balldevice_bd_right_lock_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: mode_multiball_show_ended

timers:
  intro_invid_invasion_timer:
    debug: true
    start_value: 8
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: true


widgets:
  black_screen_rectangle_widget:
    - type: rectangle
      anchor_x: left
      anchor_y: bottom
      x: 0
      y: 0
      z: 109
      width: 1280
      height: 720
      color: black
  intro_ii_text1_widget:
    - type: text
      text: INVID INVASION !!!
      color: white
      font_size: 80
      x: center
      y: center+300
      z: 110
  intro_ii_video_widget:
    - type: video
      video: intro_invid_invasion_video
      z: 110
  intro_ii_text2_widget:
    - type: text
      text: 20 Invid Targets Hit, Lits Jackpot
      color: white
      x: center
      y: center-300
      z: 110
      font_size: 50

widget_player:
  play_multiball_intro:
    black_screen_rectangle_widget:
      action: add
    intro_ii_text1_widget:
      action: add
    intro_ii_video_widget:
      action: add
    intro_ii_text2_widget:
      action: add

light_player:
  mode_intro_invid_invasion_started:
    gi_string:
      color: off
    playfield:
      color: off
      priority: 9900

show_player:
  start_mode_multiball_intro:
    intro_mode_start_show:
      loops: 0
      speed: 30
      priority: 9910
      events_when_stopped:
        - play_multiball_intro
        - play_alert_show
  play_alert_show:
    alert_show:
      loops: -1
      priority: 9920
