#config_version=5

mode:
   start_events: start_intro_invid_invasion
   stop_events: mode_invid_invasion_started, game_ending
   restart_on_next_ball: true
   priority: 800

queue_event_player:
  mode_intro_invid_invasion_started:
    queue_event: my_queue
    events_when_finished: start_invid_invasion

queue_relay_player:
  my_queue:
    post: start_mode_multiball_intro
    wait_for: mode_multiball_show_ended
  balldevice_bd_trough_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: mode_multiball_show_ended
  balldevice_bd_right_lock_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: mode_multiball_show_ended

shows:
  multiball_intro:
    - duration: 6
      slides:
        intro_invid_invasion_slide:
          widgets:
            - type: text
              text: INVID INVASION !!!
              color: white
              font_size: 130
              y: center + 100
            - type: text
              text: Destroy 20 Enemy Invid
              color: white
              y: center-40
              font_size: 80
            - type: text
              text: Spinner hit adds time
              y: center-100
              font_size: 80
            - type: text
              text: SDF targets Add-A-Ball
              y: center-160
              font_size: 80

show_player:
  start_mode_multiball_intro:
    multiball_intro:
      loops: 0
      events_when_stopped: mode_multiball_show_ended
    alert_show:
      loops: -1
      priority: 9500
  flipper_cancel:
    multiball_intro:
      action: stop


multiball_locks:
  invid_invasion_multiball:
  #invid_invasion_ball_lock:
  #invid_invasion_ball_hold:
    #balls_to_hold: 1
    balls_to_lock: 1
    lock_devices: bd_right_lock
    #hold_devices: bd_left_lock
    #lock_devices: bd_left_lock
    #release_one_events: start_mission_1
    #reset_events: machine_reset_phase_3, ball_starting, ball_will_end, service_mode_entered, start_mission_1
    #reset_count_for_current_player_events: quick_2_ball_start
    disable_events: invid_invasion_quick_2_ball_started

sound_player:
  mode_intro_invid_invasion_started:
    invid_invasion_start:
      action: play
  flipper_cancel:
    invid_invasion_start:
      action: stop
