#config_version=5

mode:
  start_events:
    - rook_mode_success
  stop_events:
    - ball_will_end
    - rook_collect_mecha_mode_done
  stop_on_ball_end: true
  priority: 4800

queue_event_player:
  rook_collect_mecha_shot_flashing_hit:
    queue_event: my_queue_rook_collect_mecha_mode
    events_when_finished: rook_collect_mecha_mode_done

queue_relay_player:
  my_queue_rook_collect_mecha_mode:
    post: start_rook_collect_mecha_mode_display
    wait_for: rook_collect_mecha_mode_show_ended
  balldevice_bd_right_lock_ball_eject_attempt{not mode.rand_mode.active and not mode.annie_mode.active and not mode.lunk_mode.active and device.shots.rook_collect_mecha_shot.state_name=='hit'}:
    post: wait_for_rook_collect_mecha_mode_display
    wait_for: rook_collect_mecha_mode_show_ended


# shot_groups:
#   rook_collect_mecha_shot_group:
#     shots: rook_collect_mecha_shot
#     enable_events: mode_rook_collect_mecha_started
#     disable_events: rook_collect_mecha_shot_group_flashing_hit


shot_profiles:
  rook_collect_mecha_flash:
    advance_on_hit: true
    states:
      - name: flashing
        show: flash_blue_show
        loops: -1
        speed: 10
      - name: hit
        show: off

shots:
  rook_collect_mecha_shot:
    switch: s_right_lock_kickout
    profile: rook_collect_mecha_flash
    show_tokens:
      leds: l_rlock_arrow
    enable_events:
      - mode_skill_shot_stopped
      - mode_rook_collect_mecha_started
      - mode_rand_mode_stopped
      - mode_annie_mode_stopped
      - mode_lunk_mode_stopped
      - mode_genesis_pit_stopped
      - mode_the_fortress_stopped
    disable_events:
      - mode_skill_shot_started
      - mode_rand_mode_started
      - mode_annie_mode_started
      - mode_lunk_mode_started
      - mode_genesis_pit_started
      - mode_the_fortress_started

shows:
  rook_collect_mecha_mode_display:
    - duration: 8
      slides:
        rook_collect_mecha_slide:
          widgets:
            - type: text
              text: CYCLONE Collected
              color: yellow
              font_size: 80
              x: center
              y: center+300
            - type: video
              video: rook_collect_mecha_video
            - type: text
              text: (mecha_collect_value)
              font_size: 80
              x: center
              y: center-300
              color: yellow
              number_grouping: true

show_player:
  start_rook_collect_mecha_mode_display:
    rook_collect_mecha_mode_display:
      loops: 0
      events_when_stopped: rook_collect_mecha_mode_show_ended
  flipper_cancel:
    rook_collect_mecha_mode_display:
      action: stop

variable_player:
  rook_collect_mecha_shot_hit:
  #rand_collect_mecha_shot_group_flashing_hit:
    score: (50000 * current_player.rook_shot_multiplier) * current_player.pf_multiplier
    mecha_collect_value:
      int: (50000 * current_player.rook_shot_multiplier) * current_player.pf_multiplier
      action: set
