#config_version=5
#Robotech

mode:
    start_events:
      #- ball_starting
      - mode_skill_shot_started
      # - mode_end_invid_invasion_stopped
      # - mode_end_genesis_pit_stopped
      # - mode_the_fortress_stopped
    stop_events:
      - qualify_invid_invasion
      - ball_save_default_disabled #mode_ball_save_done
      - mode_intro_invid_invasion_started
      - mode_intro_rand_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_annie_mode_started
      - kickback_kickback_main_fired
      - ball_save_qualify_mode_ball_save_timer_start
    priority: 8400

# event_player:
#   # ball_save_default_disabled{mode.kickback.active}:
#   #   - kickback_enable
#   # ball_save_default_grace_period{mode.kickback.active}:
#   #   - kickback_enable
#   ball_save_default_disabled:
#      - mode_ball_save_done #|1s

ball_saves:
  default:
    active_time: 10s
    grace_period: 2s
    hurry_up_time: 5s
    # enable_events:
    #   - mode_ball_save_started
    timer_start_events:
      - sw_playfield_active
      - invid_targets_skill_hit
    early_ball_save_events:
      - s_right_outlane_h_active
      - s_kickback_t_active{not mode.kickback.active}
    auto_launch: true
    balls_to_save: 1
    debug: true

show_player:
  ball_save_default_timer_start:
    ball_save_flash:
      action: play
      speed: 3
  ball_save_default_hurry_up:
    ball_save_flash:
      action: play
      speed: 9
  ball_save_default_grace_period:
    ball_save_flash:
      action: stop
  # ball_save_default_disabled:
  #   ball_save_flash:
  #     action: stop

# widgets:
#   ball_save_left_video:
#     - type: video
#       video: ball_save_left

# widget_player:
#   s_kickback_t_active:
#     ball_save_left_video:
#       action: update
#       widget_settings:
#         expire: 5.5s
#         z: 120

# sound_player:
  # s_kickback_t_active:
  #   come_back_my_scott:
  #     action: play
  #     #events_when_stopped: mode_ball_save_done
  #     #loops: 1
  # s_right_outlane_h_active:
  #   come_back_my_scott:
  #     action: play
      #events_when_stopped: mode_ball_save_done
#   balldevice_bd_trough_ball_enter:
#     come_back_my_scott:
#       action: play
#       events_when_stopped: mode_ball_saved_done
