#config_version=5

mode:
  start_events:
    - pops_level_2
  stop_events:
    - pops_level_3
    - ball_ended
  priority: 7200

event_player:
  # mode_pops_level_2_started.1{not mode.invid_invasion.active or not mode.rand_mode.active or not mode.annie_mode.active or not mode.rook_mode.active or not mode.lunk_mode.active or not mode.genesis_pit.active}:
  #   - enable_pops_level_2
  mode_pops_level_2_started.1{mode.invid_invasion.active or mode.rand_mode.active or mode.annie_mode.active or mode.rook_mode.active or mode.lunk_mode.active or mode.genesis_pit.active}:
    - disable_pops_level_2
  # mode_pops_level_2_started{not mode.invid_invasion.active or not mode.rand_mode.active or not mode.annie_mode.active or not mode.rook_mode.active or not mode.lunk_mode.active}:
  #   logicblock_pops_level_2_hit_counter_hit:
  #     count:
  #       value: device.counters.pops_level_2_hit_counter.value
  mode_pops_level_2_started.2:
    logicblock_pops_level_2_hit_counter_hit:
      count:
        value: device.counters.pops_level_2_hit_counter.value
  # mode_end_invid_invasion_stopped:
  #   logicblock_pops_level_2_hit_counter_hit:
  #     count:
  #       value: device.counters.pops_level_2_hit_counter.value
  # mode_rand_mode_stopped:
  #   logicblock_pops_level_2_hit_counter_hit:
  #     count:
  #       value: device.counters.pops_level_2_hit_counter.value
  # mode_annie_mode_stopped:
  #   logicblock_pops_level_2_hit_counter_hit:
  #     count:
  #       value: device.counters.pops_level_2_hit_counter.value
  # mode_rook_mode_stopped:
  #   logicblock_pops_level_2_hit_counter_hit:
  #     count:
  #       value: device.counters.pops_level_2_hit_counter.value

counters:
  pops_level_2_hit_counter:
    count_events: pops_shot_hit
    starting_count: current_player.pops_initial_count
    direction: down
    count_complete_value: 0
    reset_on_complete: true
    events_when_complete: pops_level_3
    disable_on_complete: false
    enable_events:
      - mode_pops_level_2_starting
      - enable_pops_level_2
      - mode_rand_mode_stopped
      - mode_annie_mode_stopped
      - mode_rook_mode_stopped
      - mode_end_invid_invasion_stopped
      - mode_lunk_mode_stopped
      - mode_genesis_pit_stopped
    disable_events:
      - disable_pops_level_2
      - mode_intro_rand_mode_started
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_intro_invid_invasion_started
      - mode_lunk_mode_started
      - mode_intro_genesis_pit_started
    persist_state: false
    debug: true

widgets:
  # pops_level_2_widget:
  #   - type: text
  #     text: POPS LEVEL 2
  #     color: orange
  #     font_size: 80
  #     x: center
  #     y: center + 50
    # - type: text
    #   text: "Score: 500"
    #   color: purple
    #   font_size: 80
    #   x: center
    #   y: center - 50
  pops_level_2_count_widget:
    - type: text
      text: "POPS: L2 - (count)"
      color: orange
      font_size: 35
      x: center - 450
      y: center - 230
    - type: text
      text: "Value: 500"
      color: orange
      font_size: 30
      x: center - 450
      y: center - 260

widget_player:
  # mode_pops_level_2_started:
  #   pops_level_2_widget:
  #     action: add
  #     widget_settings:
  #       expire: 3s
        #z: 110
  logicblock_pops_level_2_hit_counter_hit:
    pops_level_2_count_widget:
      action: update
      slide: base_slide
      priority: 7201
  # mode_intro_invid_invasion_started:
  #   pops_level_2_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_intro_rand_mode_started:
  #   pops_level_2_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_annie_mode_started:
  #   pops_level_2_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_intro_rook_mode_started:
  #   pops_level_2_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_lunk_mode_started:
  #   pops_level_2_count_widget:
  #     action: remove
  #     slide: base_slide

show_player:
  s_bottom_r_pop_bumper_active:
    flash_pop_bumper_orange:
      key: bottom_right_pop_flash
      loops: 0
      show_tokens:
        leds: l_lower_r_pop_bumper
  s_bottom_l_pop_bumper_active:
    flash_pop_bumper_orange:
      key: bottom_left_pop_flash
      loops: 0
      show_tokens:
        leds: l_lower_l_pop_bumper
  s_top_r_pop_bumper_active:
    flash_pop_bumper_orange:
      key: top_right_pop_flash
      loops: 0
      show_tokens:
        leds: l_upper_r_pop_bumper
  s_top_l_pop_bumper_active:
    flash_pop_bumper_orange:
      key: top_left_pop_flash
      loops: 0
      show_tokens:
        leds: l_upper_l_pop_bumper

variable_player:
  pops_shot_hit:
    score: 500 * current_player.pf_multiplier

sound_player:
  mode_pops_level_2_started:
    pops_level_2:
      action: play
