#config_version=5
#Robotech

mode:
    start_events:
      - mode_rand_mode_will_start
    stop_events:
      - ball_save_rand_mode_multiball_disabled
      #- mode_end_invid_invasion_started
    priority: 9250


ball_saves:
  rand_mode_multiball:
    active_time: 15s
    hurry_up_time: 5s
    grace_period: 5s
    #enable_events: mode_ball_save_rand_mode_started
    timer_start_events:
      - mode_ball_save_rand_mode_started
    auto_launch: true
    balls_to_save: -1
    debug: true

show_player:
  ball_save_rand_mode_multiball_timer_start:
    fast_flash_show:
      key: rand_mode_save_flash
      speed: 3
      show_tokens:
        leds: l_shoot_again
        color: red
      action: play
  ball_save_rand_mode_multiball_hurry_up:
    rand_mode_save_flash:
      action: stop
    fast_flash_show:
      key: rand_mode_hurry_up_flash
      action: play
      speed: 20
      show_tokens:
        leds: l_shoot_again
        color: red
  ball_save_rand_mode_multiball_grace_period:
    rand_mode_hurry_up_flash:
      action: stop
