#config_version=5

mode:
  start_events: game_ended, reset_complete
  stop_events: game_start
  priority: 10
  game_mode: False

show_player:
  mode_attract_started:
    #cycle_all_lights:
     # loops: -1
      #speed: 1
    all_blink:
      loops: -1
      speed: 1
    attract_loop:
      loops: -1
  mode_attract_stopped:
    #cycle_all_lights:
    #  action: stop
    all_blink:
      action: stop
    attract_loop:
      action: stop

#sound_player:
 # mode_attract_started:
 #   main_title:
  #    action: play
    #  loops: 0
    #  mode_end_action: stop

# slides:
#   attract_started:
#     widgets:
#       - type: image
#         image: attract

# slide_player:
#   mode_attract_started:
#     attract_started
#   mode_attract_stopped:
#     attract_started:
#       action: remove

slide_player:
  flipper_cancel:
    last_game_scores:
      priority: 1
      expire: 10s
  # sw_right_flipper_active:
  #   title_screen:
  #     action: stop
