#config_version=5

mode:
   start_events:
     - mode_qualified
   stop_events:
     - end_qualify_a_mode_mode
   restart_on_next_ball: true
   priority: 710


event_player:
  mode_skill_shot_stopped:
    - ramp_down_active|.5s
  mode_qualify_a_mode_started:
    - play_what_is_that_flashing|.5s
    - ramp_diverter_disable
    - ramp_down_active{device.switches.s_up_down_ramp_switch.state == 0}|1s
  start_mode_shot_flashing_hit:
    - ramp_up_active
    - end_qualify_a_mode_mode
  mode_intro_rand_mode_started:
    - ramp_up_active
  mode_intro_annie_mode_started:
    - ramp_up_active
  mode_intro_rook_mode_started:
    - ramp_up_active
  mode_lunk_mode_started:
    - ramp_up_active
  mode_rand_mode_stopped:
    - ramp_down_active|.5s
  mode_annie_mode_stopped:
    - ramp_down_active|.5s
  mode_rook_mode_stopped:
    - ramp_down_active|.5s
  mode_lunk_mode_stopped:
    - ramp_down_active|.5s

shot_profiles:
  start_mode_profile:
    advance_on_hit: true
    states:
    - name: flashing
      show: flash_white_show
      sync_ms: 1000
      loops: -1
      speed: 5
    - name: hit
      show: off


shots:
  start_mode_shot:
    hit_events: ramp_reflex_point_sequence_hit
    profile: start_mode_profile
    show_tokens:
      leds: l_mode_start
    enable_events:
      - diverter_ramp_activating
    disable_events:
      - diverter_ramp_deactivating
    reset_events:
      - end_qualify_a_mode_mode
    debug: true


sound_player:
  play_what_is_that_flashing:
    what_is_that_flashing:
      action: play
