#config_version=5

mode:
   start_events:
     - qualify_invid_invasion
   stop_events:
     - mode_intro_invid_invasion_started
     #- game_ending
   restart_on_next_ball: true
   priority: 700

event_player:
  mode_skill_shot_stopped{mode.qualify_invid_invasion.active}:
    - ramp_down_active|.5s # {mode.qualify_invid_invasion.active}: #and not mode.skill_shot.active} #|1s #   {{mode.qualify_invid_invasion.active}|1s and not mode.skill_shot.active}
  mode_qualify_invid_invasion_started:
    - play_what_is_that_flashing|.5s
    - ramp_diverter_disable
  #   - ramp_down_active{device.switches.s_up_down_ramp_switch.state == 0}|1s  #testing
  #   - right_flipper_stronger_enable
  mode_start_invid_invasion_shot_flashing_hit:
    - start_intro_invid_invasion
    - ramp_up_active
  # ball_search_stopped:
  #   - ramp_down_active
  pity_invid_invasion_shot_flashing_hit: #s_right_lock_kickout_active{current_player.ball==3}:
    - start_intro_invid_invasion
    - ramp_up_active
  # mode_qualify_invid_invasion_stopped:
  #   - normal_flippers_enable
  diverter_ramp_activating{not mode.skill_shot.active}:
    - display_shoot_ramp_widget
  mode_corg_mode_stopped.1{device.switches.s_up_down_ramp_switch.state == 0}:
    - ramp_down_active
  mode_corg_mode_stopped.2{device.switches.s_up_down_ramp_switch.state == 1}:
    - display_shoot_ramp_widget

shots:
  mode_start_invid_invasion_shot:
    hit_events: ramp_reflex_point_sequence_hit
    profile: mode_start
    show_tokens:
      leds: l_mode_start
    enable_events:
      #- mode_qualify_invid_invasion_started
      - diverter_ramp_activating
      - mode_corg_mode_stopped
    disable_events:
      #- mode_qualify_invid_invasion_stopped
      - diverter_ramp_deactivating
      - mode_intro_corg_mode_starting
  pity_invid_invasion_shot:
    switch: s_right_lock_kickout
    profile: mode_start
    enable_events:
      - mode_skill_shot_stopped{current_player.ball==3}
      - mode_qualify_invid_invasion_started{current_player.ball==3}
      - mode_corg_mode_stopped{current_player.ball==3}
    disable_events:
      - mode_skill_shot_started
      - mode_qualify_invid_invasion_started{current_player.ball < 3}
      - s_back_ramp_active
      - mode_intro_corg_mode_starting
    show_tokens:
      leds: l_rlock_arrow

shot_profiles:
  mode_start:
    advance_on_hit: true
    states:
    - name: flashing
      show: flash_white_show
      sync_ms: 1000
      loops: -1
      speed: 5
    - name: hit
      show: off

widgets:
  qualify_invid_invasion_display_shoot_ramp_text_widget:
    - type: text
      text: "SHOOT RAMP"
      color: red
      font_size: 100
      y: center + 150
      x: center # + 300
      z: 1150
      animations:
        widgets_play:
        - property: opacity
          value: 1
          duration: .5s
        - property: opacity
          value: 0
          duration: .5s
          repeat: true

widget_player:
  display_shoot_ramp_widget:
    qualify_invid_invasion_display_shoot_ramp_text_widget:
      action: add
      slide: base_slide
      priority: 701
  diverter_ramp_deactivating{not mode.skill_shot.active}:
    qualify_invid_invasion_display_shoot_ramp_text_widget:
      action: remove
      slide: base_slide
      priority: 702
  ball_ending:
    qualify_invid_invasion_display_shoot_ramp_text_widget:
      action: remove
      slide: base_slide
      priority: 702


# show_player:
#   mode_qualify_invid_invasion_started.1:
#     flash_white_show:
#       key: normal
#       speed: 5
#       show_tokens:
#         leds: l_mode_start
#       loops: -1
    # on:
    #   show_tokens:
    #     leds: l_mission_1
  # mode_qualify_invid_invasion_started.2{current_player.ball==3}:
  #   flash_white_show:
  #     key: pity
  #     speed: 5
  #     show_tokens:
  #       leds: l_rlock_arrow
  #     loops: -1
  # mode_bonus_will_start:
  #   pity:
  #     action: stop
  #   normal:
  #     action: stop

sound_player:
  play_what_is_that_flashing:
    what_is_that_flashing:
      action: play

#shots:
#  opening_shot:
#    switch: s_left_lock_kickout
#    profile: quick_flash_green
#    show_tokens:
#      leds: l_llock_arrow

#timers:
#   alien_attack:
#     start_value: 1
#     end_value: 60
#     direction: up
#     tick_interval: 1s
#     start_running: true

#shot_profiles:
#  quick_flash_green:
#    states:
#  - name: unlit
#      show: flash_green
    #- name: lit
#  - name: complete
#      show: off
