#config_version=5

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - kickback_disable
    - ramp_diverter_disable
  ball_save_kickback_save_saving_ball:      # ball save on kickback (that goes straight to right outlane) that goes around orbit to flipper
    - orbit_gate_enable{device.switches.s_up_down_ramp_switch.state==0 and not mode.rand_mode.active} #}not mode.qualify_invid_invasion.active}
    #- orbit_gate_disable|2s
  achievement_invid_invasion_mission_1_state_enabled:
    - play_what_is_that_flashing|.5s
  invid_target_group_hit_complete:
    - drop_reset_up|2s

achievements:
  rand_mode_collect:
    show_tokens:
      leds: l_rand
    show_when_enabled: on
    show_when_started: flash
    show_when_completed: color_green_on
    show_when_stopped: color_red_on
    enable_events: rand_collected
    events_when_enabled: start_intro_rand_mode
    start_events: mode_rand_mode_started
    stop_events: mode_rand_mode_stopped
    restart_after_stop_possible: false
    complete_events: rand_mode_success
    debug: true
  annie_mode_collect:
    show_tokens:
      leds: l_annie
    show_when_enabled: on
    show_when_started: flash
    show_when_completed: color_green_on
    events_when_enabled: start_annie_mode
    start_events: mode_annie_mode_started
    stop_events: mode_annie_mode_stopped
    show_when_stopped: color_red_on
    enable_events: annie_collected
    restart_after_stop_possible: false
    complete_events: annie_mode_success
    debug: true
  rook_mode_collect:
    show_tokens:
      leds: l_lancer #add light for rook?
    show_when_enabled: on
    show_when_started: flash
    show_when_completed: color_green_on
    events_when_enabled: start_rook_mode
    start_events: mode_rook_mode_started
    stop_events: mode_rook_mode_stopped
    show_when_stopped: color_red_on
    enable_events: rook_collected
    restart_after_stop_possible: false
    complete_events: rook_mode_success
    debug: true
  invid_invasion_mission_1:
    show_tokens:
      leds: l_mission_1
    show_when_enabled: on
    show_when_started: flash
    show_when_completed: color_green_on
    show_when_stopped: color_red_on
    enable_events: invid_invasion_mission_ready
    #events_when_started:
    #events_when_completed:
    #events_when_enabled:
    start_events: mode_invid_invasion_started
    stop_events: mode_invid_invasion_stopped #timer_invid_invasion_complete
    restart_after_stop_possible: false
    complete_events: invid_invasion_success, increase_modes_completed_count
    debug: true

extra_balls:
  skillshot_extraball:
    award_events: award_extra_ball
  protoculture_extraball:
    award_events: protoculture_award_extra_ball


sequence_shots:
  ramp_reflex_point_sequence:
    switch_sequence:
      - s_back_ramp
      - s_right_lock_kickout
    sequence_timeout: 3s
  ramp_wireform_sequence:
    switch_sequence:
      - s_back_ramp
      - s_wireform_ramp
    sequence_timeout: 2s
  rand_rook_combo:
    event_sequence:
      - rand_shot_group_flashing_rand_hit
      - rook_shot_group_flashing_rook_hit
    sequence_timeout: 3s
  rook_rand_combo:
    event_sequence:
      - rook_shot_group_flashing_rook_hit
      - rand_shot_group_flashing_rand_hit
    sequence_timeout: 3s
  rook_annie_combo:
    event_sequence:
      - rook_shot_group_flashing_rook_hit
      - annie_shot_group_flashing_annie_hit
    sequence_timeout: 3s
  rand_lancer_combo:
    event_sequence:
      - rand_shot_group_flashing_rand_hit
      - lancer_shot_group_flashing_lancer_hit
    sequence_timeout: 4s


slides:
  default:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        color: white
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
        color: white
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
        color: white
  extra_ball_slide:
    widgets:
      - type: text
        text: SHOOT AGAIN
        color: red
        font_size: 130
        y: center+50
      # - type: text
      #   text: Keep Shooting
      #   color: red
      #   y: center-50
      #   font_size: 100

widgets:
  skill_shot_combo_widget:
    - type: text
      text: SKILL SHOT COMBO
      color: yellow
      font_size: 100
      y: center + 50
    - type: text
      text: 10000
      font_size: 100
      color: red
      y: center - 50
  player_num_keep_shooting_widget:
    - type: text
      text: PLAYER (number)
      color: blue
      font_size: 100
      y: center + 80
    - type: text
      text: Keep Shooting
      color: red
      y: center #- 90
      font_size: 70
  ball_saved_widget:
    - type: text
      text: BALL SAVED!!
      color: blue
      font_size: 100
      y: center + 80
    - type: text
      text: Keep Shooting
      color: red
      y: center #- 90
      font_size: 70
  skill_shot_saucer_hit_video:
    - type: video
      video: skill_shot_saucer
  skill_shot_invid_hit_video:
    - type: video
      video: skill_shot_invid
  skill_shot_lanes_hit_video:
    - type: video
      video: skill_shot_lanes
  skill_shot_failure:
    - type: text
      text: SKILL SHOT MISSED!
      font_size: 100
      color: red
      y: center + 150
  skill_shot_success:
    - type: text
      text: SKILL SHOT SUCCESS!
      font_size: 100
      color: blue
      y: center + 150
      # z: 120
    - type: text
      text: (skill_shot_value)
      font_size: 100
      color: red
      y: center-150
      # z: 120
  shatz_skill_shot_success:
    - type: text
      text: (SHATZ)
      font_size: 100
      color: blue
      y: center + 250
      # z: 120
    - type: text
      text: SKILL SHOT SUCCESS!
      font_size: 100
      color: blue
      y: center + 150
      # z: 120
    - type: text
      text: (skill_shot_value)
      font_size: 100
      color: red
      y: center-150
      # z: 120
  ball_save_kickback_save_video:
    - type: video
      video: kickback_save
  team_combo_widget:
    - type: text
      text: TEAM COMBO
      color: orange
      font_size: 100
      y: center + 50
    - type: text
      text: 10000
      font_size: 100
      color: red
      y: center-50
  # skill_shot_combo_widget:
  #   - type: text
  #     text: SKILL SHOT COMBO
  #     color: blue
  #     font_size: 100
  #     y: center + 150
  #   - type: text
  #     text: 10000
  #     font_size: 100
  #     color: red
  #     y: center-150
  # rand_qualify_image:
  #   - type: image
  #     image: rand_qualify
  #     x: center - 580
  #     y: center + 275
  # annie_qualify_image:
  #   - type: image
  #     image: annie_qualify
  #     x: center - 580
  #     y: center + 100
  # rook_qualify_image:
  #   - type: image
  #     image: rook_qualify
  #     x: center - 580
  #     y: center - 75

  # widget_ballsave:
  #   - type: text
  #     font_size: 100
  #     color: blue
  #     text: BALL SAVED!
  #     # y: 41
  #     # x: 105
  #     # z: 1302


  # ball_save_left_video:
  #   - type: video
  #     video: ball_save_left

widget_player:
  skill_shot_combo_made:
    skill_shot_combo_widget:
      action: add
      widget_settings:
        expire: 2s
  qualify_rand_1st_time:
    player_num_keep_shooting_widget:
      action: add
      slide: base_slide
      widget_settings:
        expire: 4s
        z: 115
  ball_save_default_saving_ball:
    ball_saved_widget:
      action: add
      widget_settings:
        expire: 2s
        z: 115
  ball_save_invid_invasion_multiball_saving_ball:
    ball_saved_widget:
      action: add
      widget_settings:
        expire: 2s
        z: 115
      # expire: 2s
      # priority: 1200
  saucer_skill_group_flashing_hit:
    skill_shot_saucer_hit_video:
      action: add
      widget_settings:
        expire: 2.5s
        z: 110
  invid_targets_skill_flashing_hit:
    skill_shot_invid_hit_video:
      action: add
      widget_settings:
        expire: 1.5s
        z: 110
  top_lanes_skill_flashing_hit:
    skill_shot_lanes_hit_video:
      action: add
      widget_settings:
        expire: 2.5s
        z: 110
  skill_shot_missed:
    skill_shot_failure:
      action: update
      widget_settings:
        expire: 1.5s
        z: 110
  skill_shot_made:
    skill_shot_success:
      action: add
      widget_settings:
        expire: 3s
        z: 120
  shatz_skill_shot_made:
    shatz_skill_shot_success:
      action: add
      widget_settings:
        expire: 3s
        z: 120
  ball_save_kickback_save_saving_ball:
    ball_save_kickback_save_video:
      action: add
      widget_settings:
        expire: 3s
        z: 120
  rand_rook_combo_hit:
    team_combo_widget:
      action: add
      widget_settings:
        expire: 2s
        z: 110
  rook_rand_combo_hit:
    team_combo_widget:
      action: add
      widget_settings:
        expire: 2s
        z: 110
  rand_lancer_combo_hit:
    team_combo_widget:
      action: add
      widget_settings:
        expire: 2s
        z: 110


  # mode_qualify_rand_started:
  #   rand_qualify_image:
  #     action: add
  # mode_qualify_annie_started:
  #   annie_qualify_image:
  #     action: add
  # mode_qualify_rook_started:
  #   rook_qualify_image:
  #     action: add
  # ball_save_default_saving_ball:
  #   widget_ballsave:
  #     action: update
  #     widget_settings:
  #       expire: 3s
  #       z: 110
  #       y: center-120

  # s_kickback_t_active{mode.ball_save.active}:
  #   ball_save_left_video:
  #     action: update
  #     widget_settings:
  #       expire: 5.5s
  #       z: 120

slide_player:
  # mode_base_started:
  #   default:
  #     target: window
  mode_base_starting{is_extra_ball}:
    extra_ball_slide:
      expire: 3s
      priority: 1199

# counters:
#   invid_target_group_made_qualify_invid_invasion:
#     count_events: invid_target_group_hit_complete
#     starting_count: 0
#     direction: up
#     count_complete_value: 1
#     events_when_complete: qualify_invid_invasion,  invid_invasion_mission_ready
#     persist_state: true
#     #debug: true


# shot_groups:
#   invid_target_group:
#     shots: left_target, middle_target, right_target, left_drop, middle_drop, right_drop
#     reset_events: ball_started, invid_target_group_hit_complete

show_player:
  # invid_target_group_hit_complete:
  #   invid_targets_complete:
  #     show_tokens:
  #       color: red
  s_right_orbit_rollover_active:
    fast_flash_show:
      loops: 3
      speed: 30
      show_tokens:
        leds: rorbit_rollover
        color: red
  s_left_rollover_active:
    fast_flash_show:
      loops: 3
      speed: 30
      show_tokens:
        leds: llock_rollover
        color: red
  s_right_rollover_active:
    fast_flash_show:
      loops: 3
      speed: 30
      show_tokens:
        leds: rlock_rollover
        color: red
  extra_ball_awarded:
    on:
      key: extraball_awarded_show
      show_tokens:
        leds: l_shoot_again

variable_player:
  # r_top_lane_shot_unlit_hit:
  #   score: 1000
  # o1_top_lane_shot_unlit_hit:
  #   score: 1000
  # b_top_lane_shot_unlit_hit:
  #   score: 1000
  # o2_top_lane_shot_unlit_hit:
  #   score: 1000
  # r_top_lane_shot_lit_hit:
  #   score: 500
  # o1_top_lane_shot_lit_hit:
  #   score: 500
  # b_top_lane_shot_lit_hit:
  #   score: 500
  # o2_top_lane_shot_lit_hit:
  #   score: 500
  # robo_lanes_default_lit_complete:
  #   score: 10000
  # shot_left_outlane_t_hit:
  #   score: 1000
  # s_left_inlane_e_active:
  #   score: 1000
  # s_right_inlane_c_active:
  #   score: 1000
  # s_right_outlane_h_active:
  #   score: 1000
#  tech_lanes_default_lit_complete:
#    score: 10000
  spinner_shot_hit:
    score: 100
  # pops_shot_hit:
  #   score: 100
  slings_shot_hit:
    score: 10
  # s_top_target_active:
  #   score: 1000
  s_right_orbit_rollover_active:
    score: 1000
  s_right_rollover_active:
    score: 1000
  s_left_rollover_active:
    score: 1000
  # s_s_target_active:
  #   score: 1000
  # s_d_target_active:
  #   score: 1000
  # s_f_target_active:
  #   score: 1000
  # sdf_bank_default_lit_complete:
  #   score: 10000
  s_left_target_active:
    score: 1000
  s_middle_target_active:
    score: 1000
  s_right_target_active:
    score: 1000
  s_right_drop_target_active:
    score: 1000
  s_middle_drop_target_active:
    score: 1000
  s_left_drop_target_active:
    score: 1000
  invid_target_group_hit_complete:
    score: 10000
  s_right_top1_rubber_active:
    score: 50
  s_right_top2_rubber_active:
    score: 50
  s_middle_right_rubber_active:
    score: 50
  s_lower_right_rubber_active:
    score: 50
  s_left_top_rubber_active:
    score: 50
  s_left_top_rubber2_active:
    score: 50
  s_left_middle_rubber_active:
    score: 50
  s_left_bottom_rubber_active:
    score: 50
  s_left_lock_kickout_active:
    score: 1000
  s_right_lock_kickout_active:
    score: 1000
  s_top_lock_kickout_active:
    score: 1000
  achievement_rand_mode_collect_state_completed:
    modes_completed: 1
  achievement_invid_invasion_mission_1_state_completed:
    modes_completed: 1
  rand_rook_combo_hit:
    score: 10000
  rook_rand_combo_hit:
    score: 10000
  rand_lancer_combo_hit:
    score: 10000
  rook_combo_shot_flashing_combo_hit:
    score: 10000

#shows:
#  flash_green:
#  - duration: +75ms
#    lights:
#      (leds): green
#  - duration: +75ms
#    lights:
#      (leds): off

# shot_profiles:
#   invid_profile:
#     show_when_disabled: false
#     states:
#       # - name: unlit
#       #   show: off
#       - name: flashing
#         show: flash_red_show #invid_flash_red_show
#         speed: 15
#       - name: hit
#         show: color_red_on
#               # - name: unlit
#               #   show: off
#         # show_tokens:
#         #   color: red

# shows:
  # invid_flash_red_show:
  #   - time: 0
  #     lights:
  #       (leds): red
  #   - time: +1
  #     lights:
  #       (leds): black
  # color_red_on:
  #   - time: 0
  #     lights:
  #       (leds): red
  #   - time: -1
  # color_green_on:
  #   - time: 0
  #     lights:
  #       (leds): green
  #   - time: -1

shots:
  spinner_shot:
    switch: s_spinner
  slings_shot:
    switch: s_right_slingshot, s_left_slingshot
  pops_shot:
    switch: s_top_r_pop_bumper, s_top_l_pop_bumper, s_bottom_r_pop_bumper, s_bottom_l_pop_bumper
  # left_target:
  #   switch: s_left_target
  #   profile: invid_profile
  #   show_tokens:
  #     leds: l_t1
  # middle_target:
  #   switch: s_middle_target
  #   profile: invid_profile
  #   show_tokens:
  #     leds: l_t2
  # right_target:
  #   switch: s_right_target
  #   profile: invid_profile
  #   show_tokens:
  #     leds: l_t3
  # left_drop:
  #   switch: s_left_drop_target
  #   profile: invid_profile
  #   show_tokens:
  #     leds: l_t4
  # middle_drop:
  #   switch: s_middle_drop_target
  #   profile: invid_profile
  #   show_tokens:
  #     leds: l_t5
  #   #debug: True
  # right_drop:
  #   switch: s_right_drop_target
  #   profile: invid_profile
  #   show_tokens:
  #     leds: l_t6
  # right_orbit_rollover:
  #   switch: s_right_orbit_rollover
  #   show_tokens: rorbit_rollover
  #     leds: rorbit_rollover
  # left_rollover:
  #   switch: s_left_rollover
  #   show_tokens:
  #     leds: llock_rollover
  # right_rollover:
  #   switch: s_right_rollover
  #   show_tokens:
  #     leds: rlock_rollover

  # s_target_shot:
  #   switch: s_s_target
  # d_target_shot:
  #   switch: s_d_target
  #    #profile: quick_flash
  #   show_tokens:
  #     leds: l_d_led
  # f_target_shot:
  #   switch: s_f_target
  #   #profile: quick_flash
  #   show_tokens:
  #     leds: l_f_led

sound_player:
  ball_started{player==1 and ball==1}:
    start:
      action: play
  play_what_is_that_flashing:
    what_is_that_flashing:
      action: play
  s_plunger_lane_inactive: firepower_launch_sound
  slings_shot_hit: sling_sound
  # sw_sdf_active: sdf_target_sound
  #s_spinner_active: spinner

  # ball_save_default_saving_ball:
  #   come_back_my_scott:
  #     action: play
  #     events_when_stopped: mode_ball_saved_done
