# config_version=4

mode:
  start_events: ball_starting
  priority: 100

shot_groups:
  tech_lanes:
    rotate_left_events: sw_left_flipper
#    rotate_right_events: sw_right_flipper
    reset_events:
      tech_lanes_default_lit_complete: 10ms
  robo_lanes:
#    rotate_left_events: sw_left_flipper
    rotate_right_events: sw_right_flipper
    reset_events:
      robo_lanes_default_lit_complete: 10ms    

show_player:
   tech_lanes_default_lit_complete:
      tech_lanes_complete:
        loops: 3
        show_tokens:
           color: red
      tech_hotdog:
        loops: 0
        show_tokens:
           color: red
   robo_lanes_default_lit_complete:
      robo_lanes_complete:
        loops: 3
        show_tokens:
           color: red
      robo_hotdog:   
        loops: 0
        show_tokens: 
           color: red
   invid_target_group_complete:
      invid_targets_complete:
        loops: 0
        show_tokens:
           color: red

logic_blocks:
   accruals:
       light_multiplier:
           events:
               - robo_lanes_default_lit_complete, tech_lanes_default_lit_complete
           events_when_complete: increment_multipliers, light_multiplier_led
           enable_events: ball_started
           disable_events: ball_ended
           reset_events: ball_ended
   counters:
       multiplier_count:
           count_events: increment_multipliers
           starting_count: 1
           count_complete_value: 5
           direction: up

show_player:
   light_multiplier_led:
     leds: l_2x
#     show: on
