#config_version=5

mode:
  start_events:
    - rand_mode_success
  stop_events:
    - ball_will_end
    - collect_mecha_rand_mode_done
  stop_on_ball_end: true
  priority: 2300

queue_event_player:
  rand_mode_collect_mecha_shot_group_flashing_hit:
    queue_event: my_queue_collect_mecha_rand_mode
    events_when_finished: collect_mecha_rand_mode_done

queue_relay_player:
  my_queue_collect_mecha_rand_mode:
    post: start_collect_mecha_rand_mode_display
    wait_for: collect_mecha_rand_mode_show_ended
  balldevice_bd_left_lock_ball_eject_attempt:
    post: wait_for_collect_mecha_rand_mode_display
    wait_for: collect_mecha_rand_mode_show_ended


shot_groups:
    rand_mode_collect_mecha_shot_group:
      shots: rand_mode_collect_mecha_shot
      enable_events: mode_collect_mecha_rand_mode_started
      disable_events: rand_mode_collect_mecha_shot_group_flashing_hit


shot_profiles:
  collect_mecha_flash:
    advance_on_hit: true
    states:
      - name: flashing
        show: flash_blue_show
        loops: -1
        speed: 10
      - name: hit
        show: off

shots:
  rand_mode_collect_mecha_shot:
    switch: s_left_lock_kickout
    profile: collect_mecha_flash
    show_tokens:
      leds: l_llock_arrow

shows:
  collect_mecha_rand_mode_display:
    - duration: 5
      slides:
        rand_mode_mecha_collected_slide:
          widgets:
            - type: text
              text: CYCLONE Collected
              color: red
              font_size: 80
              x: center
              y: center+300
            - type: video
              video: cyclone_collect
              # x: center
              # y: center-50

show_player:
  start_collect_mecha_rand_mode_display:
    collect_mecha_rand_mode_display:
      loops: 0
      events_when_stopped: collect_mecha_rand_mode_show_ended
    # alert_show:
    #   loops: -1
  flipper_cancel:
    collect_mecha_rand_mode_display:
      action: stop
