#config_version=5

mode:
  start_events:
    - start_end_the_fortress_mode
  stop_events:
    - end_the_fortress_player_continue_show_ended
  priority: 8300

event_player:
  mode_end_the_fortress_started:
    - ramp_up_active{device.switches.s_up_down_ramp_switch.state == 1}
    - flipper_off
    - disable_Upper_Left_pop_bumper
    - disable_Upper_Right_pop_bumper
    - disable_Lower_Left_pop_bumper
    - disable_Lower_Right_pop_bumper
    - disable_sling
    - kickback_disable{mode.kickback.active}
    - ramp_diverter_disable
    - drop_reset_up #|1
  end_the_fortress_player_continue_show_ended:
    - flipper_on
    - enable_Upper_Left_pop_bumper
    - enable_Upper_Right_pop_bumper
    - enable_Lower_Left_pop_bumper
    - enable_Lower_Right_pop_bumper
    - enable_sling
    - kickback_enable{mode.kickback.active}
    - start_skill_shot_mode
    - restart_main_title
  mode_end_the_fortress_stopping{(device.achievements.genesis_pit.state != "completed" and device.achievements.genesis_pit.state != "stopped") or (device.achievements.big_apple.state != "completed" and device.achievements.big_apple.state != "stopped")}:
    - start_pre_qualify_a_mode


timers:
  eject_mystery_ball_end_the_fortress_timer:
    debug: true
    start_value: 2
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: check_if_okay_to_hold

queue_event_player:
  mode_end_the_fortress_started:
    queue_event: my_queue_end_the_fortress
    events_when_finished: end_end_the_fortress

queue_relay_player:
  my_queue_end_the_fortress:
    post: start_end_the_fortress_intro
    wait_for: end_the_fortress_show_ended
  balldevice_bd_trough_ball_eject_attempt:
    post: wait_for_instructions_the_fortress
    wait_for: end_the_fortress_player_continue_show_ended

shows:
  end_the_fortress_ball_over:
    - duration: 16
      slides:
        end_the_fortress_ball_over_slide:
          widgets:
            - type: text
              text: "BALL LOST"
              color: white
              font_size: 80
              y: center + 300
            - type: video
              video: end_the_fortress_mode_video
            - type: text
              text: "DON'T MOVE"
              font_size: 80
              color: red
              x: center
              y: center - 300
              animations:
                show_slide:
                - property: opacity
                  value: 1
                  duration: .5s
                - property: opacity
                  value: 0
                  duration: .5s
                  repeat: true
  end_the_fortress_timer_expired:
    - duration: 16
      slides:
        end_the_fortress_timer_expired_slide:
          widgets:
            - type: text
              text: "TIMER EXPIRED!"
              color: blue
              font_size: 80
              y: center + 300
            - type: video
              video: end_the_fortress_mode_video
            - type: text
              text: "DON'T MOVE"
              font_size: 80
              color: red
              x: center
              y: center - 300
              animations:
                show_slide:
                - property: opacity
                  value: 1
                  duration: .5s
                - property: opacity
                  value: 0
                  duration: .5s
                  repeat: true
  end_the_fortress_super_jackpot_collected:
    - duration: 22
      slides:
        end_the_fortress_super_jackpot_collected_slide:
          widgets:
            - type: text
              text: "SUPER JACKPOT COLLECTED!"
              color: purple
              font_size: 80
              y: center + 300
            - type: video
              video: end_the_fortress_mode_jackpot_video
            - type: text
              text: "DON'T MOVE"
              font_size: 80
              color: red
              x: center
              y: center - 300
              animations:
                show_slide:
                - property: opacity
                  value: 1
                  duration: .5s
                - property: opacity
                  value: 0
                  duration: .5s
                  repeat: true
  end_the_fortress_player_continue_show:
    - duration: 3
      slides:
        end_the_fortress_player_continue_slide:
          widgets:
            - type: text
              text: PLAYER (number)
              color: blue
              font_size: 120
              y: center + 90
            - type: text
              text: Keep Shooting
              color: red
              y: center - 10
              font_size: 90

light_player:
  mode_end_the_fortress_started:
    gi_string:
      color: off
    playfield:
      color: off
      priority: 8000
  mode_end_the_fortress_stopped:
    gi_string:
      color: on
    playfield:
      color: on

show_player:
  start_end_the_fortress_intro.1{current_player.mode_end_action_flag == 0}:
    end_the_fortress_ball_over:
      loops: 0
      events_when_stopped: end_the_fortress_show_ended
  start_end_the_fortress_intro.2{current_player.mode_end_action_flag == 1}:
    end_the_fortress_timer_expired:
      loops: 0
      events_when_stopped: end_the_fortress_show_ended
  start_end_the_fortress_intro.3{current_player.mode_end_action_flag == 2}:
    end_the_fortress_super_jackpot_collected:
      loops: 0
      events_when_stopped: end_the_fortress_show_ended
  flipper_cancel.1{device.ball_devices.bd_trough.balls==4}:
    end_the_fortress_timer_expired:
      action: stop
  flipper_cancel.2{device.ball_devices.bd_trough.balls==4}:
    end_the_fortress_ball_over:
      action: stop
  flipper_cancel.3{device.ball_devices.bd_trough.balls==4}:
    end_the_fortress_super_jackpot_collected:
      action: stop
  end_the_fortress_show_ended:
    end_the_fortress_player_continue_show:
      loops: 0
      events_when_stopped: end_the_fortress_player_continue_show_ended

variable_player:
  end_the_fortress_player_continue_show_ended:
    mode_end_action_flag:
      int: 0
      action: set
  mode_end_the_fortress_started:
    the_fortress_mode_total_points:
      int: current_player.score - current_player.the_fortress_start_mode_score
      action: set
