#config_version=5

mode:
  start_events:
    #- start_rook_mode
    - mode_intro_rook_mode_started
  stop_events:
    - timer_rook_mode_timer_complete
    - ball_will_end
    - rook_mode_success
  stop_on_ball_end: true
  priority: 4700

event_player:
  mode_rook_mode_started.1:
    logicblock_biker_gang_defeated_counter_hit:
      count: 0
    logicblock_biker_1_shots_made_counter_hit{device.counters.biker_1_shots_made_counter.value == 15}:
      count: 15
    logicblock_biker_2_shots_made_counter_hit{device.counters.biker_2_shots_made_counter.value == 15}:
      count: 15
    logicblock_biker_3_shots_made_counter_hit{device.counters.biker_3_shots_made_counter.value == 15}:
      count: 15
    logicblock_biker_4_shots_made_counter_hit{device.counters.biker_4_shots_made_counter.value == 15}:
      count: 15
    logicblock_biker_1_shots_made_counter_hit{device.counters.biker_1_shots_made_counter.value == 20}:
      count: 20
    logicblock_biker_2_shots_made_counter_hit{device.counters.biker_2_shots_made_counter.value == 20}:
      count: 20
    logicblock_biker_3_shots_made_counter_hit{device.counters.biker_3_shots_made_counter.value == 20}:
      count: 20
    logicblock_biker_4_shots_made_counter_hit{device.counters.biker_4_shots_made_counter.value == 20}:
      count: 20
  mode_rook_mode_started.2:
    timer_rook_mode_timer_tick:
      ticks_remaining: 60
  mode_rook_mode_started.3:
    - display_rook_mode_widgets
  multiball_rook_mode_multiball_started:
    - drop_reset_up
    - play_rook_mode_music
  drop_target_left_drop_down:
    - drop_reset_up|1s
  drop_target_middle_drop_down:
    - drop_reset_up|1s
  drop_target_right_drop_down:
    - drop_reset_up|1s
  # mode_rook_mode_stopping:
  #   - enable_Upper_Left_pop_bumper
  #   - enable_Upper_Right_pop_bumper
  #   - enable_Lower_Left_pop_bumper
  #   - enable_Lower_Right_pop_bumper
  # timer_rook_mode_timer_started:
  #   logicblock_biker_gang_defeated_counter_hit:
  #     count: 0
  #   logicblock_biker_1_shots_made_counter_hit{device.counters.biker_1_shots_made_counter.value == 15}:
  #     count: 15
  #   logicblock_biker_2_shots_made_counter_hit{device.counters.biker_2_shots_made_counter.value == 15}:
  #     count: 15
  #   logicblock_biker_3_shots_made_counter_hit{device.counters.biker_3_shots_made_counter.value == 15}:
  #     count: 15
  #   logicblock_biker_4_shots_made_counter_hit{device.counters.biker_4_shots_made_counter.value == 15}:
  #     count: 15
  #   logicblock_biker_1_shots_made_counter_hit{device.counters.biker_1_shots_made_counter.value == 20}:
  #     count: 20
  #   logicblock_biker_2_shots_made_counter_hit{device.counters.biker_2_shots_made_counter.value == 20}:
  #     count: 20
  #   logicblock_biker_3_shots_made_counter_hit{device.counters.biker_3_shots_made_counter.value == 20}:
  #     count: 20
  #   logicblock_biker_4_shots_made_counter_hit{device.counters.biker_4_shots_made_counter.value == 20}:
  #     count: 20
  logicblock_biker_gang_defeated_counter_updated.1{value==1}:
    - biker_1st_done
  logicblock_biker_gang_defeated_counter_updated.2{value==2}:
    - biker_2nd_done

multiballs:
  rook_mode_multiball:
    ball_count: 1
    ball_count_type: add #total
    start_or_add_a_ball_events:
      #- mode_rook_mode_started
      - stop_intro_rook_mode
      - rook_mode_rand_add_ball_hit
    #add_a_ball_events: rook_mode_rand_add_ball_hit
    ball_locks: bd_right_lock
    shoot_again: 0
    # disable_events:
    #   - mode_rook_mode_stopping
    debug: true

widgets:
  rook_mode_time_display_widget:
    - type: text
      text: TIMER
      color: blue
      font_size: 100
      y: center + 220
      x: center - 450
      z: 1101
  rook_mode_timer_widget:
    - type: text
      text: (ticks_remaining)
      color: red
      font_size: 100
      y: center + 150
      x: center - 450
      z: 1101
  rook_left_rectangle:
    - type: rectangle
      anchor_x: left
      anchor_y: bottom
      x: 13
      y: 190
      z: 1100
      width: 125
      height: 500
      color: black
  rook_right_rectangle:
    - type: rectangle
      anchor_x: left
      anchor_y: bottom
      x: 1130
      y: 190
      z: 1100
      width: 130
      height: 500
      color: black
  rook_mode_gang_display_widget:
    - type: text
      text: "Biker Gang"
      color: 2E0854 #purple
      font_size: 80
      y: center + 220
      x: center + 450
      z: 1101
  rook_mode_gang_count_widget:
    - type: text
      text: "(count)/3"
      color: green
      font_size: 100
      y: center + 150
      x: center + 445
      z: 1101
  biker_1_circle:
    - type: ellipse
      width: 125
      height: 125
      x: center - 100
      y: center + 100
      z: 1100
      color: red
  biker_2_circle:
    - type: ellipse
      width: 125
      height: 125
      x: center + 100
      y: center + 100
      z: 1100
      color: red
  biker_3_circle:
    - type: ellipse
      width: 125
      height: 125
      x: center - 100
      y: center - 100
      z: 1100
      color: red
  biker_4_circle:
    - type: ellipse
      width: 125
      height: 125
      x: center + 100
      y: center - 100
      z: 1100
      color: red
  rook_mode_biker_1_count_widget:
    - type: text
      text: (count)
      color: black
      font_size: 50
      x: center - 100
      y: center + 100
      z: 1101
  rook_mode_biker_2_count_widget:
    - type: text
      text: (count)
      color: black
      font_size: 50
      x: center + 100
      y: center + 100
      z: 1101
  rook_mode_biker_3_count_widget:
    - type: text
      text: (count)
      color: black
      font_size: 50
      x: center - 100
      y: center - 100
      z: 1101
  rook_mode_biker_4_count_widget:
    - type: text
      text: (count)
      color: black
      font_size: 50
      x: center + 100
      y: center - 100
      z: 1101

widget_player:
  #timer_rook_mode_timer_started:
  display_rook_mode_widgets:
    rook_left_rectangle:
      action: add
      slide: base_slide
      priority: 4701
    rook_right_rectangle:
      action: add
      slide: base_slide
      priority: 4702
    rook_mode_time_display_widget:
      action: add
      slide: base_slide
      priority: 4703
    rook_mode_timer_widget:
      action: update
      slide: base_slide
      priority: 4704
    rook_mode_gang_display_widget:
      action: add
      slide: base_slide
      priority: 4705
    rook_mode_gang_count_widget:
      action: update
      slide: base_slide
      priority: 4706
    biker_1_circle:
      action: add
      slide: base_slide
      priority: 4707
    biker_2_circle:
      action: add
      slide: base_slide
      priority: 4708
    biker_3_circle:
      action: add
      slide: base_slide
      priority: 4709
    biker_4_circle:
      action: add
      slide: base_slide
      priority: 4710
  timer_rook_mode_timer_tick:
    rook_mode_timer_widget:
      action: update
      slide: base_slide
      priority: 4711
  logicblock_biker_gang_defeated_counter_hit:
    rook_mode_gang_count_widget:
      action: update
      slide: base_slide
      priority: 4712
  logicblock_biker_1_shots_made_counter_hit:
    rook_mode_biker_1_count_widget:
      action: update
      slide: base_slide
      priority: 4713
  logicblock_biker_2_shots_made_counter_hit:
    rook_mode_biker_2_count_widget:
      action: update
      slide: base_slide
      priority: 4714
  logicblock_biker_3_shots_made_counter_hit:
    rook_mode_biker_3_count_widget:
      action: update
      slide: base_slide
      priority: 4715
  logicblock_biker_4_shots_made_counter_hit:
    rook_mode_biker_4_count_widget:
      action: update
      slide: base_slide
      priority: 4716
  # mode_rook_mode_stopped:
  #   rook_left_rectangle:
  #     action: remove
  #     slide: base_slide
  #   rook_right_rectangle:
  #     action: remove
  #     slide: base_slide
  #   biker_1_circle:
  #     action: remove
  #     slide: base_slide
  #   biker_2_circle:
  #     action: remove
  #     slide: base_slide
  #   biker_3_circle:
  #     action: remove
  #     slide: base_slide
  #   biker_4_circle:
  #     action: remove
  #     slide: base_slide
  #   rook_mode_biker_1_count_widget:
  #     action: remove
  #     slide: base_slide
  #   rook_mode_biker_2_count_widget:
  #     action: remove
  #     slide: base_slide
  #   rook_mode_biker_3_count_widget:
  #     action: remove
  #     slide: base_slide
  #   rook_mode_biker_4_count_widget:
  #     action: remove
  #     slide: base_slide

slides:
  rook_mode_1st_kill_slide:
    widgets:
      - type: text
        text: BIKER DEFEATED
        font_size: 80
        color: blue
        x: center
        y: center+300
        # z: 120
      - type: video
        video: rook_mode_1st_kill
      - type: text
        text: (biker_kill_value)
        font_size: 80
        color: red
        x: center
        y: center-300
        number_grouping: true
        # z: 120
  rook_mode_2nd_kill_slide:
    widgets:
      - type: text
        text: BIKER DEFEATED
        font_size: 80
        color: blue
        x: center
        y: center+300
        # z: 120
      - type: video
        video: rook_mode_2nd_kill
      - type: text
        text: (biker_kill_value)
        font_size: 80
        color: red
        x: center
        y: center-300
        number_grouping: true
        # z: 120

slide_player:
  biker_1st_done:
    rook_mode_1st_kill_slide:
      expire: 6s
  biker_2nd_done:
    rook_mode_2nd_kill_slide:
      expire: 6s
      #priority: 4705

timers:
  rook_mode_timer:
    debug: true
    start_value: 60
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: multiball_rook_mode_multiball_started
      - action: add
        event: spinner_shot_hit
        value: current_player.spinner_time_value
      - action: add
        event: add_10s
        value: 10
      - action: pause
        event: mystery_shot_flashing_hit{game.balls_in_play==1}
        value: 5

shot_profiles:
  rook_mode_rand_add_ball_flash:
    advance_on_hit: true
    states:
      - name: flashing
        show: flash_red_show
        loops: -1
        speed: 10
      - name: hit
        show: off

shots:
  rook_mode_rand_add_ball:
    switch: s_left_lock_kickout
    profile: rook_mode_rand_add_ball_flash
    show_tokens:
      leds: l_llock_arrow
    enable_events: ball_save_rook_mode_multiball_disabled
    disable_events: rook_mode_rand_add_ball_hit
  biker_1:
    switch: s_top_l_pop_bumper
    enable_events: mode_rook_mode_started
    disable_events: biker_1_complete
  biker_2:
    switch: s_top_r_pop_bumper
    enable_events: mode_rook_mode_started
    disable_events: biker_2_complete
  biker_3:
    switch: s_bottom_l_pop_bumper
    enable_events: mode_rook_mode_started
    disable_events: biker_3_complete
  biker_4:
    switch: s_bottom_r_pop_bumper
    enable_events: mode_rook_mode_started
    disable_events: biker_4_complete


# sequence_shots:
#   right_obit_shot_sequence:
#     switch_sequence:
#       - s_spinner
#       - s_right_orbit_rollover
#       - s_gate_top_right
#     sequence_timeout: 2s

counters:
  biker_1_shots_made_counter:
    count_events: biker_1_hit
    starting_count: current_player.rook_mode_pop_bumpers_count
    count_complete_value: 0
    events_when_complete: add_10s, biker_1_complete #, disable_Upper_Left_pop_bumper
    disable_on_complete: true
    reset_on_complete: false
    direction: down
    debug: true
  biker_2_shots_made_counter:
    count_events: biker_2_hit
    starting_count: current_player.rook_mode_pop_bumpers_count
    count_complete_value: 0
    events_when_complete: add_10s, biker_2_complete #, disable_Upper_Right_pop_bumper
    disable_on_complete: true
    reset_on_complete: false
    direction: down
    debug: true
  biker_3_shots_made_counter:
    count_events: biker_3_hit
    starting_count: current_player.rook_mode_pop_bumpers_count
    count_complete_value: 0
    events_when_complete: add_10s, biker_3_complete #, disable_Lower_Left_pop_bumper
    disable_on_complete: true
    reset_on_complete: false
    direction: down
    debug: true
  biker_4_shots_made_counter:
    count_events: biker_4_hit
    starting_count: current_player.rook_mode_pop_bumpers_count
    count_complete_value: 0
    events_when_complete: add_10s, biker_4_complete #, disable_Lower_Right_pop_bumper
    disable_on_complete: true
    reset_on_complete: false
    direction: down
    debug: true
  biker_gang_defeated_counter:
    count_events:
      - biker_1_complete
      - biker_2_complete
      - biker_3_complete
      - biker_4_complete
    starting_count: 0
    count_complete_value: 3
    events_when_complete:
      - rook_mode_success
      - biker_3rd_done

show_player:
  mode_rook_mode_started:
    biker_1_pulse_show:
      show_tokens:
        leds: l_upper_l_pop_bumper
      loops: -1
    biker_2_pulse_show:
      show_tokens:
        leds: l_upper_r_pop_bumper
      loops: -1
    biker_3_pulse_show:
      show_tokens:
        leds: l_lower_l_pop_bumper
      loops: -1
    biker_4_pulse_show:
      show_tokens:
        leds: l_lower_r_pop_bumper
      loops: -1
  biker_1_hit:
    flash_pops_red_show:
      key: biker_1_flash_show
      show_tokens:
        leds: l_upper_l_pop_bumper
      priority: 4701
      loops: 2
  biker_2_hit:
    flash_pops_red_show:
      key: biker_2_flash_show
      show_tokens:
        leds: l_upper_r_pop_bumper
      priority: 4701
      loops: 2
  biker_3_hit:
    flash_pops_red_show:
      key: biker_3_flash_show
      show_tokens:
        leds: l_lower_l_pop_bumper
      priority: 4701
      loops: 2
  biker_4_hit:
    flash_pops_red_show:
      key: biker_4_flash_show
      show_tokens:
        leds: l_lower_r_pop_bumper
      priority: 4701
      loops: 2
  biker_1_complete:
    biker_1_pulse_show:
      action: stop
    turn_pop_black:
      key: biker_1_black_show
      show_tokens:
        leds: l_upper_l_pop_bumper
  biker_2_complete:
    biker_2_pulse_show:
      action: stop
    turn_pop_black:
      key: biker_2_black_show
      show_tokens:
        leds: l_upper_r_pop_bumper
  biker_3_complete:
    biker_3_pulse_show:
      action: stop
    turn_pop_black:
      show_tokens:
        leds: l_lower_l_pop_bumper
  biker_4_complete:
    biker_4_pulse_show:
      action: stop
    turn_pop_black:
      show_tokens:
        leds: l_lower_r_pop_bumper

variable_player:
  biker_1st_done:
    biker_kill_value:
      int: 25000 * current_player.pf_multiplier
      action: set
    score: 25000 * current_player.pf_multiplier
  biker_2nd_done:
    biker_kill_value:
      int: 35000 * current_player.pf_multiplier
      action: set
    score: 35000 * current_player.pf_multiplier
  biker_3rd_done:
    biker_kill_value:
      int: 50000 * current_player.pf_multiplier
      action: set
    score: 50000 * current_player.pf_multiplier
  rook_mode_success:
    rook_mode_bonus_time_score:
      int: (device.timers.rook_mode_timer.ticks * 500 * game.balls_in_play) * current_player.pf_multiplier
      action: set
    score: (device.timers.rook_mode_timer.ticks * 500 * game.balls_in_play) * current_player.pf_multiplier

sound_player:
  rook_mode_rand_add_ball_hit: rook_add_a_ball
  play_rook_mode_music:
    rook_mode_confrontation:
      action: play
      loops: -1
