#config_version=5

mode:
  start_events:
    - super_pops
  stop_events:
    - ball_ended
  priority: 2700


show_player:
  s_bottom_r_pop_bumper_active:
    flash_pop_bumper_purple:
      loops: 0
      show_tokens:
        leds: l_lower_r_pop_bumper
  s_bottom_l_pop_bumper_active:
    flash_pop_bumper_purple:
      loops: 0
      show_tokens:
        leds: l_lower_l_pop_bumper
  s_top_r_pop_bumper_active:
    flash_pop_bumper_purple:
      loops: 0
      show_tokens:
        leds: l_upper_r_pop_bumper
  s_top_l_pop_bumper_active:
    flash_pop_bumper_purple:
      loops: 0
      show_tokens:
        leds: l_upper_l_pop_bumper

variable_player:
  pops_shot_hit:
    score: 1000
