#config_version=5

mode:
  start_events:
    - start_spinner_level_1_mode #mode_base_started #ball_starting
  stop_events:
    - mode_invid_invasion_stopped
    - mode_genesis_pit_stopped
    - mode_the_fortress_stopped
    - mode_big_apple_stopped
    - spinner_level_2
    - ball_ended
  priority: 7500

event_player:
  mode_spinner_level_1_started:
    logicblock_spinner_level_1_hit_counter_hit:
      count:
        value: device.counters.spinner_level_1_hit_counter.value
  # mode_end_invid_invasion_stopped:
  #   logicblock_spinner_level_1_hit_counter_hit:
  #     count:
  #       value: device.counters.spinner_level_1_hit_counter.value
  # mode_rand_mode_stopped:
  #   logicblock_spinner_level_1_hit_counter_hit:
  #     count:
  #       value: device.counters.spinner_level_1_hit_counter.value
  # mode_annie_mode_stopped:
  #   logicblock_spinner_level_1_hit_counter_hit:
  #     count:
  #       value: device.counters.spinner_level_1_hit_counter.value
  # mode_rook_mode_stopped:
  #   logicblock_spinner_level_1_hit_counter_hit:
  #     count:
  #       value: device.counters.spinner_level_1_hit_counter.value

counters:
  spinner_level_1_hit_counter:
    count_events: spinner_shot_hit
    starting_count: current_player.spinner_initial_count
    direction: down
    count_complete_value: 0
    reset_on_complete: true
    events_when_complete: spinner_level_2
    disable_on_complete: false
    enable_events:
      - mode_spinner_level_1_started
      - mode_rand_mode_stopped
      - mode_annie_mode_stopped
      - mode_rook_mode_stopped
      - mode_lunk_mode_stopped
      - mode_corg_mode_stopped
      # - mode_end_invid_invasion_stopped
      # - mode_genesis_pit_stopped
      # - mode_the_fortress_stopped
    disable_events:
      - mode_intro_rand_mode_started
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_intro_corg_mode_started
      # - mode_intro_invid_invasion_started
      # - mode_intro_genesis_pit_started
      # - mode_intro_the_fortress_started
    persist_state: false
    debug: true

widgets:
  spinner_level_1_count_widget:
    - type: text
      text: "SPINNER: L1 - (count)"
      color: white
      font_size: 35
      x: center + 450
      y: center - 230
    - type: text
      text: "Value: 500"
      color: white
      font_size: 30
      x: center + 450
      y: center - 260

widget_player:
  logicblock_spinner_level_1_hit_counter_hit:
    spinner_level_1_count_widget:
      action: add
      slide: base_slide
      priority: 7501
  # mode_intro_invid_invasion_started:
  #   spinner_level_1_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_intro_rand_mode_started:
  #   spinner_level_1_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_annie_mode_started:
  #   spinner_level_1_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_into_rook_mode_started:
  #   spinner_level_1_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_lunk_mode_started:
  #   spinner_level_1_count_widget:
  #     action: remove
  #     slide: base_slide

variable_player:
  spinner_shot_hit:
    score: 500 * current_player.pf_multiplier
  mode_spinner_level_1_started:
    spinner_time_value:
      int: 1
      action: set

sound_player:
  spinner_shot_hit:
    spinner_sound:
      action: play

show_player:
  spinner_shot_hit:
    flash_spinner_white:
      loops: 0
      show_tokens:
        leds: l_spinner_flasher
