#config_version=5

mode:
  start_events:
    - start_add_1x_playfield_multiplier_mystery_award_mode
  stop_events:
    - timer_add_1x_playfield_multiplier_mystery_award_timer_complete
  stop_on_ball_end: true
  priority: 8360

event_player:
  player_pf_multiplier.1{mode.marlene_mode.active}:
    - stop_2x_show_mystery
  player_pf_multiplier.2{mode.lancer_mode.active}:
    - stop_2x_show_mystery

timers:
  add_1x_playfield_multiplier_mystery_award_timer:
    debug: true
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_qualify_mystery_stopped

variable_player:
  mode_add_1x_playfield_multiplier_mystery_award_started:
    pf_multiplier: 1
  mode_add_1x_playfield_multiplier_mystery_award_stopping:
    pf_multiplier: -1


show_player:
  mode_qualify_mystery_stopped{current_player.pf_multiplier==2 and not mode.marlene_mode.active and not mode.lancer_mode.active}:
    flash_multiplier_2x_led:
      key: mystery_2x_flash
      loops: -1
      sync_ms: 1000
  mode_add_1x_playfield_multiplier_mystery_award_stopped{current_player.pf_multiplier==2 and not mode.marlene_mode.active and not mode.lancer_mode.active}:
    mystery_2x_flash:
      action: stop
  stop_2x_show_mystery:
    mystery_2x_flash:
      action: stop
