#config_version=5

mode:
  start_events:
    - spinner_level_3
  stop_events:
    - mode_invid_invasion_stopped
    - mode_genesis_pit_stopped
    - mode_the_fortress_stopped
    - mode_big_apple_stopped
    - spinner_super
    - ball_ended
  priority: 7700

event_player:
  # mode_spinner_level_3_starting{not mode.invid_invasion.active or not mode.genesis_pit.active or not mode.rand_mode.active or not mode.annie_mode.active or not mode.rook_mode.active or not mode.lunk_mode.active}:
  #     - enable_spinner_level_3
  #mode_spinner_level_3_started.1{mode.invid_invasion.active or mode.genesis_pit.active or mode.rand_mode.active or mode.annie_mode.active or mode.rook_mode.active or mode.lunk_mode.active}:
  mode_spinner_level_3_started.1{mode.rand_mode.active or mode.annie_mode.active or mode.rook_mode.active or mode.lunk_mode.active}:
    - disable_spinner_level_3
  mode_spinner_level_3_started.2:
    logicblock_spinner_level_3_hit_counter_hit:
      count:
        value: device.counters.spinner_level_3_hit_counter.value
  # mode_end_invid_invasion_stopped:
  #   logicblock_spinner_level_3_hit_counter_hit:
  #     count:
  #       value: device.counters.spinner_level_3_hit_counter.value
  # mode_rand_mode_stopped:
  #   logicblock_spinner_level_3_hit_counter_hit:
  #     count:
  #       value: device.counters.spinner_level_3_hit_counter.value
  # mode_annie_mode_stopped:
  #   logicblock_spinner_level_3_hit_counter_hit:
  #     count:
  #       value: device.counters.spinner_level_3_hit_counter.value
  # mode_rook_mode_stopped:
  #   logicblock_spinner_level_3_hit_counter_hit:
  #     count:
  #       value: device.counters.spinner_level_3_hit_counter.value

counters:
  spinner_level_3_hit_counter:
    count_events: spinner_shot_hit
    starting_count: current_player.spinner_initial_count
    direction: down
    count_complete_value: 0
    reset_on_complete: true
    events_when_complete: spinner_super
    disable_on_complete: false
    enable_events:
      - mode_spinner_level_3_starting
      - enable_spinner_level_3
      - mode_rand_mode_stopped
      - mode_annie_mode_stopped
      - mode_rook_mode_stopped
      - mode_lunk_mode_stopped
      - mode_corg_mode_stopped
      # - mode_end_invid_invasion_stopped
      # - mode_genesis_pit_stopped
      # - mode_the_fortress_stopped
    disable_events:
      - disable_spinner_level_3
      - mode_intro_rand_mode_started
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_intro_corg_mode_started
      # - mode_intro_invid_invasion_started
      # - mode_intro_genesis_pit_started
      # - mode_intro_the_fortress_started
    # reset_events:
    #   - mode_end_invid_invasion_stopped
    persist_state: false

widgets:
  # spinner_level_3_widget:
  #   - type: text
  #     text: SPINNER Level 3
  #     color: red
  #     font_size: 80
  #     x: center
  #     y: center + 50
    # - type: text
    #   text: "Score: 1500"
    #   color: red
    #   font_size: 80
    #   x: center
    #   y: center - 50
  spinner_level_3_count_widget:
    - type: text
      text: "SPINNER: L3 - (count)"
      color: red
      font_size: 35
      x: center + 450
      y: center - 230
    - type: text
      text: "Value: 1500"
      color: red
      font_size: 30
      x: center + 450
      y: center - 260

widget_player:
  # mode_spinner_level_3_started:
  #   spinner_level_3_widget:
  #     action: add
  #     widget_settings:
  #       expire: 3s
  #       #z: 110
  logicblock_spinner_level_3_hit_counter_hit:
    spinner_level_3_count_widget:
      action: update
      slide: base_slide
  # mode_intro_invid_invasion_started:
  #   spinner_level_3_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_intro_rand_mode_started:
  #   spinner_level_3_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_annie_mode_started:
  #   spinner_level_3_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_intro_rook_mode_started:
  #   spinner_level_3_count_widget:
  #     action: remove
  #     slide: base_slide
  # mode_lunk_mode_started:
  #   spinner_level_3_count_widget:
  #     action: remove
  #     slide: base_slide

variable_player:
  spinner_shot_hit:
    score: 1500 * current_player.pf_multiplier
  mode_spinner_level_3_started:
    spinner_time_value:
      int: 3
      action: set

show_player:
  spinner_shot_hit:
    flash_spinner_red:
      loops: 0
      show_tokens:
        leds: l_spinner_flasher

sound_player:
  # mode_spinner_level_3_started:
  #   spinner_level_3:
  #     action: play
  #     priority: 9999
  spinner_shot_hit:
    spinner_sound3:
      action: play
