#config_version=5

mode:
   start_events:
     - qualify_invid_invasion
     #- start_qualify_invid_invasion_ball_save
   stop_events:
     - ball_save_qualify_invid_invasion_ball_save_disabled
     - ball_ending
   priority: 750

# event_player:
#   mode_ball_save_qualify_invid_invasion_started:
#     kickback_disable{mode.kickback.active}
#   ball_save_start_qualify_ii_ball_save_disabled:
#     kickback_enable{mode.kickback.active} #|.5s

ball_saves:
  qualify_invid_invasion_ball_save:
    active_time: 4s
    #grace_period: 1s
    # enable_events:
    #   - mode_ball_save_qualify_invid_invasion_started{not mode.ball_save.active}
    #   - mode_ball_save_stopped
    timer_start_events:
      - mode_ball_save_qualify_invid_invasion_started
      #- mode_ball_save_stopped
    early_ball_save_events:
      - s_right_outlane_h_active
      - s_kickback_t_active{not mode.kickback.active}
    disable_events: stop_ball_save_invid_invasion
    auto_launch: yes
    balls_to_save: 1
    debug: yes

show_player:
  ball_save_qualify_invid_invasion_ball_save_timer_start:
    fast_flash_show:
      key: qualify_invid_invasion_ball_save_flash
      action: play
      speed: 20
      show_tokens:
        leds: l_shoot_again
        color: red
  ball_save_start_qualify_invid_invasion_ball_save_disabled:
    qualify_invid_invasion_ball_save_flash:
      action: stop
