#config_version=5

mode_settings:
  display_delay_ms: 2s
  hurry_up_delay_ms: 0
  hurry_up_event: flipper_cancel
  keep_multiplier: false
  bonus_entries:
    - event: bonus_lanes_display
      score: current_player.bonus_lanes * 20000
      player_score_entry: bonus_lanes
      reset_player_score_entry: false
      skip_if_zero: True
    - event: bonus_modes_display
      score: current_player.modes_started * 20000
      player_score_entry: modes_started
      reset_player_score_entry: false
      skip_if_zero: True
    - event: three_skillshots_made_display
      score: 50000
      player_score_entry: skill_shots_bonus
      reset_player_score_entry: true
      skip_if_zero: True

slide_player:
  mode_bonus_started: bonus_start_slide
  bonus_modes_display: modes_started_slide
  bonus_lanes_display: bonus_lanes_slide
  three_skillshots_made_display: bonus_skillshot_slide
  bonus_multiplier: bonus_multiplier_slide
  bonus_total:
    bonus_total:
    - type: text
      text: "TOTAL BONUS"
      font_size: 100
    - type: text
      text: (score)
      number_grouping: true
      color: red
      font_size: 100
      z: 110
      y: center-120

slides:
  bonus_start_slide:
    widgets:
      - type: text
        text: "END OF BALL BONUS"
        font_size: 100
        color: white
  modes_started_slide:
    widgets:
      - type: text
        text: "Modes Started Bonus"
        font_size: 100
        color: white
      - type: text
        text: "(player|modes_started) x 20,000 = (score)"
        font_size: 100
        color: red
        z: 110
        y: center-120
  bonus_lanes_slide:
    widgets:
      - type: text
        text: "Robotech Lanes Bonus"
        font_size: 100
        color: white
      - type: text
        text: "(player|bonus_lanes) x 30,000 = (score)"
        font_size: 100
        color: red
        z: 110
        y: center-120
  bonus_skillshot_slide:
    widgets:
      - type: text
        text: "3 Skill Shot Bonus"
        font_size: 100
        color: white
      - type: text
        text: (score)
        font_size: 100
        color: red
        z: 110
        y: center-120
  bonus_multiplier_slide:
    widgets:
      - type: text
        text: "Multiplier"
        font_size: 100
        color: white
      - type: text
        text: "(player|bonus_multiplier)X"
        font_size: 100
        color: red
        z: 110
        y: center-120
