#config_version=5

mode:
   start_events: start_invid_invasion
   stop_events:
     - tilt
     - mode_end_invid_invasion_started
   priority: 900

event_player:
  multiball_invid_invasion_quick_2_ball_started:
    - drop_reset_up
  drop_target_left_drop_down:
    - drop_reset_up|1s
  drop_target_middle_drop_down:
    - drop_reset_up|1s
  drop_target_right_drop_down:
    - drop_reset_up|1s
  mode_invid_invasion_started:
    - orbit_gate_enable
    - ramp_up_active{device.switches.s_up_down_ramp_switch.state == 1}|1s
  mode_invid_invasion_stopping:
    - orbit_gate_disable
  # ball_save_fake_invid_invasion_ball_save_saving_ball:
  #   - start_end_invid_invasion_mode
  timer_check_ramp_timer_complete{device.switches.s_up_down_ramp_switch.state == 0}:
    - ramp_up_active
    - ramp_down_active|1s
  invid_invasion_triple_jackpot_shot_flashing_hit:
    - ramp_diverter_disable
  invid_invasion_super_jackpot_shot_flashing_hit:
    - start_end_invid_invasion_mode|1s
  ball_save_fake_invid_invasion_ball_save_saving_ball:
    - start_end_invid_invasion_mode
  timer_invid_invasion_complete:
    - start_end_invid_invasion_mode

# slides:
#   ball_added_slide:
#     widgets:
#       - type: text
#         text: BALL ADDED!!
#         color: red
#         font_size: 130
#         y: center+50


# slide_player:
#   add_ball:
#     ball_added_slide:
#       expire: 2s
#       priority: 375


widget_player:
  timer_invid_invasion_started:
    ii_time_display_widget:
      action: add
      slide: base_slide
      priority: 901
    # ii_timer_widget:
    #   action: add
    #   slide: base_slide
    #   priority: 902
    ii_invid_display_widget:
      action: add
      slide: base_slide
      priority: 903
    ii_invid_count_widget:
      action: update
      slide: base_slide
      priority: 904
  timer_invid_invasion_tick:
    ii_timer_widget:
      action: update
      slide: base_slide
      priority: 905
  sw_invid_active:
    ii_invid_count_widget:
      action: update
      slide: base_slide
      priority: 906
  invid_invasion_jackpot_shot_flashing_hit:
    jackpot_invid_invasion_widget:
      widget_settings:
        expire: 2s
  invid_invasion_double_jackpot_shot_flashing_hit:
    double_jackpot_invid_invasion_widget:
      widget_settings:
        expire: 2s
  invid_invasion_triple_jackpot_shot_flashing_hit:
    triple_jackpot_invid_invasion_widget:
      widget_settings:
        expire: 2s
  invid_invasion_super_jackpot_shot_flashing_hit:
    super_jackpot_invid_invasion_widget:
      widget_settings:
        expire: 2s
  # add_10s:
  #   10s_added_widget:
  #     widget_settings:
  #       expire: 3s


widgets:
  ii_time_display_widget:
    - type: text
      text: TIMER
      color: blue
      font_size: 100
      y: center + 220
      x: center - 450
  ii_timer_widget:
    - type: text
      text: (ticks_remaining)
      color: red
      font_size: 100
      y: center + 150
      x: center - 450
  ii_invid_display_widget:
    - type: text
      text: "Invid"
      color: blue
      font_size: 100
      y: center + 220
      x: center + 450
  ii_invid_count_widget:
    - type: text
      text: (player|invid_invasion_total)
      color: green
      font_size: 100
      y: center + 150
      x: center + 450
  jackpot_invid_invasion_widget:
    - type: text
      text: JACKPOT!
      color: green
      font_size: 100
      y: center + 120 #150
    - type: text
      text: (jackpot_value)
      color: red
      font_size: 100
      y: center #-150
      number_grouping: true
  double_jackpot_invid_invasion_widget:
    - type: text
      text: DOUBLE JACKPOT!!
      color: yellow
      font_size: 100
      y: center + 120 #150
    - type: text
      text: (jackpot_value)
      color: red
      font_size: 100
      y: center #-150
      number_grouping: true
  triple_jackpot_invid_invasion_widget:
    - type: text
      text: TRIPLE JACKPOT!!
      color: red
      font_size: 100
      y: center + 120 #150
    - type: text
      text: (jackpot_value)
      color: red
      font_size: 100
      y: center #-150
      number_grouping: true
  super_jackpot_invid_invasion_widget:
    - type: text
      text: SUPER JACKPOT!!!
      color: purple
      font_size: 100
      y: center + 120 #150
    - type: text
      text: (jackpot_value)
      color: red
      font_size: 100
      y: center #-150
      number_grouping: true
  # 10s_added_widget:
  #   - type: text
  #     text: 10 seconds ADDED
  #     color: green
  #     font_size: 80
  #     y: center - 150
  #     x: center
  #     #z: 400


timers:
  invid_invasion:
    debug: true
    start_value: 60
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: multiball_invid_invasion_quick_2_ball_started #mode_multiball_show_ended #start_mission_1
      - action: add
        event: spinner_shot_hit
        value: current_player.spinner_time_value
      # - action: add
      #   event: add_5s
      #   value: 5
      - action: add
        event: s_back_ramp_active
        value: 2
      - action: pause
        event: mystery_shot_flashing_hit{game.balls_in_play==1}
        value: 5
  check_ramp_timer:
    debug: True
    start_value: 0
    end_value: 2
    direction: up
    tick_interval: 1s
    control_events:
      - action: start
        event: invid_invasion_success
  # add_a_ball_grace_period:
  #   start_value: 10
  #   end_value: 0
  #   direction: down
  #   tick_interval: 1s
  #   control_events:
  #     - action: start
  #       event: start_add_a_ball_grace_period

counters:
  disable_orbit_gate_counter:
    count_events: sw_invid_active
    starting_count: 0
    count_complete_value: 17
    events_when_complete: orbit_gate_disable
    disable_on_complete: true
  invid_hit_counter:
    count_events: sw_invid_active
    starting_count: 0
    count_complete_value: 20
    events_when_complete:
      - invid_invasion_success
      - ramp_down_active
      - ramp_diverter_enable
    reset_on_complete: false
    persist_state: true
    debug: true
  # add_more_time:
  #   count_events: sdf_bank_shots_lit_complete
  #   starting_count: 0
  #   count_complete_value: 2
  #   direction: up
  #   events_when_complete: add_10s
  #   disable_on_complete: true
  #   enable_events: timer_invid_invasion_started
  #   debug: true
    #disable_events: multiball_invid_invasion_quick_2_ball_ended

shot_profiles:
  invid_invasion_profile:
    show_when_disabled: false
    advance_on_hit: false
    states:
      - name: flashing
        show: flash_ii_red_show
        speed: 15
  invid_invasion_add_a_ball:
    advance_on_hit: true
    block: true
    states:
      - name: flashing
        show: flash_blue_show
        speed: 4
        sync_ms: 1000
        loops: -1
      - name: hit
        show: color_blue_on
  invid_invasion_jackpot:
    advance_on_hit: true
    block: true
    states:
      - name: flashing
        show: invid_invasion_jackpot_flash_show
        loops: -1
        speed: 5
      - name: hit
        show: off


shot_groups:
  invid_invasion_add_a_ball_group:
    shots:
      - invid_invasion_s_target_shot
      - invid_invasion_d_target_shot
      - invid_invasion_f_target_shot
    disable_events:
      - invid_invasion_add_a_ball_group_hit_complete


shots:
  invid_invasion_s_target_shot:
    switch: s_s_target
    profile: invid_invasion_add_a_ball
    show_tokens:
      leds: l_s_led
  invid_invasion_d_target_shot:
    switch: s_d_target
    profile: invid_invasion_add_a_ball
    show_tokens:
      leds: l_d_led
  invid_invasion_f_target_shot:
    switch: s_f_target
    profile: invid_invasion_add_a_ball
    show_tokens:
      leds: l_f_led
  invid_invasion_left_target:
    switch: s_left_target
    profile: invid_invasion_profile
    show_tokens:
      leds: l_t1
  invid_invasion_middle_target:
    switch: s_middle_target
    profile: invid_invasion_profile
    show_tokens:
      leds: l_t2
  invid_invasion_right_target:
    switch: s_right_target
    profile: invid_invasion_profile
    show_tokens:
      leds: l_t3
  invid_invasion_left_drop:
    switch: s_left_drop_target
    profile: invid_invasion_profile
    show_tokens:
      leds: l_t4
  invid_invasion_middle_drop:
    switch: s_middle_drop_target
    profile: invid_invasion_profile
    show_tokens:
      leds: l_t5
  invid_invasion_right_drop:
    switch: s_right_drop_target
    profile: invid_invasion_profile
    show_tokens:
      leds: l_t6
  invid_invasion_jackpot_shot:
    hit_events: ramp_wireform_sequence_hit
    profile: invid_invasion_jackpot
    show_tokens:
      color: green
    enable_events:
      - invid_invasion_success
    disable_events:
      - invid_invasion_jackpot_shot_flashing_hit
  invid_invasion_double_jackpot_shot:
    hit_events: ramp_wireform_sequence_hit
    profile: invid_invasion_jackpot
    show_tokens:
      color: yellow
    enable_events:
      - invid_invasion_jackpot_shot_flashing_hit
    disable_events:
      - invid_invasion_double_jackpot_shot_flashing_hit
  invid_invasion_triple_jackpot_shot:
    hit_events: ramp_wireform_sequence_hit
    profile: invid_invasion_jackpot
    show_tokens:
      color: red
    enable_events:
      - invid_invasion_double_jackpot_shot_flashing_hit
    disable_events:
      - invid_invasion_triple_jackpot_shot_flashing_hit
  invid_invasion_super_jackpot_shot:
    hit_events: ramp_reflex_point_sequence_hit
    profile: invid_invasion_jackpot
    show_tokens:
      color: purple
    enable_events:
      - invid_invasion_triple_jackpot_shot_flashing_hit

variable_player:
  mode_invid_invasion_started:
    invid_invasion_start_mode_score:
      int: current_player.score
      action: set
  invid_invasion_jackpot_shot_flashing_hit:
    jackpot_value:
      int: (current_player.invid_invasion_total * 1000) * current_player.ramp_shot_multiplier #(current_player.invid_invasion_total * 1000)  * game.balls_in_play
      action: set
    score: (current_player.invid_invasion_total * 1000) * current_player.ramp_shot_multiplier  #(current_player.invid_invasion_total * 1000) * game.balls_in_play
  invid_invasion_double_jackpot_shot_flashing_hit:
    jackpot_value:
      int: ((current_player.invid_invasion_total * 1000) * 2) * current_player.ramp_shot_multiplier #((current_player.invid_invasion_total * 1000) * game.balls_in_play) * 2
      action: set
    score: ((current_player.invid_invasion_total * 1000) * 2) * current_player.ramp_shot_multiplier #((current_player.invid_invasion_total * 1000) * game.balls_in_play) * 2
  invid_invasion_triple_jackpot_shot_flashing_hit:
    jackpot_value:
      int: ((current_player.invid_invasion_total * 1000) * 3) * current_player.ramp_shot_multiplier #((current_player.invid_invasion_total * 1000) * game.balls_in_play) * 3
      action: set
    score: ((current_player.invid_invasion_total * 1000) * 3) * current_player.ramp_shot_multiplier #((current_player.invid_invasion_total * 1000) * game.balls_in_play) * 3
  invid_invasion_super_jackpot_shot_flashing_hit:
    jackpot_value:
      int: ((current_player.invid_invasion_total * 1000) * 4) * current_player.ramp_shot_multiplier #((current_player.invid_invasion_total * 1000) * game.balls_in_play) * 4
      action: set
    score: ((current_player.invid_invasion_total * 1000) * 4) * current_player.ramp_shot_multiplier #((current_player.invid_invasion_total * 1000) * game.balls_in_play) * 4
    mode_end_action_flag:
      int: 2
      action: set
  sw_invid_active:
    invid_invasion_total: 1
    score: 1000
  timer_invid_invasion_complete:
    mode_end_action_flag:
      int: 1
      action: set

sound_player:
  invid_invasion_success:
    that_takes_care_of_them:
      action: play
  mode_invid_invasion_stopping:
    that_takes_care_of_them:
      action: stop
  invid_invasion_jackpot_shot_flashing_hit:
    jackpot:
      action: play
      priority: 1000
  invid_invasion_double_jackpot_shot_flashing_hit:
    double_jackpot:
      action: play
      priority: 1000
  invid_invasion_triple_jackpot_shot_flashing_hit:
    triple_jackpot:
      action: play
      priority: 1000
  invid_invasion_super_jackpot_shot_flashing_hit:
    super_jackpot:
      action: play
      priority: 1000
  invid_invasion_add_a_ball_group_hit: sdf_target_sound


ball_saves:
  fake_invid_invasion_ball_save:
    enable_events:
      - multiball_invid_invasion_quick_2_ball_ended
    disable_events: invid_invasion_add_ball #added to test
    auto_launch: no
    balls_to_save: 1
    debug: yes
