#config_version=5
#Robotech

mode:
    start_events:
      # - achievement_invid_invasion_mission_1_state_started
      - add_ball
    stop_events:
      - ball_save_invid_invasion_add_a_ball_disabled
      - multiball_invid_invasion_quick_2_ball_ended
      - mode_end_invid_invasion_started
    priority: 9000

event_player:
  mode_ball_save_invid_invasion_add_a_ball_started:
    - play_add_a_ball_sound|1s

ball_saves:
  invid_invasion_add_a_ball:
    active_time: 10s
    hurry_up_time: 5s
    grace_period: 2s
    enable_events: mode_ball_save_invid_invasion_add_a_ball_started #add_ball
    #disable_events: multiball_invid_invasion_quick_2_ball_ended
    timer_start_events:
      - mode_ball_save_invid_invasion_add_a_ball_started{not mode.ball_save_invid_invasion.active} # add_ball{not mode.ball_save_invid_invasion.active}
      - mode_ball_save_invid_invasion_stopped
    auto_launch: true
    balls_to_save: -1
    debug: true

show_player:
  ball_save_invid_invasion_add_a_ball_timer_start:
    fast_flash_show:
      key: invid_invasion_add_a_ball_save_flash
      speed: 3
      show_tokens:
        leds: l_shoot_again
        color: purple
      action: play
  ball_save_invid_invasion_add_a_ball_hurry_up:
    invid_invasion_add_a_ball_save_flash:
      action: stop
    fast_flash_show:
      key: invid_invasion_add_a_ball_hurry_up_flash
      action: play
      speed: 20
      show_tokens:
        leds: l_shoot_again
        color: purple
  ball_save_invid_invasion_add_a_ball_grace_period:
    invid_invasion_add_a_ball_hurry_up_flash:
      action: stop

widgets:
  add_a_ball_video:
    - type: video
      video: add_a_ball

widget_player:
  mode_ball_save_invid_invasion_add_a_ball_started:
    add_a_ball_video:
      action: update
      widget_settings:
        expire: 2.5s
        z: 110

sound_player:
  play_add_a_ball_sound:
    launch_next_wave:
      action: play
