#config_version=5

mode:
  start_events:
    - mode_invid_invasion_started
  stop_events:
    #- invid_invasion_add_ball #connented out 5.17
    #- timer_add_a_ball_grace_period_stopped
    #- ball_will_end
    #- mode_invid_invasion_stopping #connented out 5.17
    - mode_end_invid_invasion_started
  #stop_on_ball_end: false #true
  priority: 1000

# event_player:
  # invid_invasion_add_ball:
  #   - right_flipper_normal_enable
  #   - left_flipper_normal_enable
#   multiball_invid_invasion_quick_2_ball_ended:
#     - start_add_a_ball_grace_period

multiballs:
  invid_invasion_quick_2_ball:
    ball_count: 3
    ball_count_type: total
    start_or_add_a_ball_events:
      - mode_multiball_invid_invasion_started
      - invid_invasion_add_ball
    ball_locks: bd_right_lock
    shoot_again: 0
    #disable_events: mode_end_invid_invasion_starting #connented out 6.19
    stop_events: start_end_invid_invasion_mode
    #add_a_ball_events: add_ball
    debug: true

# timers:
#   add_a_ball_grace_period:
#     start_value: 0
#     #end_value: 0
#     #direction: down
#
#     tick_interval: 1s
#     control_events:
#       - action: start
#         event: start_add_a_ball_grace_period
#       - action: stop
#         event: add_ball #multiball_invid_invasion_quick_2_ball_started

counters:
  add_a_ball_counter:
    count_events: invid_invasion_add_a_ball_group_hit_complete #sdf_bank_shots_lit_complete
    starting_count: 0
    count_complete_value: 1
    events_when_complete:
      - invid_invasion_add_ball
      #- add_5s
    enable_events: multiball_invid_invasion_quick_2_ball_started
    disable_on_complete: true
    debug: true
    #disable_events: multiball_invid_invasion_quick_2_ball_ended
