#config_version=5
# Robotech Pinball Machine

hardware:
  platform: fast
  driverboards: fast
  #platform: smart_virtual

mpf:
#  default_led_hw_update_hz: 30
  default_pulse_ms: 10

fast:
  #ports: /dev/ttyUSB1, /dev/ttyUSB2  #for RPi3
  ports: com6, com7
  #debug: true
  #config_number_format: int
#  rgb_buffer: 100

config:
  - leds.yaml
  - lightscripts.yaml
  - audio.yaml
  - switches.yaml
  - keyboard.yaml
  - display.yaml
  #- machine_config.yaml

logging:
  file:
    event_manager: basic
    show_controller: full

modes:
  - attract                             #priority: 10
  # - game                              #priority: 20
  - base                                #priority: 100
  - lanes                               #priority: 150 -> 200
  - sdf_targets                         #priority: 200 -> 300
  - pre_qualify_invid_invasion          #priority: 225 -> 400
  - bonus                               #priority: 500
  - high_score                          #priority: 600
  - qualify_invid_invasion              #priority: 250 -> 700
  - intro_invid_invasion                #priority: 300 -> 800
  - invid_invasion                      #priority: 350 -> 900
  - multiball_invid_invasion            #priority: 375 -> 1000
  - end_invid_invasion                  #priority: 385 -> 1100
  - qualify_rand                        #priority: 400 -> 1200
  - qualify_annie                       #priority: 425 -> 1300
  - qualify_rook                        #priority: 450 -> 1400
  - qualify_lancer                      #priority: 475 -> 1500
  - qualify_lunk                        #priority: 485 -> 1600
  - qualify_marlene                     #priority: 495 -> 1700
  - kickback                            #priority: 900 -> 1800
  - skill_shot                          #priority: 1000 -> 1900
  - skill_shot_combo                    #priority: 1025 -> 2000
  - intro_rand_mode                     #priority: 1050 -> 2100
  - rand_mode                           #priority: 1100 -> 2200
  - collect_mecha_rand_mode             #priority: 1200 -> 2300
  - pops_level_1                        #priority: 2400
  - pops_level_2                        #priority: 2500
  - pops_level_3                        #priority: 2600
  - super_pops                          #priority: 2700
  - annie_mode                          #priority: 3000
  - protoculture                        #priority: 4000
  - ball_save                           #priority: 8000
  - ball_save_invid_invasion            #priority: 8500
  - ball_save_invid_invasion_add_a_ball #priority: 9000
  - ball_save_rand_mode                 #priority: 9250
  - ball_save_annie_mode                #priority: 9350
  - ball_save_annie_mode_rook_add_a_ball #priority: 9450
  - tilt                                #priority: 10,000
  #- carousel
  #- super_spinner

playfields:
  playfield:
     tags: default
     default_source_device: bd_plunger
     enable_ball_search: True
     ball_search_timeout: 25s
     ball_search_wait_after_iteration: 12s
     ball_search_interval: 500ms
     debug: true

flippers:
  lower_left:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    label: Left Main Flipper
    enable_events: ball_started, flipper_on, normal_flippers_enable
    disable_events: ball_will_end, flipper_off, weak_flipper_2_ball_enable
  lower_right:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    label: Right Main Flipper
    enable_events: ball_started, flipper_on, normal_flippers_enable
    disable_events: ball_will_end, flipper_off, weak_flipper_2_ball_enable
  left_weak_2_ball:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    main_coil_overwrite:
      pulse_ms: 22
    activation_switch: s_left_flipper
    enable_events: weak_flipper_2_ball_enable
    disable_events: normal_flippers_enable, weak_flipper_1_ball_enable, flipper_off
  right_weak_2_ball:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    main_coil_overwrite:
      pulse_ms: 22
    activation_switch: s_right_flipper
    enable_events: weak_flipper_2_ball_enable
    disable_events: normal_flippers_enable, weak_flipper_1_ball_enable, flipper_off
  left_weak_1_ball:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    main_coil_overwrite:
      pulse_ms: 19
    activation_switch: s_left_flipper
    enable_events: weak_flipper_1_ball_enable
    disable_events: normal_flippers_enable, flipper_off
  right_weak_1_ball:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    main_coil_overwrite:
      pulse_ms: 19
    activation_switch: s_right_flipper
    enable_events: weak_flipper_1_ball_enable
    disable_events: normal_flippers_enable, flipper_off

player_vars:
  #multiplier:
  bonus_multiplier:
    value_type: int
    initial_value: 1
  #after 3x you get bonus for completing more robotech lanes
  bonus_lanes:
    value_type: int
    initial_value: 0
  #keep count of how many combos made
  combos_made:
    value_type: int
    initial_value: 0
  skill_shot_value:
    value_type: int
    initial_value: 0
  jackpot_value:
    value_type: int
    initial_value: 0
  super_jackpot_value:
    value_type: int
    initial_value: 0
  invid_invasion_total:
    value_type: int
    initial_value: 0
  pop_bumper_hits:
    value_type: int
    initial_value: 0
  modes_completed:
    value_type: int
    initial_value: 0
  skill_shots_bonus:
    value_type: int
    initial_value: 0
  team_members_collected:
    value_type: int
    initial_value: 0
  rand_start_count:
    value_type: int
    initial_value: 0
  annie_start_count:
    value_type: int
    initial_value: 0
  rook_start_count:
    value_type: int
    initial_value: 0
  lancer_start_count:
    value_type: int
    initial_value: 3
  lunk_start_count:
    value_type: int
    initial_value: 2
  marlene_start_count:
    value_type: int
    initial_value: 0

coils:
  #BEGIN 0804 (0 0-3)
  #free
  #BEGIN 3208 (1 0-7)
  c_top_lock_kickout:
    number: 1-1
    default_pulse_ms: 10
    default_pulse_power: .50
    label: FP-DN-04
    #debug: true
  c_flipper_left_main:
    number: 1-2
    default_pulse_ms: 27
    default_pulse_power: .90
    label: FP-DN-06
  c_flipper_left_hold:
    number: 1-3
    allow_enable: true
    label: FP-DN-07
  c_flipper_right_main:
    number: 1-4
    default_pulse_ms: 29
    default_pulse_power: .95
    label: FP-DN-08
  c_flipper_right_hold:
    number: 1-5
    allow_enable: true
    label: FP-DN-09
  c_auto_launch:
    number: 1-6
    default_pulse_ms: 16
    label: FP-DN-0A
  c_trough_eject:
    number: 1-7
    default_pulse_ms: 18
    label: FP-DN-0B
  #BEGIN 16-16 (2 0-15)
  c_kickback:
    number: 2-0
    default_pulse_ms: 5
    label: FP-DN-0C
    #debug: true
  c_left_slingshot:
    number: 2-1
    default_pulse_ms: 3 #4
    label: FP-DN-0D
  c_left_lock_kickout:
    number: 2-2
    default_pulse_ms: 10
    label: FP-DN-0E
  c_right_slingshot:
    number: 2-3
    default_pulse_ms: 3 #4
    platform_settings:
      recycle_ms: 30
    label: FP-DN-0F
  c_middle_drop_target:
    number: 2-4
    default_pulse_ms: 10
    label: FP-DN-10
  c_left_drop_target:
    number: 2-5
    default_pulse_ms: 10
    label: FP-DN-11
  c_right_drop_target:
    number: 2-6
    default_pulse_ms: 10 #15
    label: FP-DN-12
  c_right_lock_kickout:
    number: 2-7
    default_pulse_ms: 30
    default_pulse_power: .90
    label: FP-DN-13
  c_bottom_l_pop_bumper:
    number: 2-8
    default_pulse_ms: 6
    label: FP-DN-14
  c_top_l_pop_bumper:
    number: 2-9
    default_pulse_ms: 6
    label: FP-DN-15
  c_bottom_r_pop_bumper:
    number: 2-10
    default_pulse_ms: 6
    label: FP-DN-16
  c_top_r_pop_bumper:
    number: 2-11
    default_pulse_ms: 6
    label: FP-DN-17
  c_ramp_diverter:
    number: 2-12
    default_pulse_ms: 15
    allow_enable: true
    label: FP-DN-18
  c_ramp_up:
    number: 2-13
    default_pulse_ms: 20
    label: FP-DN-19
  c_ramp_down:
    number: 2-14
    default_pulse_ms: 35
    label: FP-DN-1A
  c_orbit_gate:
    number: 2-15
    default_pulse_ms: 15
    allow_enable: true
    label: FP-DN-1B

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4
    jam_switch: s_trough_jam
    entrance_count_delay: 1s #1.5s
    eject_coil: c_trough_eject
    tags: trough, home, drain
    #confirm_eject_type: target
    debug: true
    eject_targets: bd_plunger
    eject_timeouts: 1500ms #2.5s
    eject_coil_retry_pulse: 8ms
    label: Main Trough
    auto_fire_on_unexpected_ball: False
  bd_plunger:
    ball_switches: s_plunger_lane
    entrance_count_delay: 0 #1s
    eject_timeouts: 4s
    #tags: ball_add_live
    mechanical_eject: true
    eject_coil: c_auto_launch
    #exit_count_delay: 1s #0.5s
    ball_missing_timeouts: 10s
    #auto_fire_on_unexpected_ball: true
    label: Plunger Lane
    confirm_eject_type: target
    player_controlled_eject_event: force_plunger_launch
    debug: true
  bd_left_lock:
    label: left lock
    ball_switches: s_left_lock_kickout
    eject_coil: c_left_lock_kickout
    #exit_count_delay: 250ms
    tags: left_lock
    eject_timeouts: 500ms
    eject_all_events: game_ended
    #debug: true
  bd_right_lock:
    label: right lock
    ball_switches: s_right_lock_kickout
    eject_coil: c_right_lock_kickout
    exit_count_delay: 250ms
    tags: right_lock
    eject_timeouts: 500ms
    eject_all_events: game_ended
  bd_top_lock:
    label: top lock
    ball_switches: s_top_lock_kickout
    eject_coil: c_top_lock_kickout
    exit_count_delay: 250ms
    tags: top_lock
    eject_timeouts: 500ms
    eject_all_events: game_ended

game:
  balls_per_game: 3
  max_players: 2

machine:
  balls_installed: 4
  min_balls: 3

widget_styles:
  text_default:
    font_name: robotech
    font_size: 20
  score_style_singleplayer:
    number_grouping: true
    min_digits: 2
    font_size: 80
    font_name: robotech
  score_style_multiplayer:
    number_grouping: true
    min_digits: 2
    font_size: 40
    font_name: robotech

autofire_coils:
  left_slingshot:
    switch: s_left_slingshot
    coil: c_left_slingshot
    disable_events: ball_ending, service_mode_entered, disable_sling
    enable_events: ball_started, enable_sling
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
    disable_events: ball_ending, service_mode_entered, disable_sling
    enable_events: ball_started, enable_sling
  bottom_l_pop_bumper:
    coil: c_bottom_l_pop_bumper
    switch: s_bottom_l_pop_bumper
    disable_events: ball_ending, service_mode_entered, disable_pop_bumper
    enable_events: ball_started, enable_pop_bumper
  bottom_r_pop_bumper:
    coil: c_bottom_r_pop_bumper
    switch: s_bottom_r_pop_bumper
    disable_events: ball_ending, service_mode_entered, disable_pop_bumper
    enable_events: ball_started, enable_pop_bumper
  top_l_pop_bumper:
    coil: c_top_l_pop_bumper
    switch: s_top_l_pop_bumper
    disable_events: ball_ending, service_mode_entered, disable_pop_bumper
    enable_events: ball_started, enable_pop_bumper
  top_r_pop_bumper:
    coil: c_top_r_pop_bumper
    switch: s_top_r_pop_bumper
    disable_events: ball_ending, service_mode_entered, disable_pop_bumper
    enable_events: ball_started, enable_pop_bumper

kickbacks:
  kickback_main:
    coil: c_kickback
    switch: s_kickback_t
    enable_events: kickback_enable
    disable_events: kickback_disable #, ball_starting # {not mode.kickback.active}, disable_kickback
    debug: true

drop_targets:
   left_drop:
     switch: s_left_drop_target
     reset_coil: c_left_drop_target
     reset_events: drop_reset_up, ball_starting
     # enable_keep_up_events: ball_starting
     # disable_keep_up_events: s_plunger_lane_inactive
     debug: true
   middle_drop:
     switch: s_middle_drop_target
     reset_coil: c_middle_drop_target
     reset_events: drop_reset_up, ball_starting
     # enable_keep_up_events: ball_starting
     # disable_keep_up_events: s_plunger_lane_inactive
     debug: true
   right_drop:
     switch: s_right_drop_target
     reset_coil: c_right_drop_target
     reset_events: drop_reset_up, ball_starting
     # enable_keep_up_events: ball_starting
     # disable_keep_up_events: s_plunger_lane_inactive
     debug: True

# drop_target_banks:
#   bank:
#     debug: True
#     drop_targets: left_drop, middle_drop, right_drop
#     reset_events:
#          #ball_starting: 0.5s
#          invid_target_group_complete: 2s
#          drop_target_bank_bank_down: 1s

diverters:
  orbit_gate:
    activation_coil: c_orbit_gate
    type: hold
    activation_time: 2s
    activation_switches: s_gate_top_right
    deactivation_switches: s_left_orbit
    enable_events: orbit_gate_enable
    disable_events: orbit_gate_disable
    debug: True
  ramp_down:
    activation_coil: c_ramp_down
    activate_events: ramp_down_active #mode_skill_shot_starting
    type: pulse
    enable_events: ball_started
  #   enable_events: ramp_down_enable #mode_skill_shot_starting #ball_starting
  #   # disable_events: ramp_down_disable #mode_skill_shot_stopping
    debug: True
  ramp_up:
    activation_coil: c_ramp_up
    # #activation_switches: s_right_orbit_rollover # (look into this)
    activate_events: ramp_up_active
    type: pulse
    #enable_events: mode_skill_shot_starting #mode_skill_shot_starting
    #disable_events: mode_skill_shot_stopping
    debug: True
  ramp_diverter:
    activation_coil: c_ramp_diverter
    type: hold
    activation_time: 1s
    activation_switches: s_back_ramp
    enable_events: ramp_diverter_enable #ball_started
    disable_events: ramp_diverter_disable
    debug: true
  # ramp:
  #   activation_coil: c_ramp_down
  #   deactivation_coil: c_ramp_up
  #   type: pulse
  #   activate_events: ramp_down_active
  #   deactivate_events: ramp_up_active
  #   debug: True
