#config_version=4
# Robotech Pinball Machine

hardware:
  platform: fast
  driverboards: fast

mpf:
  default_led_hw_update_hz: 30

fast:
  ports: /dev/ttyUSB1, /dev/ttyUSB2
  config_number_format: int
  rgb_buffer: 100

config:
- leds.yaml
- shots.yaml
- lightscripts.yaml

modes:
- base
- kickback
- attract
- ball_save

window:
  width: 1280
  height: 800
  title: Robotech
  resizable: false
  fullscreen: auto
  borderless: false
  exit_on_escape: true

kivy_config:
  graphics:
        fbo: force-hardware


switches:
  s_right_flipper:
    number: 0
    tags: right_flipper
  s_left_flipper:
    number: 1
    tags: left_flipper  
  s_start:
    number: 2
    tags: start
  s_tilt:
    number: 3
  s_left_target:
    number: 10
    tags: playfield_active
  s_middle_target:
    number: 11
    tags: playfield_active
  s_right_target:
    number: 12
    tags: playfield_active
  s_left_top_rubber:
    number: 13
    tags: playfield_active
  s_left_middle_rubber:
    number: 14
    tags: playfield_active
  s_left_bottom_rubber:
    number: 15
    tags: playfield_active
  s_left_top_rubber:
    number: 18
    tags: playfield_active
  s_r_top_lane:
    number: 19
    tags: playfield_active
  s_o1_top_lane:
    number: 20
    tags: playfield_active
  s_top_target:
    number: 21
    tags: playfield_active
  s_b_top_lane:
    number: 22
    tags: playfield_active
  s_o2_top_lane:
    number: 23
    tags: playfield_active
  s_right_top1_rubber:
    number: 24
    tags: playfield_active
  s_right_top2_rubber:
    number: 25
    tags: playfield_active
  s_right_rollover:
    number: 26
    tags: playfield_active
  s_middle_right_rubber:
    number: 27
    tags: playfield_active
  s_s_target:
    number: 28
    tags: playfield_active, sdf
  s_d_target:
    number: 29
    tags: playfield_active, sdf
  s_f_target:
    number: 30
    tags: playfield_active, sdf
  s_lower_right_rubber:
    number: 31
    tags: playfield_active
  s_drain_kicker:
    number: 32
    tags: start
  s_trough3:
    number: 33
  s_trough2:
    number: 34
  s_trough1:
    number: 36
  s_plunger_lane:
    number: 37
  s_right_inlane_c:
    number: 38
    tags: playfield_active
  s_right_outlane_h:
    number: 39
    tags: playfield_active
  s_kickback_t:
    number: 40
    tags: kickback, playfield_active
  s_left_slingshot:
    number: 41
    tags: playfield_active
  s_left_inlane_e:
    number: 42
    tags: playfield_active
  s_left_rollover:
    number: 43
    tags: playfield_active
  s_left_lock_kickout:
    number: 44
    tags: playfield_active
  s_right_drop_target:
    number: 45
    tags: playfield_active
  s_middle_drop_target:
    number: 46
    tags: playfield_active
  s_left_drop_target:
    number: 47
    tags: playfield_active
  s_bottom_l_pop_bumper:
    number: 48
    tags: playfield_active
  s_top_l_pop_bumper:
    number: 49
    tags: playfield_active
  s_bottom_r_pop_bumper:
    number: 50
    tags: playfield_active
  s_top_r_pop_bumper:
    number: 51
    tags: playfield_active
  s_spinner:
    number: 52
    tags: playfield_active
  s_top_lock_kickout:
    number: 53
    tags: playfield_active
  s_right_lock_kickout:
    number: 54
    tags: playfield_active
  s_right_slingshot:
    number: 55
    tags: playfield_active

flippers:
  lower_left:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    label: Left Main Flipper
  lower_right:
    main_coil: c_flipper_right_main
    activation_switch: s_right_flipper
    label: Right Main Flipper

coils:
  c_flipper_left_main:
    number: 8
    pulse_ms: 12
    hold_power: 1
  c_flipper_right_main:
    number: 9
    pulse_ms: 12
    hold_power: 1
  c_trough_eject:
    number: 10
    pulse_ms: 70
  c_drain_kicker:
    number: 11
    pulse_ms: 20
  c_kickback:
    number: 12
    pulse_ms: 20
  c_left_slingshot:
    number: 13
    pulse_ms: 9
  c_left_lock_kickout:
    number: 14
    pulse_ms: 20
  c_right_slingshot:
    number: 15
    pulse_ms: 9
  c_middle_drop_target:
    number: 16
    pulse_ms: 20
  c_left_drop_target:
    number: 17
    pulse_ms: 20
  c_right_drop_target:
    number: 18
    pulse_ms: 20
  c_right_lock_kickout:
    number: 19
    pulse_ms: 20
  c_bottom_l_pop_bumper:
    number: 20
    pulse_ms: 30
  c_top_l_pop_bumper:
    number: 21
    pulse_ms: 30
  c_bottom_r_pop_bumper:
    number: 22
    pulse_ms: 30
  c_top_r_pop_bumper:
    number: 23
    pulse_ms: 30
  c_top_lock_kickout:
    number: 24
    pulse_ms: 20
  c_top_gate:
    number: 25
    pulse_ms: 20

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3
    entrance_count_delay: 300ms
    eject_coil: c_trough_eject
    tags: trough, home, drain
    debug: yes
    eject_targets: bd_plunger
  bd_plunger:
    ball_switches: s_plunger_lane
    #entrance_count_delay: 300ms
    eject_timeouts: 3s
    tags: ball_add_live
    mechanical_eject: true
  drain:
    ball_switches: s_drain_kicker
    eject_coil: c_drain_kicker
    entrance_count_delay: 100ms
    confirm_eject_type: target
    eject_targets: bd_trough
    tags: drain
  bd_left_lock:
    label: left lock
    ball_switches: s_left_lock_kickout
    eject_coil: c_left_lock_kickout
    exit_count_delay: 250ms
    tags: left_lock
    eject_timeouts: 500ms
  bd_right_lock:
    label: right lock
    ball_switches: s_right_lock_kickout
    eject_coil: c_right_lock_kickout
    exit_count_delay: 250ms
    tags: right_lock
    eject_timeouts: 500ms
  bd_top_lock:
    label: top lock
    ball_switches: s_top_lock_kickout
    eject_coil: c_top_lock_kickout
    exit_count_delay: 250ms
    tags: top_lock
    eject_timeouts: 500ms

game:
  balls_per_game: 3
  max_players: 1

machine:
  balls_installed: 3
  min_balls: 1

widget_styles:
  default:
    font_name: Quadrit
    font_size: 10
    adjust_top: 2
    adjust_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    adjust_top: 3
    adjust_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    adjust_top: 2
    adjust_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    adjust_top: 1
    adjust_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    adjust_top: 2
    adjust_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  bottom_l_pop_bumper:
    coil: c_bottom_l_pop_bumper
    switch: s_bottom_l_pop_bumper
  bottom_r_pop_bumper:
    coil: c_bottom_r_pop_bumper
    switch: s_bottom_r_pop_bumper
  top_l_pop_bumper:
    coil: c_top_l_pop_bumper
    switch: s_top_l_pop_bumper
  top_r_pop_bumper:
    coil: c_top_r_pop_bumper
    switch: s_top_r_pop_bumper
  kickback:
    coil: c_kickback
    switch: s_kickback_t
    enable_events: mode_kickback_started
    disable_events: mode_kickback_stopped

drop_targets:
   left_drop:
     debug: True
     switch: s_left_drop_target
     reset_coil: c_left_drop_target
   middle_drop:
     debug: True
     switch: s_middle_drop_target
     reset_coil: c_middle_drop_target
   right_drop:
     debug: True
     switch: s_right_drop_target
     reset_coil: c_right_drop_target

drop_target_banks:
  bank:
    debug: True
    drop_targets: left_drop, middle_drop, right_drop
    reset_events:
         ball_starting: 0.5s
         invid_target_group_complete: 2s
#        drop_target_bank_bank_down: 1s

#ball_saves:
#  default:
#    active_time: 5s
#    hurry_up_time: 2s
#    grace_period: 3s
#    enable_events: mode_base_started
#    timer_start_events: #       
#    balldevice_bd_plunger_ball_eject_success
#    auto_launch: false
#    balls_to_save: 1
#    debug: true
#
#show_player:
#  ball_save_default_enabled:
#   ball_save_flash:
#    loops: -1
#  ball_save_default_disabled:
#    ball_save_flash:
#      action: stop  
