#config_version=5
# Robotech Pinball Machine

# kivy_config:
#   kivy:
#     desktop: 1
#     exit_on_escape: true
#   graphics:
#     borderless: false
#     fbo: hardware
#     fullscreen: false
#     multisamples: 2
#     position: auto
#     show_cursor: true
#     resizable: true

window:
  width: 1280
  height: 720
  title: Robotech
  resizable: true
  fullscreen: true
  borderless: false
  exit_on_escape: true
  source_display: window

displays:
 window:
    width: 1280
    height: 720
    default: true

#slides:
#  attract_started:
#    widgets:
#      - type: image
#        image: attract

#slide_player:
#   mode_attract_started:
#     attract_started
#   mode_attract_stopped:
#      attract_started:
#         action: remove
