#config_version=5

virtual_platform_start_active_switches: s_trough1, s_trough2, s_trough3, s_trough4


keyboard:
  debug: true
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  s:
    switch: s_start
  p:
    switch: s_plunger_lane
    toggle: true
  shift-s:
    switch: s_spinner
  z:
    switch: s_left_flipper
  m:
    switch: s_right_flipper
  w:
    event: top_lanes_skill_flashing_hit
  i:
    event: invid_targets_skill_flashing_hit
  l:
    event: skill_shot_top_saucer_lunk_combo_hit
  # t:
  #   event: start_skillshot_saucer_timer
  d:
    event: debug_dump_stats
  e:
    event: start_end_invid_invasion_mode
  n:
    event: start_intro_invid_invasion
  g:
    event: start_intro_genesis_pit
  f:
    event: mode_intro_the_fortress_started
  q:
    event: start_end_invid_invasion_mode
  o:
    event: invid_target_group_hit_complete
  c:
    event: start_switches_countdown
  h:
    event: start_hurry_up_mode_start_ramp
  b:
    event: enable_lock_shots
  x:
    event: mode_invid_invasion_stopped
  j:
    event: pre_qualify_a_mode_invid_target_group_hit_complete
  u:
    event: pops_shot_hit
  v:
    event: start_mode_shot_flashing_hit
  r:
    event: start_intro_corg_mode
  t:
    event: top_target_protoculture_shot_flashing_hit
  k:
    event: sdf_skill_group_flashing_hit
