#config_version=5
# Robotech pinball machine


lights:
  l_rorbit_rollover_1:
    number: 0
    type: grb
    label: led0
    tags: rorbit_rollover, playfield
  l_rorbit_roller_2:
    number: 1
    type: grb
    label: led1
    tags: rorbit_rollover, playfield
  l_rorbit_roller_3:
    number: 2
    type: grb
    label: led2
    tags: rorbit_rollover, playfield
  l_rorbit_roller_4:
    number: 3
    type: grb
    label: led3
    tags: rorbit_rollover, playfield
  l_rlock_roller_1:
    number: 4
    type: grb
    label: led4
    tags: rlock_rollover, playfield
  l_rlock_roller_2:
    number: 5
    type: grb
    label: led5
    tags: rlock_rollover, playfield
  l_rlock_roller_3:
    number: 6
    type: grb
    label: led6
    tags: rlock_rollover, playfield
  l_rlock_roller_4:
    number: 7
    type: grb
    label: led7
    tags: rlock_rollover, playfield
  l_rlock_arrow:
    number: 8
    type: grb
    label: led8
    tags: playfield
  l_rook_x:
    number: 9
    type: grb
    label: led9
    tags: playfield
  l_right_orbit_arrow:
    number: 10
    type: grb
    label: led10
    tags: playfield
  l_lancer_x:
    number: 11
    type: grb
    label: led11
    tags: playfield
  l_s_led:
    number: 12
    type: grb
    label: led12
    tags: sdf, playfield
  l_d_led:
    number: 13
    type: grb
    label: led13
    tags: sdf, playfield
  l_f_led:
    number: 14
    type: grb
    label: led14
    tags: sdf, playfield
  l_sdf_arrow_led:
    number: 15
    type: grb
    label: led15
    tags: playfield
  l_lunk_x:
    number: 16
    type: grb
    label: led16
    tags: playfield
  l_right_inlane_c:
    number: 17
    type: grb
    label: led17
    tags: lanes, playfield
  l_right_outlane_h:
    number: 18
    type: grb
    label: led18
    tags: lanes, playfield
  l_shoot_again:
    number: 19
    type: grb
    label: led19
    tags: playfield
  l_b1:
    number: 20
    type: grb
    label: led20
    tags: playfield
  l_annie:
    number: 21
    type: grb
    label: led21
    tags: playfield
  l_rand:
    number: 22
    type: grb
    label: led22
    tags: playfield
  l_b2:
    number: 23
    type: grb
    label: led23
    tags: playfield
  l_rook:
    number: 24
    type: grb
    label: led24
    tags: playfield
  l_lunk:
    number: 25
    type: grb
    label: led25
    tags: playfield
  l_3x:
    number: 26
    type: grb
    label: led26
    tags: playfield
  l_b3:
    number: 27
    type: grb
    label: led27
    tags: playfield
  l_b4:
    number: 28
    type: grb
    label: led28
    tags: playfield
  l_2x:
    number: 29
    type: grb
    label: led29
    tags: playfield
  l_b5:
    number: 30
    type: grb
    label: led30
    tags: playfield
  l_b6:
    number: 31
    type: grb
    label: led31
    tags: playfield
  l_b7:
    number: 32
    type: grb
    label: led32
    tags: playfield
  l_b8:
    number: 33
    type: grb
    label: led33
    tags: playfield
  l_b9:
    number: 34
    type: grb
    label: led34
    tags: playfield
  l_tech_1:
    number: 35
    type: grb
    label: led35
    tags: tech_hotdog, playfield
  l_tech_2:
    number: 36
    type: grb
    label: led36
    tags: tech_hotdog, playfield
  l_tech_3:
    number: 37
    type: grb
    label: led37
    tags: tech_hotdog, playfield
  l_tech_4:
    number: 38
    type: grb
    label: led38
    tags: tech_hotdog, playfield
  l_tech_5:
    number: 39
    type: grb
    label: led39
    tags: tech_hotdog, playfield
  l_mission_3:
    number: 40
    type: grb
    label: led40
    tags: playfield
  l_mission_4:
    number: 41
    type: grb
    label: led41
    tags: playfield
  l_b10:
    number: 64
    type: grb
    label: led64
    tags: playfield
  l_b20:
    number: 65
    type: grb
    label: led65
    tags: playfield
  l_t6:
    number: 66
    type: grb
    label: led66
    tags: invid_target, playfield
  l_t5:
    number: 67
    type: grb
    label: led67
    tags: invid_target, playfield
  l_t4:
    number: 68
    type: grb
    label: led68
    tags: invid_target, playfield
  l_t3:
    number: 69
    type: grb
    label: led69
    tags: invid_target, playfield
  l_t2:
    number: 70
    type: grb
    label: led70
    tags: invid_target, playfield
  l_t1:
    number: 71
    type: grb
    label: led71
    tags: invid_target, playfield
  l_robo_5:
    number: 72
    type: grb
    label: led50
    tags: robo_hotdog, playfield
  l_robo_4:
    number: 73
    type: grb
    label: led51
    tags: robo_hotdog, playfield
  l_robo_3:
    number: 74
    type: grb
    label: led52
    tags: robo_hotdog, playfield
  l_robo_2:
    number: 75
    type: grb
    label: led53
    tags: robo_hotdog, playfield
  l_robo_1:
    number: 76
    type: grb
    label: led54
    tags: robo_hotdog, playfield
  l_mission_1:
    number: 77
    type: grb
    label: led55
    tags: playfield
  l_mission_2:
    number: 78
    type: grb
    label: led56
    tags: playfield
  l_kickback:
    number: 79
    type: grb
    label: led57
    tags: playfield
  l_left_outlane_t:
    number: 80
    type: grb
    label: led58
    tags: lanes, playfield
  l_left_inlane_e:
    number: 81
    type: grb
    label: led59
    tags: lanes, playfield
  l_rand_x:
    number: 82
    type: grb
    label: led60
    tags: playfield
  l_llock_arrow:
    number: 83
    type: grb
    label: led61
    tags: playfield
  l_llock_rollover_1:
    number: 84
    type: grb
    label: led62
    tags: llock_rollover, playfield
  l_llock_rollover_2:
    number: 85
    type: grb
    label: led63
    tags: llock_rollover, playfield
  l_llock_rollover_3:
    number: 86
    type: grb
    label: led64
    tags: llock_rollover, playfield
  l_llock_rollover_4:
    number: 87
    type: grb
    label: led65
    tags: llock_rollover, playfield
  l_annie_x:
    number: 88
    type: grb
    label: led66
    tags: playfield
  l_annie_arrow:
    number: 89
    type: grb
    label: led67
    tags: playfield
  l_mode_start:
    number: 90
    type: grb
    label: led68
    tags: playfield
  l_left_orbit_arrow:
    number: 91
    type: grb
    label: led69
    tags: playfield
  l_r_light:
    number: 92
    type: grb
    label: led70
    tags: lanes, playfield
  l_o_light:
    number: 93
    type: grb
    label: led71
    tags: lanes, playfield
  l_b_light:
    number: 94
    type: grb
    label: led72
    tags: lanes, playfield
  l_top_target_light:
    number: 95
    type: rgb
    label: led73
    tags: playfield
  l_o2_light:
    number: 96
    type: grb
    label: led74
    tags: lanes, playfield
  l_50k:
    number: 97
    type: grb
    label: led75
    tags: playfield
  l_20k:
    number: 98
    type: grb
    label: led76
    tags: playfield
  l_10k:
    number: 99
    type: grb
    label: led77
    tags: playfield
  # l_top_right_flasher:
  #   number: 2-0
  #   type: rgb
  #   label: led1
  #   tags: flasher, playfield
  # l_right_lock_flasher:
  #   number: 2-1
  #   type: rgb
  #   label: led2
  #   tags: flasher, playfield
  l_sdf_bank_flasher:
    number: 128
    type: rgb
    label: led3
    tags: flasher, sdf, playfield
  l_spinner_flasher:
    number: 129
    type: rgb
    label: led3
    tags: playfield
  l_lower_r_pop_bumper:
    number: 130
    type: rgb
    label: led4
    tags: flasher, playfield
  l_upper_r_pop_bumper:
    number: 131
    type: rgb
    label: led5
    tags: flasher, playfield
  l_upper_l_pop_bumper:
    number: 132
    type: rgb
    label: led6
    tags: flasher, playfield
  l_lower_l_pop_bumper:
    number: 133
    type: rgb
    label: led7
    tags: flasher, playfield
  # l_top_left_flasher:
  #   number: 2-7
  #   type: rgb
  #   label: led8
  #   tags: flasher, playfield
  # l_left_lock_flasher:
  #   number: 2-8
  #   type: rgb
  #   label: led9
  #   tags: flasher, playfield
  # l_kickback_flasher:
  #   number: 2-9
  #   type: rgb
  #   label: led10
  #   tags: flasher, playfield
