#config_version=5
# Robotech pinball machine

shows:
  quick_flash:
  - time: 0
    lights:
      (leds): red
  - time: +75ms
    lights:
      (leds): off
  - time: +75ms
#  - time: +75ms
#    lights:
#      (lights): red
#  - time: +75ms
#    lights:
#      (lights): off
#  - time: +75ms
#    lights:
#      (lights): red
#  - duration: -1
#    lights:
#      (lights): red
