# config_version=4

shows:

  quick_flash:
  - time: 0
    leds:
      (leds): white
  - time: +75ms
    leds:
      (leds): '000000'
  - time: +75ms
    leds:
      (leds): white
  - time: +75ms
    leds:
      (leds): '000000'
  - time: +75ms
    leds:
      (leds): white
  - duration: -1
    leds:
      (leds): white
