# config_version=4


shows:

quick_flash:
  - time: 0
    leds:
      (leds): white
  - time: '+100'
    leds:
      (leds): '000000'
  - time: '+100'
    leds:
      (leds): white
  - time: '+100'
    leds:
      (leds): '000000'
  - time: '+100'
    leds:
      (leds): white
  - time: '+100'