# config_version=4

shows:
  quick_flash:
  - time: 0
    leds:
      (leds): red
  - time: +75ms
    leds:
      (leds): off
  - time: +75ms
#  - time: +75ms
#    leds:
#      (leds): red
#  - time: +75ms
#    leds:
#      (leds): off
#  - time: +75ms
#    leds:
#      (leds): red
#  - duration: -1
#    leds:
#      (leds): red
