#config_version=4

shots:
   left_outlane_t:
     switch: s_kickback_t 
     show_tokens:
       leds: l_left_outlane_t
   left_inlane_e:
     switch: s_left_inlane_e
     #profile: quick_flash
     show_tokens:
       leds: l_left_inlane_e
   right_inlane_c:
     switch: s_right_inlane_c
     #profile: quick_flash
     show_tokens:
       leds: l_right_inlane_c
   right_outlane_h:
     switch: s_right_outlane_h
     #profile: quick_flash
     show_tokens:
       leds: l_right_outlane_h
   r_top_lane:
     switch: s_r_top_lane
     show_tokens:
       leds: l_r_light
   o1_top_lane:
     switch: s_o1_top_lane
     show_tokens:
       leds: l_o_light
   b_top_lane:
     switch: s_b_top_lane
     show_tokens:
       leds: l_b_light
   o2_top_lane:
     switch: s_o2_top_lane
     show_tokens:
       leds: l_o2_light
   left_target:
     switch: s_left_target
     profile: quick_flash
     show_tokens:
       leds: l_t1

shot_groups:
  tech_lanes:
    shots:
    - left_outlane_t
    - left_inlane_e
    - right_inlane_c
    - right_outlane_h
  robo_lanes:
    shots:
    - r_top_lane
    - o1_top_lane
    - b_top_lane
    - o2_top_lane

shot_profiles:
  quick_flash:
    states:
    - name: unlit
      show: flash
    - name: lit
      show: on
      loops: 0


