#config_version=5

mode:
  start_events:
    - start_end_invid_invasion_mode
  stop_events:
    - player_continue_show_ended
  priority: 1100

event_player:
  mode_end_invid_invasion_started:
    #- ramp_up_active{device.switches.s_up_down_ramp_switch.state == 1}
    - flipper_off
    - disable_Upper_Left_pop_bumper
    - disable_Upper_Right_pop_bumper
    - disable_Lower_Left_pop_bumper
    - disable_Lower_Right_pop_bumper
    - disable_sling
    - kickback_disable{mode.kickback.active}
    - ramp_diverter_disable
  player_continue_show_ended:
    - flipper_on
    - enable_Upper_Left_pop_bumper
    - enable_Upper_Right_pop_bumper
    - enable_Lower_Left_pop_bumper
    - enable_Lower_Right_pop_bumper
    - enable_sling
    - kickback_enable{mode.kickback.active}
    #- start_pre_qualify_mystery
    - start_skill_shot_mode

timers:
  eject_mystery_ball_end_invid_invation_timer:
    debug: true
    start_value: 2
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: check_if_okay_to_hold

# widgets:
#   player_num_keep_shooting_widget:
#     - type: text
#       text: PLAYER (number)
#       color: blue
#       font_size: 100
#       y: center + 80
#     - type: text
#       text: Keep Shooting
#       color: red
#       y: center #- 90
#       font_size: 70
#
# widget_player:
#   wait_for_instructions:
#     player_num_keep_shooting_widget:
#       action: add
#       slide: base_slide
#       widget_settings:
#         expire: 4s
#         z: 115


# queue_event_player:
#   mode_end_invid_invasion_started:
#     queue_event: my_queue
#     events_when_finished: end_end_invid_invasion

queue_event_player:
  mode_end_invid_invasion_started:
    queue_event: my_queue
    events_when_finished: end_end_invid_invasion

queue_relay_player:
  my_queue:
    post: start_end_invid_invasion_intro
    wait_for: end_invid_invasion_show_ended
  balldevice_bd_trough_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: player_continue_show_ended

shows:
  end_invid_invasion_timer_expired:
    - duration: 9
      slides:
        end_invid_invasion_timer_expired_slide:
          widgets:
            - type: text
              text: "MODE TIMER EXPIRED!"
              color: blue
              font_size: 80
              y: center + 300
            - type: video
              video: end_invid_invasion
            - type: text
              text: "DON'T MOVE"
              font_size: 80
              color: red
              x: center
              y: center - 300
              animations:
                show_slide:
                - property: opacity
                  value: 1
                  duration: .5s
                - property: opacity
                  value: 0
                  duration: .5s
                  repeat: true
  end_invid_invasion_ball_over:
    - duration: 9
      slides:
        end_invid_invasion_ball_over_slide:
          widgets:
            - type: text
              text: "BALL LOST"
              color: white
              font_size: 80
              y: center + 300
            - type: video
              video: end_invid_invasion
            - type: text
              text: "DON'T MOVE"
              font_size: 80
              color: red
              x: center
              y: center - 300
              animations:
                show_slide:
                - property: opacity
                  value: 1
                  duration: .5s
                - property: opacity
                  value: 0
                  duration: .5s
                  repeat: true
  end_invid_invasion_super_jackpot_collected:
    - duration: 9
      slides:
        end_invid_invasion_super_jackpot_collected_slide:
          widgets:
            - type: text
              text: "SUPER JACKPOT COLLECTED!"
              color: purple
              font_size: 80
              y: center + 300
            - type: video
              video: end_invid_invasion
            - type: text
              text: "DON'T MOVE"
              font_size: 80
              color: red
              x: center
              y: center - 300
              animations:
                show_slide:
                - property: opacity
                  value: 1
                  duration: .5s
                - property: opacity
                  value: 0
                  duration: .5s
                  repeat: true
  collect_team_members:
    - duration: 5
      slides:
        collect_team_members_slide:
          widgets:
            - type: text
              text: Make your way to Reflex Point
              color: red
              font_size: 80
              y: center + 100
            - type: text
              text: Assemble freedom fighters...
              color: white
              y: center-40
              font_size: 60
            - type: text
              text: "   to help defeat the Invid"
              color: white
              y: center - 100
              font_size: 60
  player_continue_show:
    - duration: 3
      slides:
        player_continue_slide:
          widgets:
            - type: text
              text: PLAYER (number)
              color: blue
              font_size: 120
              y: center + 90
            - type: text
              text: Keep Shooting
              color: red
              y: center - 10
              font_size: 90

light_player:
  mode_end_invid_invasion_started:
    gi_string:
      color: off
    playfield:
      color: off
      priority: 9900
  # mode_end_invid_invasion_stopped:
  #   gi_string:
  #     color: on
  #   playfield:
  #     color: on
  #     # priority: 1801


show_player:
  start_end_invid_invasion_intro.1{current_player.mode_end_action_flag == 0}:
    end_invid_invasion_ball_over:
      loops: 0
      events_when_stopped: start_collect_team_members_notice
  start_end_invid_invasion_intro.2{current_player.mode_end_action_flag == 1}:
    end_invid_invasion_timer_expired:
      loops: 0
      events_when_stopped: start_collect_team_members_notice
  start_end_invid_invasion_intro.3{current_player.mode_end_action_flag == 2}:
    end_invid_invasion_super_jackpot_collected:
      loops: 0
      events_when_stopped: start_collect_team_members_notice
  start_collect_team_members_notice:
    collect_team_members:
      loops: 0
      events_when_stopped: end_invid_invasion_show_ended
  # ball_save_end_invid_invasion_ball_save_enabled:
  #   fast_flash_show:
  #     key: end_invid_invasion_ball_save_flash
  #     speed: 3
  #     show_tokens:
  #       leds: l_shoot_again
  #       color: red
  #     action: play
  # mode_end_invid_invasion_show_stopping:
  #     end_invid_invasion_ball_save_flash:
  #       action: stop
  flipper_cancel.1{device.ball_devices.bd_trough.balls==4}:
    end_invid_invasion_timer_expired:
      action: stop
  flipper_cancel.2{device.ball_devices.bd_trough.balls==4}:
    end_invid_invasion_ball_over:
      action: stop
  flipper_cancel.3{device.ball_devices.bd_trough.balls==4}:
    end_invid_invasion_super_jackpot_collected:
      action: stop
  flipper_cancel.4{device.ball_devices.bd_trough.balls==4}:
    collect_team_members:
      action: stop
  end_invid_invasion_show_ended:
    player_continue_show:
      loops: 0
      events_when_stopped: player_continue_show_ended
  # flipper_cancel:
  #   player_continue_show:
  #     action: stop

# ball_saves:
#   end_invid_invasion_ball_save:
#     enable_events: mode_end_invid_invasion_started
#     auto_launch: no
#     balls_to_save: 1
#     debug: yes

variable_player:
  player_continue_show_ended:
    mode_end_action_flag:
      int: 0
      action: set
  mode_end_invid_invasion_started:
    invid_invasion_mode_total_points:
      int: current_player.score - current_player.invid_invasion_start_mode_score
      action: set
