#config_version=5

mode:
  start_events:
   - start_intro_the_fortress
  stop_events:
    - stop_intro_the_fortress_mode
  restart_on_next_ball: false
  priority: 8250

queue_event_player:
  mode_intro_the_fortress_started:
    queue_event: my_queue_the_fortress
    events_when_finished: stop_intro_the_fortress_mode

queue_relay_player:
  my_queue_the_fortress:
    post: start_the_fortress_intro
    wait_for: intro_the_fortress_show_ended
  balldevice_bd_trough_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: intro_the_fortress_show_ended
  balldevice_bd_right_lock_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: intro_the_fortress_show_ended

shows:
  the_fortress_intro:
    - duration: 24
      slides:
        intro_the_fortress_slide:
          widgets:
            - type: text
              text: THE FORTRESS !!!
              color: white
              font_size: 80
              x: center
              y: center+300
            - type: text
              text: Destroy The Fortress, lits Jackpot
              color: white
              x: center
              y: center-300
              font_size: 50
            - type: video
              video: intro_the_fortress_video

light_player:
  mode_intro_the_fortress_started{game.balls_in_play == 1}:
    gi_string:
      color: off
    playfield:
      color: off
      priority: 9900

show_player:
  start_the_fortress_intro:
    the_fortress_intro:
      loops: 0
      events_when_stopped: intro_the_fortress_show_ended
  flipper_cancel:
    the_fortress_intro:
      action: stop
