#config_version=5

mode:
  start_events:
    - mode_invid_invasion_stopped
  stop_events:
    - rook_collected
  restart_on_next_ball: true
  priority: 1400

event_player:
  mode_skill_shot_stopped.1:
    - post_rook_image
  mode_skill_shot_stopped.2{device.counters.rook_hit_counter.value==1}:
    - post_rook_r
  mode_skill_shot_stopped.3{device.counters.rook_hit_counter.value==2}:
    - post_rook_r
    - post_rook_o
  mode_skill_shot_stopped.4{device.counters.rook_hit_counter.value==3}:
    - post_rook_r
    - post_rook_o
    - post_rook_oo
  rr_shot_flashing_rook_hit:
    - post_rook_r
  ro_shot_flashing_rook_hit:
    - post_rook_o
  roo_shot_flashing_rook_hit:
    - post_rook_oo
  rook_shot_flashing_rook_hit:
    - post_rook_k

widget_player:
  post_rook_image:
    rook_qualify_image:
      action: add
      slide: base_slide
      priority: 1401
  post_rook_r:
    rook_r_widget:
      action: add
      slide: base_slide
      priority: 1402
  post_rook_o:
    rook_o_widget:
      action: add
      slide: base_slide
      priority: 1403
  post_rook_oo:
    rook_oo_widget:
      action: add
      slide: base_slide
      priority: 1404
  post_rook_k:
    rook_k_widget:
      action: add
      slide: base_slide
      priority: 1405


widgets:
  rook_qualify_image:
    - type: image
      image: rook_qualify
      x: center - 560
      y: center - 75
  rook_r_widget:
    - type: text
      text: R
      color: yellow
      font_size: 35
      x: center - 595
      y: center - 150
  rook_o_widget:
    - type: text
      text: O
      color: yellow
      font_size: 35
      x: center - 575
      y: center - 150
  rook_oo_widget:
    - type: text
      text: O
      color: yellow
      font_size: 35
      x: center - 555
      y: center - 150
  rook_k_widget:
    - type: text
      text: D
      color: yellow
      font_size: 35
      x: center - 535
      y: center - 150

shot_groups:
  rook_shot_group:
    shots:
      - rr_shot
      - ro_shot
      - roo_shot
      - rook_shot
    debug: true

shots:
  rr_shot:
    switch: s_right_lock_kickout
    profile: rook_profile
    enable_events:
      - mode_annie_mode_stopped{device.counters.rook_hit_counter.value==0}
      - mode_rand_mode_stopped{device.counters.rook_hit_counter.value==0}
      - mode_lunk_mode_stopped{device.counters.rook_hit_counter.value==0}
      - mode_skill_shot_stopped{device.counters.rook_hit_counter.value==0}
    disable_events:
      - rr_shot_flashing_rook_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    debug: true
  ro_shot:
    switch: s_right_lock_kickout
    profile: rook_profile
    enable_events:
      - rr_shot_flashing_rook_hit
      - mode_annie_mode_stopped{device.counters.rook_hit_counter.value==1}
      - mode_rand_mode_stopped{device.counters.rook_hit_counter.value==1}
      - mode_lunk_mode_stopped{device.counters.rook_hit_counter.value==1}
      - mode_skill_shot_stopped{device.counters.rook_hit_counter.value==1}
    disable_events:
      - ro_shot_flashing_rook_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    debug: true
  roo_shot:
    switch: s_right_lock_kickout
    profile: rook_profile
    enable_events:
      - ro_shot_flashing_rook_hit
      - mode_annie_mode_stopped{device.counters.rook_hit_counter.value==2}
      - mode_rand_mode_stopped{device.counters.rook_hit_counter.value==2}
      - mode_lunk_mode_stopped{device.counters.rook_hit_counter.value==2}
      - mode_skill_shot_stopped{device.counters.rook_hit_counter.value==2}
    disable_events:
      - roo_shot_flashing_rook_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    debug: true
  rook_shot:
    switch: s_right_lock_kickout
    profile: rook_profile
    enable_events:
      - roo_shot_flashing_rook_hit
      - mode_annie_mode_stopped{device.counters.rook_hit_counter.value==3}
      - mode_rand_mode_stopped{device.counters.rook_hit_counter.value==3}
      - mode_lunk_mode_stopped{device.counters.rook_hit_counter.value==3}
      - mode_skill_shot_stopped{device.counters.rook_hit_counter.value==3}
    disable_events:
      - rook_shot_flashing_rook_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    debug: true

shot_profiles:
  rook_profile:
    advance_on_hit: true # false
    states:
    # - name: unlit
    #   show: off
    - name: flashing_rook
      show: flash_rook_show
      sync_ms: 1500
      loops: -1
      speed: 5
    - name: hit
      show: off

counters:
  rook_hit_counter:
    count_events:
      - rook_shot_group_flashing_rook_hit
    starting_count: current_player.rook_start_count
    direction: up
    count_complete_value: 4
    reset_on_complete: false
    events_when_complete: rook_collected
    persist_state: true

variable_player:
  rook_collected:
    team_members_collected: 1
