#config_version=4

mode:
    start_events: ball_starting
    stop_events: skill_shot_flipper_start, sw_skill_shot_cancel, target_group_robo_lanes_skill_shot_hit
    priority: 400

timers:
    target_rotator:
        start_running: true
        tick_interval: 1s

logic_blocks:
    sequences:
        skill_shot_flipper_check:
            events: 
                - sw_flipper
            events_when_complete: skill_shot_flipper

shot_profiles:
    robo_lanes_skill_shot:
         rotation_pattern: r,r,r,r,l,l,l,l
         states:
             - name: unlit
               show: off
             - name: lit
               show: flash
               loops: -1
               speed: 10
             - name: hit
               show: on

shots:
    robo_lanes_skill_shot:
        advance_events: mode_skill_shot_auto_started

shot_groups:
    robo_lanes_skill_shot:
        profile: skill_shot
        rotate_events: timer_target_rotator_tick
        reset_events: mode_robo_lanes_skill_shot_auto_started|1

scoring:
    robo_lanes_skill_shot_active_hit:
        score: 2000
