#config_version=5

mode:
  start_events:
    #- ball_starting{ball==1}
    - mode_end_invid_invasion_stopped
    - mode_annie_mode_stopped
    - mode_rand_mode_stopped
    - mode_skill_shot_stopped
    - mode_rook_mode_stopped
    - marlene_shot_6_flashing_marlene_hit
    - mode_lunk_mode_stopped
  stop_events:
    - protoculture_collected
    - logicblock_marlene_hit_counter_hit{device.counters.marlene_hit_counter.value==6}
    - mode_invid_invasion_started
    - mode_annie_mode_started
    - mode_rand_mode_started
    - mode_skill_shot_started
    - mode_rook_mode_started
    - mode_lunk_mode_started
  restart_on_next_ball: true
  priority: 7000

event_player:
  logicblock_protoculture_hit_counter_hit{count==5}:
    - protoculture_award_extra_ball

counters:
  protoculture_hit_counter:
    count_events:  s_top_target_active #protoculture_shot_group_unlit_hit
    starting_count: 0
    direction: up
    count_complete_value: 10
    reset_on_complete: false
    events_when_complete: protoculture_collected
    persist_state: true

widgets:
  protoculture_hit_widget:
    - type: text
      text: Protoculture Collected
      color: yellow
      font_size: 60
      y: center + 50
    - type: text
      text: (protoculture_value)
      font_size: 80
      color: red
      y: center - 50
      number_grouping: true

widget_player:
  s_top_target_active: #protoculture_shot_group_unlit_hit:
    protoculture_hit_widget:
      action: add
      widget_settings:
        expire: 2s

show_player:
  s_top_target_active:
    fast_flash_show:
      key: s_top_target_flash
      loops: 4
      speed: 30
      show_tokens:
        leds: l_top_target_light
        color: white

# show_player:
#   mode_protoculture_started{device.counters.protoculture_hit_counter.value==1}:
#     P_1_show_on
#   logicblock_protoculture_hit_counter_hit{count==1}:
#     P_1_show_on
#   logicblock_protoculture_hit_counter_hit{count==2}:
#     P_2_show_on
#   mode_end_invid_invasion_stopped{device.counters.protoculture_hit_counter.value>=1}:
#     P1_show_on:
#       action: play
#   mode_end_invid_invasion_stopped{device.counters.protoculture_hit_counter.value>=2}:
#     P2_show_on:
#       action: play
#   # s_top_target_active{device.counters.protoculture_collected_counter.value==1}:
#   #   P1_show_on:
#   #     action: play
#   # s_top_target_active{device.counters.protoculture_collected_counter.value==2}:
#   #   P2_show_on:
#   #     action: play
#   # mode_bonus_will_start:
#   #   P1_show_on:
#   #     action: stop
#   #   P2_show_on:
#   #     action: stop
# #
# shows:
#   P_1_show_on:
#     - time: 0
#       lights:
#         l_b1: red #2F4F4F
#     - time: -1
#   P_2_show_on:
#     - time: 0
#       lights:
#         l_b2: 2F4F4F
#     - time: -1

# shot_groups:
#   protoculture_shot_group:
#     shots: P_1, P_2, P_3, P_4, P_5, P_6, P_7, P_8, P_9
#     # enable_events:
#     #   - mode_end_invid_invasion_stopped
#     #   - mode_annie_mode_stopped
#     #   - mode_rand_mode_stopped
#     #   - marlene_shot_6_flashing_marlene_hit
#     # disable_events:
#     #   - mode_invid_invasion_started
#     #   - mode_annie_mode_started
#     #   - mode_rand_mode_started
#     #   - logicblock_marlene_hit_counter_hit{device.counters.marlene_hit_counter.value==6}
#     debug: true
#
#
# shots:
#   P_1:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b1
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value==0}
#     #   - mode_end_invid_invasion_stopped{device.counters.protoculture_hit_counter.value>=0}
#     # disable_events:
#     #   - P_1_unlit_hit
#     advance_events: P_1_unlit_hit
#     debug: true
#   P_2:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b2
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value==1}
#       - P_1_unlit_hit
#     #   - mode_end_invid_invasion_stopped{device.counters.protoculture_hit_counter.value>=1}
#     # disable_events:
#     #   - P_2_unlit_hit
#     #   #- mode_protoculture_started{device.counters.protoculture_hit_counter.value<1 or device.counters.protoculture_hit_counter.value>1}
#     #   - mode_invid_invasion_started
#     #advance_events: P_2_unlit_hit
#     debug: true
#   P_3:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b3
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value==2}
#       - P_2_unlit_hit
#     #   - mode_end_invid_invasion_stopped{device.counters.protoculture_hit_counter.value>=2}
#     # disable_events:
#     #     - P_3_unlit_hit
#     #   #- mode_protoculture_started{device.counters.protoculture_hit_counter.value<2 or device.counters.protoculture_hit_counter.value>2}
#     #   - mode_invid_invasion_started
#     advance_events: P_3_unlit_hit
#     debug: true
#   P_4:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b4
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value==3}
#       - P_3_unlit_hit
#     #   - mode_end_invid_invasion_stopped{device.counters.protoculture_hit_counter.value>=3}
#     # disable_events:
#     #   - P_4_unlit_hit
#     #   #- mode_protoculture_started{device.counters.protoculture_hit_counter.value<3 or device.counters.protoculture_hit_counter.value>3}
#     #   - mode_invid_invasion_started
#     advance_events: P_4_unlit_hit
#     debug: true
#   P_5:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b5
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value==4}
#       - P_4_unlit_hit
#     #   - mode_end_invid_invasion_stopped{device.counters.protoculture_hit_counter.value>=4}
#     disable_events:
#       - logicblock_marlene_hit_counter_hit{device.counters.marlene_hit_counter.value==6}
#     #   #- mode_protoculture_started{device.counters.protoculture_hit_counter.value<3 or device.counters.protoculture_hit_counter.value>3}
#     #   - mode_invid_invasion_started
#     advance_events: P_5_unlit_hit
#     debug: true
#   P_6:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b6
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value==5}
#       - P_5_unlit_hit
#     advance_events: P_6_unlit_hit
#     debug: true
#   P_7:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b7
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value>=6}
#       - P_6_unlit_hit
#     advance_events: P_7_unlit_hit
#     debug: true
#   P_8:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b8
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value>=7}
#       - P_7_unlit_hit
#     advance_events: P_8_unlit_hit
#     debug: true
#   P_9:
#     switch: s_top_target
#     profile: protoculture_profile
#     show_tokens:
#       leds: l_b9
#     enable_events:
#       - mode_protoculture_started{device.counters.protoculture_hit_counter.value>=8}
#       - P_8_unlit_hit
#     advance_events: P_9_unlit_hit
#     debug: true
#
# shot_profiles:
#   protoculture_profile:
#     advance_on_hit: false
#     states:
#     - name: unlit
#       show: off
#     - name: hit
#       show: protoculture_cell_on

variable_player:
  s_top_target_active: #protoculture_shot_group_unlit_hit:
    protoculture_value:
      int: ((1000 + ((device.counters.protoculture_hit_counter.value-1) * 250)) * current_player.protoculture_shot_multiplier) * current_player.pf_multiplier
      action: set
    score: ((1000 + ((device.counters.protoculture_hit_counter.value-1) * 250)) * current_player.protoculture_shot_multiplier) * current_player.pf_multiplier
