#config_version=5
#Robotech

mode:
  start_events:
    - mode_end_invid_invasion_started
  stop_events:
    - mode_end_invid_invasion_stopped
  priority: 9100

ball_saves:
  end_invid_invasion_ball_save:
    enable_events: mode_ball_save_end_invid_invasion_started
    auto_launch: no
    balls_to_save: 1
    debug: yes

# light_player:
#   mode_ball_save_end_invid_invasion_started:
#     gi_string:
#       color: off
#     playfield:
#       color: off
#       priority: 9099
#   mode_ball_save_end_invid_invasion_stopped:
#     gi_string:
#       color: on
#     playfield:
#       color: on

show_player:
  ball_save_end_invid_invasion_ball_save_enabled:
    fast_flash_show:
      key: end_invid_invasion_ball_save_flash
      speed: 3
      show_tokens:
        leds: l_shoot_again
        color: red
      action: play
  mode_ball_save_end_invid_invasion_stopping:
      end_invid_invasion_ball_save_flash:
        action: stop
