#config_version=4


mode:
   start_events: s_left_inlane_e_active
   stop_events: timer_super_spinner_complete, timer_super_spinner_stopped
   stop_on_ball_end: true
   priority: 125

scoring:
   super_spinner_flashing_hit:
     score: 1000

shots:
   super_spinner_shot:
     switch: s_spinner
     show_tokens:
       led: l_left_orbit_arrow
     profile: super_spinner

shot_profiles:
   super_spinner:
     states:
      - name: flashing
        show: flash
        speed: 7
     loop: no

timers:
   super_spinner:
     start_value: 1
     end_value: 6
     direction: up
     tick_interval: 1s
     start_running: true
