#config_version=5

mode:
  start_events:
    - mode_invid_invasion_stopped
  stop_events:
    - marlene_collected
  restart_on_next_ball: true
  priority: 1700

event_player:
  # drop_target_left_drop_down:
  #   - drop_reset_up|1s
  # drop_target_middle_drop_down:
  #   - drop_reset_up|1s
  # drop_target_right_drop_down:
  #   - drop_reset_up|1s
  mode_skill_shot_stopped.1:
    - post_marlene_image
  mode_skill_shot_stopped.2{device.counters.marlene_hit_counter.value==1}:
    - post_marlene_m
  mode_skill_shot_stopped.3{device.counters.marlene_hit_counter.value==2}:
    - post_marlene_m
    - post_marlene_a
  mode_skill_shot_stopped.4{device.counters.marlene_hit_counter.value==3}:
    - post_marlene_m
    - post_marlene_a
    - post_marlene_r
  mode_skill_shot_stopped.5{device.counters.marlene_hit_counter.value==4}:
    - post_marlene_m
    - post_marlene_a
    - post_marlene_r
    - post_marlene_l
  mode_skill_shot_stopped.6{device.counters.marlene_hit_counter.value==5}:
    - post_marlene_m
    - post_marlene_a
    - post_marlene_r
    - post_marlene_l
    - post_marlene_e
  mode_skill_shot_stopped.7{device.counters.marlene_hit_counter.value==6}:
    - post_marlene_m
    - post_marlene_a
    - post_marlene_r
    - post_marlene_l
    - post_marlene_e
    - post_marlene_n
  marlene_shot_1_flashing_marlene_hit.1{device.counters.marlene_hit_counter.value==2}:
    - post_marlene_a
  marlene_shot_1_flashing_marlene_hit.2{device.counters.marlene_hit_counter.value==3}:
    - post_marlene_r
  marlene_shot_1_flashing_marlene_hit.3{device.counters.marlene_hit_counter.value==4}:
    - post_marlene_l
  marlene_shot_1_flashing_marlene_hit.4{device.counters.marlene_hit_counter.value==5}:
    - post_marlene_e
  marlene_shot_1_flashing_marlene_hit.5{device.counters.marlene_hit_counter.value==6}:
    - post_marlene_n
  marlene_shot_2_flashing_marlene_hit.1{device.counters.marlene_hit_counter.value==2}:
    - post_marlene_a
  marlene_shot_2_flashing_marlene_hit.2{device.counters.marlene_hit_counter.value==3}:
    - post_marlene_r
  marlene_shot_2_flashing_marlene_hit.3{device.counters.marlene_hit_counter.value==4}:
    - post_marlene_l
  marlene_shot_2_flashing_marlene_hit.4{device.counters.marlene_hit_counter.value==5}:
    - post_marlene_e
  marlene_shot_2_flashing_marlene_hit.5{device.counters.marlene_hit_counter.value==6}:
    - post_marlene_n
  marlene_shot_3_flashing_marlene_hit.1{device.counters.marlene_hit_counter.value==2}:
    - post_marlene_a
  marlene_shot_3_flashing_marlene_hit.2{device.counters.marlene_hit_counter.value==3}:
    - post_marlene_r
  marlene_shot_3_flashing_marlene_hit.3{device.counters.marlene_hit_counter.value==4}:
    - post_marlene_l
  marlene_shot_3_flashing_marlene_hit.4{device.counters.marlene_hit_counter.value==5}:
    - post_marlene_e
  marlene_shot_3_flashing_marlene_hit.5{device.counters.marlene_hit_counter.value==6}:
    - post_marlene_n
  marlene_shot_4_flashing_marlene_hit.1{device.counters.marlene_hit_counter.value==2}:
    - post_marlene_a
  marlene_shot_4_flashing_marlene_hit.2{device.counters.marlene_hit_counter.value==3}:
    - post_marlene_r
  marlene_shot_4_flashing_marlene_hit.3{device.counters.marlene_hit_counter.value==4}:
    - post_marlene_l
  marlene_shot_4_flashing_marlene_hit.4{device.counters.marlene_hit_counter.value==5}:
    - post_marlene_e
  marlene_shot_4_flashing_marlene_hit.5{device.counters.marlene_hit_counter.value==6}:
    - post_marlene_n
  marlene_shot_5_flashing_marlene_hit.1{device.counters.marlene_hit_counter.value==2}:
    - post_marlene_a
  marlene_shot_5_flashing_marlene_hit.2{device.counters.marlene_hit_counter.value==3}:
    - post_marlene_r
  marlene_shot_5_flashing_marlene_hit.3{device.counters.marlene_hit_counter.value==4}:
    - post_marlene_l
  marlene_shot_5_flashing_marlene_hit.4{device.counters.marlene_hit_counter.value==5}:
    - post_marlene_e
  marlene_shot_5_flashing_marlene_hit.5{device.counters.marlene_hit_counter.value==6}:
    - post_marlene_n
  marlene_shot_6_flashing_marlene_hit:
    - post_marlene_ee

widget_player:
  post_marlene_image:
    marlene_qualify_image:
      action: add
      slide: base_slide
      priority: 1701
  post_marlene_m:
    marlene_m_widget:
      action: add
      slide: base_slide
      priority: 1702
  post_marlene_a:
    marlene_a_widget:
      action: add
      slide: base_slide
      priority: 1703
  post_marlene_r:
    marlene_r_widget:
      action: add
      slide: base_slide
      priority: 1704
  post_marlene_l:
    marlene_l_widget:
      action: add
      slide: base_slide
      priority: 1705
  post_marlene_e:
    marlene_e_widget:
      action: add
      slide: base_slide
      priority: 1706
  post_marlene_n:
    marlene_n_widget:
      action: add
      slide: base_slide
      priority: 1707
  post_marlene_ee:
    marlene_ee_widget:
      action: add
      slide: base_slide
      priority: 1708

widgets:
  marlene_qualify_image:
    - type: image
      image: marlene_qualify
      x: center + 550
      y: center - 75
  marlene_m_widget:
    - type: text
      text: M
      color: ff1493
      font_size: 30
      x: center + 510
      y: center - 150
  marlene_a_widget:
    - type: text
      text: A
      color: ff1493
      font_size: 30
      x: center + 525
      y: center - 150
  marlene_r_widget:
    - type: text
      text: R
      color: ff1493
      font_size: 30
      x: center + 540
      y: center - 150
  marlene_l_widget:
    - type: text
      text: L
      color: ff1493
      font_size: 30
      x: center + 555
      y: center - 150
  marlene_e_widget:
    - type: text
      text: E
      color: ff1493
      font_size: 30
      x: center + 570
      y: center - 150
  marlene_n_widget:
    - type: text
      text: N
      color: ff1493
      font_size: 30
      x: center + 585
      y: center - 150
  marlene_ee_widget:
    - type: text
      text: E
      color: ff1493
      font_size: 30
      x: center + 600
      y: center - 150

shot_groups:
  marlene_shot_group:
    shots:
      - marlene_shot_1
      - marlene_shot_2
      - marlene_shot_3
      - marlene_shot_4
      - marlene_shot_5
      - marlene_shot_6
    debug: true

shots:
  marlene_shot_1:
    switch: s_left_lock_kickout
    profile: marlene_profile
    enable_events:
      - mode_annie_mode_stopped{device.shots.marlene_shot_1.state == 0}
      - mode_rand_mode_stopped{device.shots.marlene_shot_1.state == 0}
      - mode_rook_mode_stopped{device.shots.marlene_shot_1.state == 0}
      - mode_lunk_mode_stopped{device.shots.marlene_shot_1.state == 0}
      - mode_skill_shot_stopped{device.shots.marlene_shot_1.state == 0}
    disable_events:
      - marlene_shot_1_flashing_marlene_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    show_tokens:
      leds: l_rand_x
    debug: true
  marlene_shot_2:
    switch: s_left_orbit
    profile: marlene_profile
    enable_events:
      - mode_annie_mode_stopped{device.shots.marlene_shot_2.state == 0}
      - mode_rand_mode_stopped{device.shots.marlene_shot_2.state == 0}
      - mode_rook_mode_stopped{device.shots.marlene_shot_2.state == 0}
      - mode_lunk_mode_stopped{device.shots.marlene_shot_2.state == 0}
      - mode_skill_shot_stopped{device.shots.marlene_shot_2.state == 0}
    disable_events:
      - marlene_shot_2_flashing_marlene_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    show_tokens:
      leds: l_annie_x
    debug: true
  marlene_shot_3:
    switch: s_right_lock_kickout
    profile: marlene_profile
    enable_events:
      - mode_annie_mode_stopped{device.shots.marlene_shot_3.state == 0}
      - mode_rand_mode_stopped{device.shots.marlene_shot_3.state == 0}
      - mode_rook_mode_stopped{device.shots.marlene_shot_3.state == 0}
      - mode_lunk_mode_stopped{device.shots.marlene_shot_3.state == 0}
      - mode_skill_shot_stopped{device.shots.marlene_shot_3.state == 0}
    disable_events:
      - marlene_shot_3_flashing_marlene_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    show_tokens:
      leds: l_rook_x
    debug: true
  marlene_shot_4:
    hit_events: lancer_shot_sequence_hit
    profile: marlene_profile
    enable_events:
      - mode_annie_mode_stopped{device.shots.marlene_shot_4.state == 0}
      - mode_rand_mode_stopped{device.shots.marlene_shot_4.state == 0}
      - mode_rook_mode_stopped{device.shots.marlene_shot_4.state == 0}
      - mode_lunk_mode_stopped{device.shots.marlene_shot_4.state == 0}
      - mode_skill_shot_stopped{device.shots.marlene_shot_4.state == 0}
    disable_events:
      - marlene_shot_4_flashing_marlene_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    show_tokens:
      leds: l_lancer_x
    debug: true
  marlene_shot_5:
    switch: s_d_target
    profile: marlene_profile
    enable_events:
      - mode_annie_mode_stopped{device.shots.marlene_shot_5.state == 0}
      - mode_rand_mode_stopped{device.shots.marlene_shot_5.state == 0}
      - mode_rook_mode_stopped{device.shots.marlene_shot_5.state == 0}
      - mode_lunk_mode_stopped{device.shots.marlene_shot_5.state == 0}
      - mode_skill_shot_stopped{device.shots.marlene_shot_5.state == 0}
    disable_events:
      - marlene_shot_5_flashing_marlene_hit
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    show_tokens:
      leds: l_lunk_x
    debug: true
  marlene_shot_6:
    switch: s_top_target
    profile: marlene_profile
    enable_events:
      - logicblock_marlene_hit_counter_hit{count==6}
      - mode_annie_mode_stopped{device.counters.marlene_hit_counter.value == 6}
      - mode_rand_mode_stopped{device.counters.marlene_hit_counter.value == 6}
      - mode_rook_mode_stopped{device.counters.marlene_hit_counter.value == 6}
      - mode_lunk_mode_stopped{device.counters.marlene_hit_counter.value == 6}
      - mode_skill_shot_stopped{device.counters.marlene_hit_counter.value == 6}
    disable_events:
      - mode_qualify_marlene_started
      - mode_intro_annie_mode_started
      - mode_intro_rand_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
    show_tokens:
      leds: l_50k
    debug: true

shot_profiles:
  marlene_profile:
    advance_on_hit: true #false
    states:
    # - name: unlit
    #   show: off
    - name: flashing_marlene
      show: flash_marlene_show
      sync_ms: 1500
      loops: -1
      speed: 5
    - name: hit
      show: off

counters:
  marlene_hit_counter:
    count_events:
      - marlene_shot_group_flashing_marlene_hit
    starting_count: current_player.marlene_start_count
    direction: up
    count_complete_value: 7
    reset_on_complete: false
    events_when_complete:
      - marlene_collected
      - start_marlene_mode
    persist_state: true

variable_player:
  marlene_collected:
    team_members_collected: 1
