#config_version=5
tilt:
  warnings_to_tilt: 3
  #reset_warnings_events: ball_ended
  multiple_hit_window: 300ms
  settle_time: 5s
  tilt_warnings_player_var: tilt_warnings

slide_player:
  tilt_warning_1:
    s_tilt_warning_1:
      force: true
      expire: 2s
  tilt_warning_2:
    s_tilt_warning_2:
      force: true
      expire: 3s
  tilt:
    s_tilt:
      force: true
  tilt_clear:
    s_tilt:
      action: remove

slides:
  s_tilt_warning_1:
    #expire: 3s
    widgets:
      - type: text
        font_size: 100
        text: DANGER!
        color: red
  s_tilt_warning_2:
    #expire: 3s
    widgets:
      - type: text
        font_size: 100
        text: DANGER!!
        color: red
        y: center+30
      - type: text
        font_size: 100
        text: DANGER!!
        color: red
        y: center-30
  s_tilt:
    widgets:
      - type: text
        font_size: 200
        text: TILT
        color: red

sound_player:
  tilt:
    afm_tilt
