#config_version=5
mode:
  start_events: mode_attract_started
  stop_events: mode_attract_stopped  # not sure what event to use here????
  code: mpf.modes.carousel.code.carousel.Carousel

mode_settings:
  selectable_items: title_screen, last_score, high_score, invid_score, mpf_logo
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active

slide_player:
  carousel_title_highlighted: select_title_screen
  carousel_last_score_highlighted: select_last_score
  carousel_high_score_highlighted: select_high_score
  carousel_invid_score_highlighted: select_invid_score
  carousel_mpf_logo_highlighted: select_mpf_logo
    # flipper_cancel:
    #   last_game_scores:
    #     priority: 1
    #     expire: 10s


show_player:
  - duration: 5
    slides:
      title_screen:
      - type: image
        image: attract

  - duration: 5
    slides:
      last_game_scores:
        - type: text
          text: Player 1
          y: center + 100
          font_size: 80
        - type: text
          text: (machine|player1_score)
          number_grouping: true
          #min_digits: 2
          font_size: 80
          y: center + 40

  - duration: 5
    slides:
      attract_all_high_scores:
        - type: text
          text: (machine|score1_label)
          y: center + 280
          font_size: 45
        - type: text
          text: (machine|score1_name) (machine|score1_value)
          number_grouping: true
          y: center + 250
          font_size: 40
          color: red
        - type: text
          text: (machine|score2_label)
          y: center + 200
          font_size: 45
        - type: text
          text: (machine|score2_name) (machine|score2_value)
          number_grouping: true
          y: center + 170
          font_size: 40
          color: red
        - type: text
          text: (machine|score3_label)
          y: center + 120
          font_size: 45
        - type: text
          text: (machine|score3_name) (machine|score3_value)
          number_grouping: true
          y: center + 90
          font_size: 40
          color: red
        - type: text
          text: (machine|score4_label)
          y: center + 40
          font_size: 45
        - type: text
          text: (machine|score4_name) (machine|score4_value)
          number_grouping: true
          y: center + 10
          font_size: 40
          color: red
        - type: text
          text: (machine|score5_label)
          y: center - 40
          font_size: 45
        - type: text
          text: (machine|score5_name) (machine|score5_value)
          number_grouping: true
          y: center - 70
          font_size: 40
          color: red
        - type: text
          text: (machine|score6_label)
          y: center - 120
          font_size: 45
        - type: text
          text: (machine|score6_name) (machine|score6_value)
          number_grouping: true
          y: center - 150
          font_size: 40
          color: red
        - type: text
          text: (machine|score7_label)
          y: center - 200
          font_size: 45
        - type: text
          text: (machine|score7_name) (machine|score7_value)
          number_grouping: true
          y: center - 230
          font_size: 40
          color: red
      # transition:
      #   type: push
      #   duration: 500ms
      #   direction: left

  - duration: 5
    slides:
      attract_invid_scores:
        - type: text
          text: (machine|invid1_label)
          y: center + 140
          font_size: 70
        - type: text
          text: (machine|invid1_name) (machine|invid1_value)
          number_grouping: true
          y: center + 90
          font_size: 70
          color: purple
        - type: text
          text: (machine|invid2_label)
          y: center
          font_size: 60
        - type: text
          text: (machine|invid2_name) (machine|invid2_value)
          number_grouping: true
          y: center - 40
          font_size: 60
          color: purple

  - duration: 5
    slides:
      mpf_logo:
      - type: image
        image: mpf-logo-full
