#config_version=5

mode:
  start_events:
    - mode_intro_rand_mode_started #start_rand_mode #mode_rand_mode_started
  stop_events:
    - timer_rand_mode_timer_complete
    - ball_will_end
    - rand_mode_success
  stop_on_ball_end: true
  priority: 2200

event_player:
  mode_rand_mode_started.1:
    logicblock_rand_mode_invid_shots_made_hit:
      count: 0
  mode_rand_mode_started.2:
    timer_rand_mode_timer_tick:
      ticks_remaining: 60
  mode_rand_mode_started.3:
    - display_rand_mode_widgets
    - orbit_gate_disable
    - disable_rand_mode_shots
    - advance_rand_mode_invid_targets
  multiball_rand_mode_2_ball_started:
    - drop_reset_up
    - play_rand_mode_music
  drop_target_left_drop_down:
    - drop_reset_up|1s
  drop_target_middle_drop_down:
    - drop_reset_up|1s
  drop_target_right_drop_down:
    - drop_reset_up|1s
  # timer_rand_mode_timer_started:
  #   logicblock_rand_mode_invid_shots_made_hit:
  #     count: 0
  # rand_mode_invid_shot_group_4_flashing_hit:
  #   - rand_mode_success

multiballs:
  rand_mode_2_ball:
    ball_count: 1
    ball_count_type: add # total
    #start_events:  mode_rand_mode_started
    start_or_add_a_ball_events:
      - stop_intro_rand_mode
    ball_locks: bd_left_lock
    shoot_again: 0
    # disable_events:
    #   - mode_rand_mode_stopping
    debug: true

ball_saves:
  rand_mode_invid_hit_ball_save:
    active_time: 3s
    grace_period: 2s
    enable_events:
      - rand_mode_invid_shot_group_1_flashing_hit{not mode.ball_save_rand_mode.active}
      - rand_mode_invid_shot_group_3_flashing_hit{not mode.ball_save_rand_mode.active}
      - rand_mode_invid_shot_group_4_flashing_hit{not mode.ball_save_rand_mode.active}
    disable_events:
      - mode_rand_mode_started
      #- ball_save_rand_mode_invid_hit_ball_save_disabled
    timer_start_events:
      - rand_mode_invid_shot_group_1_flashing_hit
      - rand_mode_invid_shot_group_3_flashing_hit
      - rand_mode_invid_shot_group_4_flashing_hit
    early_ball_save_events:
      - s_right_outlane_h_active
      - s_kickback_t_active{not mode.kickback.active}
    auto_launch: yes
    balls_to_save: 1
    #restart_on_complete: yes
    debug: yes

show_player:
  ball_save_rand_mode_invid_hit_ball_save_timer_start:
    fast_flash_show:
      key: rand_mode_invid_hit_ball_save_flash
      action: play
      speed: 20
      show_tokens:
        leds: l_shoot_again
        color: 2E0854 #red
  ball_save_rand_mode_invid_hit_ball_save_disabled:
    rand_mode_invid_hit_ball_save_flash:
      action: stop

widgets:
  rand_mode_time_display_widget:
    - type: text
      text: TIMER
      color: blue
      font_size: 100
      y: center + 220
      x: center - 450
      z: 1150
  rand_mode_timer_widget:
    - type: text
      text: (ticks_remaining)
      color: red
      font_size: 100
      y: center + 150
      x: center - 450
      z: 1150
  rand_left_rectangle:
    - type: rectangle
      anchor_x: left
      anchor_y: bottom
      x: 13
      y: 190
      z: 1100
      width: 125
      height: 500
      color: black
  rand_right_rectangle:
    - type: rectangle
      anchor_x: left
      anchor_y: bottom
      x: 1137
      y: 190
      z: 1100
      width: 130
      height: 500
      color: black
  rand_mode_invid_display_widget:
    - type: text
      text: "Invid"
      color: 2E0854 #purple
      font_size: 100
      y: center + 220
      x: center + 450
      z: 1150
  rand_mode_invid_count_widget:
    - type: text
      text: "(count)/3"
      color: green
      font_size: 100
      y: center + 150
      x: center + 445
      z: 1150

widget_player:
  #mode_rand_mode_started:
  display_rand_mode_widgets:
    rand_left_rectangle:
      action: add
      slide: base_slide
      priority: 2201
    rand_right_rectangle:
      action: add
      slide: base_slide
      priority: 2202
  #timer_rand_mode_timer_started:
    rand_mode_time_display_widget:
      action: add
      slide: base_slide
      priority: 2203
    rand_mode_timer_widget:
      action: update
      slide: base_slide
      priority: 2204
    rand_mode_invid_display_widget:
      action: add
      slide: base_slide
      priority: 2205
    rand_mode_invid_count_widget:
      action: update
      slide: base_slide
      priority: 2206
  timer_rand_mode_timer_tick:
    rand_mode_timer_widget:
      action: update
      slide: base_slide
      priority: 2207
  logicblock_rand_mode_invid_shots_made_hit:
    rand_mode_invid_count_widget:
      action: update
      slide: base_slide
      priority: 2208
  # mode_rand_mode_started:
  #   rand_left_rectangle:
  #     action: add
  #     slide: base_slide
  #     #priority: 2210
  #   rand_right_rectangle:
  #     action: add
  #     slide: base_slide
  #     #priority: 2211

slide_player:
  logicblock_rand_mode_invid_shots_made_updated.1{value==1}:
    rand_mode_1st_kill_slide:
      priority: 2250
      expire: 3s
  logicblock_rand_mode_invid_shots_made_updated.2{value==2}:
    rand_mode_2nd_kill_slide:
      priority: 2260
      expire: 4s

slides:
  rand_mode_1st_kill_slide:
    widgets:
      - type: text
        text: INVID DESTROYED
        font_size: 80
        color: blue
        x: center
        y: center+300
        # z: 120
      - type: video
        video: rand_mode_1st_kill
      - type: text
        text: (invid_kill_value)
        font_size: 80
        color: red
        x: center
        y: center-300
        number_grouping: true
        # z: 120
  rand_mode_2nd_kill_slide:
    widgets:
      - type: text
        text: INVID DESTROYED
        font_size: 80
        color: blue
        x: center
        y: center+300
        # z: 120
      - type: video
        video: rand_mode_2nd_kill
      - type: text
        text: (invid_kill_value)
        font_size: 80
        color: red
        x: center
        y: center-300
        number_grouping: true
        # z: 120

timers:
  rand_mode_timer:
    debug: true
    start_value: 60
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: multiball_rand_mode_2_ball_started
      - action: add
        event: rand_mode_orbits_shot_group_2_flashing_hit
        value: 5
      - action: add
        event: spinner_shot_hit
        value: current_player.spinner_time_value
  target_rotator_1:
    start_running: false #true
    tick_interval: 2s
    control_events:
      - action: start
        event: mode_intro_rand_mode_stopped
      - action: stop
        event: rand_mode_invid_shot_group_1_flashing_hit
    debug: true
  target_rotator_3:
    start_running: false
    tick_interval: 1s
    control_events:
      - action: start
        event: rand_mode_orbits_shot_group_2_flashing_hit{device.counters.orbit_shots_made_counter.value<=1}
      - action: stop
        event: rand_mode_invid_shot_group_3_flashing_hit
    debug: true
  target_rotator_4:
    start_running: false
    tick_interval: 0.75s
    control_events:
      - action: start
        event: orbits_complete
      - action: stop
        event: rand_mode_invid_shot_group_4_flashing_hit


shot_groups:
  rand_mode_invid_shot_group_1:
    shots:
      - rand_mode_g1_invid1_shot1
      - rand_mode_g1_invid2_shot2
      - rand_mode_g1_invid3_shot3
    #rotate_right_events:
    rotate_left_events: timer_target_rotator_1_tick
    # enable_events: mode_rand_mode_starting
    disable_events:
      - rand_mode_invid_shot_group_1_flashing_hit
    reset_events: rand_mode_invid_shot_group_1_flashing_hit
    debug: True
  rand_mode_orbits_shot_group_2:
    shots: rand_mode_g2_left_orbit_shot1, rand_mode_g2_right_orbit_shot2
    enable_events:
      - rand_mode_invid_shot_group_1_flashing_hit
      - rand_mode_invid_shot_group_3_flashing_hit
    disable_events:
      - disable_rand_mode_shots #mode_rand_mode_started
      - rand_mode_orbits_shot_group_2_flashing_hit
    debug: True
  rand_mode_invid_shot_group_3:
    shots: rand_mode_g3_invid4_shot1, rand_mode_g3_invid5_shot2, rand_mode_g3_invid6_shot3
    rotate_left_events: timer_target_rotator_3_tick
    enable_events:
      - rand_mode_orbits_shot_group_2_flashing_hit{device.counters.orbit_shots_made_counter.value<=0} # {shot_group.rand_mode_orbits_shot_group.state != "hit"}
    disable_events:
      - disable_rand_mode_shots #mode_rand_mode_started
      - rand_mode_invid_shot_group_3_flashing_hit
      # - rand_mode_orbits_shot_group_2_hit_complete
    debug: True
  rand_mode_invid_shot_group_4:
    shots: rand_mode_g4_invid1_shot1, rand_mode_g4_invid2_shot2, rand_mode_g4_invid3_shot3, rand_mode_g4_invid4_shot4, rand_mode_g4_invid5_shot5, rand_mode_g4_invid6_shot6
    rotate_right_events: timer_target_rotator_4_tick
    enable_events: orbits_complete
    disable_events:
      - disable_rand_mode_shots #mode_rand_mode_started
      - rand_mode_invid_shot_group_4_flashing_hit


shot_profiles:
  invid_targets_rand_mode:
    advance_on_hit: false
    block: true
    states:
      - name: unlit
        show: off
      - name: flashing
        show: flash_rand_mode_invid_targets_show
        loops: -1
        speed: 10
      - name: hit
        show: off
  orbits_rand_mode:
    advance_on_hit: true
    block: true
    states:
      - name: flashing
        show: flash_red_show
        loops: -1
        speed: 10
      - name: hit
        show: off
  # collect_mecha_flash:
  #   advance_on_hit: true
  #   states:
  #     - name: flashing
  #       show: flash_blue_show
  #       loops: -1
  #       speed: 10
  #     - name: hit
  #       show: off


shots:
  rand_mode_g1_invid1_shot1:
    switch: s_left_target
    profile: invid_targets_rand_mode
    #advance_events: mode_rand_mode_started
    show_tokens:
      leds: l_t1
  rand_mode_g1_invid2_shot2:
    switch: s_middle_target
    profile: invid_targets_rand_mode
    show_tokens:
      leds: l_t2
  rand_mode_g1_invid3_shot3:
    switch: s_right_target
    profile: invid_targets_rand_mode
    advance_events: advance_rand_mode_invid_targets|1
    show_tokens:
      leds: l_t3
  rand_mode_g2_left_orbit_shot1:
    switch: s_left_orbit
    profile: orbits_rand_mode
    show_tokens:
      leds: l_annie_arrow
  rand_mode_g2_right_orbit_shot2:
    hit_events:  right_obit_shot_sequence_hit
    profile: orbits_rand_mode
    show_tokens:
      leds: l_right_orbit_arrow
  rand_mode_g3_invid4_shot1:
    switch: s_left_drop_target
    profile: invid_targets_rand_mode
    advance_events: timer_target_rotator_3_started|1
    show_tokens:
      leds: l_t4
  rand_mode_g3_invid5_shot2:
    switch: s_middle_drop_target
    profile: invid_targets_rand_mode
    show_tokens:
      leds: l_t5
  rand_mode_g3_invid6_shot3:
    switch: s_right_drop_target
    profile: invid_targets_rand_mode
    show_tokens:
      leds: l_t6
  rand_mode_g4_invid1_shot1:
    switch: s_left_target
    profile: invid_targets_rand_mode
    show_tokens:
      leds: l_t1
  rand_mode_g4_invid2_shot2:
    switch: s_middle_target
    profile: invid_targets_rand_mode
    show_tokens:
      leds: l_t2
  rand_mode_g4_invid3_shot3:
    switch: s_right_target
    profile: invid_targets_rand_mode
    show_tokens:
      leds: l_t3
  rand_mode_g4_invid4_shot4:
    switch: s_left_drop_target
    profile: invid_targets_rand_mode
    show_tokens:
      leds: l_t4
  rand_mode_g4_invid5_shot5:
    switch: s_middle_drop_target
    profile: invid_targets_rand_mode
    show_tokens:
      leds: l_t5
  rand_mode_g4_invid6_shot6:
    switch: s_right_drop_target
    profile: invid_targets_rand_mode
    advance_events: timer_target_rotator_4_started|1
    show_tokens:
      leds: l_t6

sequence_shots:
  right_obit_shot_sequence:
    switch_sequence:
      - s_spinner
      - s_right_orbit_rollover
      - s_gate_top_right
    sequence_timeout: 2s

counters:
  orbit_shots_made_counter:
    count_events: rand_mode_orbits_shot_group_2_flashing_hit
    starting_count: 0
    count_complete_value: 2
    events_when_complete: orbits_complete
    disable_on_complete: true
    reset_on_complete: false
    debug: true
  rand_mode_invid_shots_made:
    count_events:
      - rand_mode_invid_shot_group_1_flashing_hit
      - rand_mode_invid_shot_group_3_flashing_hit
      - rand_mode_invid_shot_group_4_flashing_hit
    starting_count: 0
    count_complete_value: 3
    direction: up
    persist_state: true
    reset_on_complete: false
    events_when_complete: rand_mode_success
    debug: true

variable_player:
  rand_mode_invid_shot_group_1_flashing_hit:
    invid_kill_value:
      int: 20000 * current_player.pf_multiplier
      action: set
    score: 20000 * current_player.pf_multiplier
  rand_mode_invid_shot_group_3_flashing_hit:
    invid_kill_value:
      int: 30000 * current_player.pf_multiplier
      action: set
    score: 30000 * current_player.pf_multiplier
  rand_mode_orbits_shot_group_2_flashing_hit:
    score: 5000 * current_player.pf_multiplier
  rand_mode_invid_shot_group_4_flashing_hit:
    invid_kill_value:
      int: 50000 * current_player.pf_multiplier
      action: set
    score: 50000 * current_player.pf_multiplier
  rand_mode_success:
    rand_mode_bonus_time_score:
      int: (device.timers.rand_mode_timer.ticks * 500 * game.balls_in_play) * current_player.pf_multiplier
      action: set
    score: (device.timers.rand_mode_timer.ticks * 500 * game.balls_in_play) * current_player.pf_multiplier

sound_player:
  play_rand_mode_music:
    rand_mode_cyclone_theme:
      action: play
      loops: -1
