#config_version=5

mode:
  start_events:
    - mode_invid_invasion_stopped
  stop_events:
    - lunk_collected
  restart_on_next_ball: true
  priority: 1600

event_player:
  mode_skill_shot_stopped.1:
    - post_lunk_image
  mode_skill_shot_stopped.2{device.counters.lunk_hit_counter.value==1}:
    - post_lunk_l
  mode_skill_shot_stopped.3{device.counters.lunk_hit_counter.value==2}:
    - post_lunk_l
    - post_lunk_u
  mode_skill_shot_stopped.4{device.counters.lunk_hit_counter.value==3}:
    - post_lunk_l
    - post_lunk_u
    - post_lunk_n
  lunk_shot_group_lit_complete{device.counters.lunk_hit_counter.value==1}:
    - post_lunk_l
  lunk_shot_group_lit_complete{device.counters.lunk_hit_counter.value==2}:
    - post_lunk_u
  lunk_shot_group_lit_complete{device.counters.lunk_hit_counter.value==3}:
    - post_lunk_n
  lunk_shot_group_lit_complete{device.counters.lunk_hit_counter.value==4}:
    - post_lunk_k
  lunk_shot_group_lit_complete:
    - play_lunk_sounds|1s
    - restart_lunk_shot_group|1

show_player:
  lunk_shot1_hit:
    fast_flash_show:
      key: lunk_shot1_flash
      loops: 3
      speed: 30
      show_tokens:
        leds: l_s_led
        color: 654321
  lunk_shot2_hit:
    fast_flash_show:
      key: lunk_shot2_flash
      loops: 3
      speed: 30
      show_tokens:
        leds: l_d_led
        color: 654321
  lunk_shot3_hit:
    fast_flash_show:
      key: lunk_shot3_flash
      loops: 3
      speed: 30
      show_tokens:
        leds: l_f_led
        color: 654321
  mode_skill_shot_stopped:
    flash_lunk_show:
      loops: -1
      speed: 5
      sync_ms: 1500
  mode_rand_mode_stopped:
    flash_lunk_show:
      loops: -1
      speed: 5
      sync_ms: 1500
  mode_annie_mode_stopped:
    flash_lunk_show:
      loops: -1
      speed: 5
      sync_ms: 1500
  mode_rook_mode_stopped:
    flash_lunk_show:
      loops: -1
      speed: 5
      sync_ms: 1500
  mode_corg_mode_stopped:
    flash_lunk_show:
      loops: -1
      speed: 5
      sync_ms: 1500
  # mode_genesis_pit_mode_stopped:
  #   flash_lunk_show:
  #     loops: -1
  #     speed: 5
  #     sync_ms: 1500
  # mode_the_fortress_mode_stopped:
  #   flash_lunk_show:
  #     loops: -1
  #     speed: 5
  #     sync_ms: 1500
  mode_intro_rand_mode_started:
    flash_lunk_show:
      action: stop
  mode_annie_mode_started:
    flash_lunk_show:
      action: stop
  mode_intro_rook_mode_started:
    flash_lunk_show:
      action: stop
  mode_intro_genesis_pit_started:
    flash_lunk_show:
      action: stop
  mode_intro_the_fortress_started:
    flash_lunk_show:
      action: stop
  mode_intro_big_apple_started:
    flash_lunk_show:
      action: stop
  mode_intro_corg_mode_started:
    flash_lunk_show:
      action: stop
  # mode_bonus_will_start:
  #   flash_lunk_show:
  #     action: stop

widget_player:
  post_lunk_image:
    lunk_qualify_image:
      action: add
      slide: base_slide
      priority: 1601
  post_lunk_l:
    lunk_l_widget:
      action: add
      slide: base_slide
      priority: 1602
  post_lunk_u:
    lunk_u_widget:
      action: add
      slide: base_slide
      priority: 1603
  post_lunk_n:
    lunk_n_widget:
      action: add
      slide: base_slide
      priority: 1604
  post_lunk_k:
    lunk_k_widget:
      action: add
      slide: base_slide
      priority: 1605

widgets:
  lunk_qualify_image:
    - type: image
      image: lunk_qualify
      x: center + 550
      y: center + 100
  lunk_l_widget:
    - type: text
      text: L
      color: brown
      font_size: 40
      x: center + 520
      y: center + 25
  lunk_u_widget:
    - type: text
      text: U
      color: brown
      font_size: 40
      x: center + 545
      y: center + 25
  lunk_n_widget:
    - type: text
      text: N
      color: brown
      font_size: 40
      x: center + 570
      y: center + 25
  lunk_k_widget:
    - type: text
      text: K
      color: brown
      font_size: 40
      x: center + 595
      y: center + 200

shot_groups:
  lunk_shot_group:
    shots:
      - lunk_shot1
      - lunk_shot2
      - lunk_shot3
    enable_events:
      - mode_skill_shot_stopped
      - mode_rand_mode_stopped
      - mode_annie_mode_stopped
      - mode_rook_mode_stopped
      - mode_corg_mode_stopped
      # - mode_genesis_pit_stopped
      # - mode_the_fortress_stopped
      # - mode_big_apple_stopped
    disable_events:
      - mode_skill_shot_started
      - mode_intro_rand_mode_started
      - mode_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_intro_genesis_pit_started
      - mode_intro_the_fortress_started
      - mode_intro_big_apple_started
      - lunk_shot_group_lit_complete # added 1-13 to test
      - mode_intro_corg_mode_started
    # reset_events:
    #   - lunk_shot_group_lit_complete|1
    restart_events:
      - restart_lunk_shot_group  # added 1-13 to test
    debug: true

shots:
  lunk_shot1:
    switch: s_s_target
    profile: lunk_profile
    show_tokens:
      leds: l_s_led
    debug: true
  lunk_shot2:
    switch: s_d_target
    profile: lunk_profile
    show_tokens:
      leds: l_d_led
    debug: true
  lunk_shot3:
    switch: s_f_target
    profile: lunk_profile
    show_tokens:
      leds: l_f_led
    debug: true

shot_profiles:
  lunk_profile:
    advance_on_hit: true
    block: false #true
    states:
    - name: unlit
      show: off
    - name: lit
      show: color_brown_on

counters:
  lunk_hit_counter:
    count_events:
      - lunk_shot_group_lit_complete
    starting_count: current_player.lunk_start_count
    direction: up
    count_complete_value: 4
    reset_on_complete: false
    events_when_complete: lunk_collected
    persist_state: true

variable_player:
  lunk_collected:
    team_members_collected: 1

sound_player:
  lunk_shot_group_hit:
    sdf_target_sound:
      action: play
  play_lunk_sounds: qualify_lunk_sounds

sound_pools:
  qualify_lunk_sounds:
    type: random_force_all
    track: voice
    sounds:
      - lunk_waiting
      - here_we_go
      - lunk_engineer
