#config_version=5
# config:
# - config_tilt.yaml

# Relay through event_player because widget_player doesn't like conditions/priorities
event_player:
  player_added:
    # Give a small delay to allow the player vars to initialize, lest the placeholder text show goofy
    - add_player_2{num==2}|150ms
    - add_player_3{num==3}|150ms
    - add_player_4{num==4}|150ms
  player_turn_started{game.num_players>1}:
    - multiplayer_turn_start_1{number==1}
    - multiplayer_turn_start_2{number==2}
    - multiplayer_turn_start_3{number==3}
    - multiplayer_turn_start_4{number==4}
  player_turn_ended{game.num_players>1}:
    - multiplayer_turn_end_1{number==1}
    - multiplayer_turn_end_2{number==2}
    - multiplayer_turn_end_3{number==3}
    - multiplayer_turn_end_4{number==4}

show_player:
  ball_will_end:
    turn_off_all_lights:
      action: play
      priority: 9999
  ball_starting:
    turn_off_all_lights:
      action: stop
  # If a second player joins during player1's turn, swap singleplayer_slide for multiplayer_slide
  #multiplayer_game{mode["field"].active and not mode["field"].stopping}: show_multiplayer_slide


# slide_player:
#   show_base_slide:
#     singleplayer_slide{not is_multiplayer}:
#       action: play
#       priority: 1
#     multiplayer_slide{is_multiplayer}:
#       action: play
#       priority: 2
#   show_multiplayer_slide:
#     multiplayer_slide:
#       action: play
#     singleplayer_slide:
#       action: remove
#   ball_will_end:
#     singleplayer_slide:
#       action: remove
#     multiplayer_slide:
#       action: remove

widget_player:
  # First event, before additional players have a chance to enter
  # game_started:
  #   base_score_widget:
  #     slide: base_slide
  #   base_ball_widget:
  #     slide: base_slide
  #   base_screen_outline_widget:
  #     slide: base_slide
    # base_score_outline_widget:
    #   slide: base_slide
  # Player 2 has entered the game, add widgets for player1 and player2
  add_player_2:
    mp_box_widget_2_players_player_1:
      slide: base_slide
      action: add
    mp_box_widget_2_players_player_2:
      slide: base_slide
      action: add
    #Start with player1 name, player2 score 0
    mp_player_widget_2_players_player_1:
      slide: base_slide
      action: add
    mp_score_widget_2_players_player_2:
      slide: base_slide
      action: add
  # Player 3 has entered the game
  add_player_3:
    mp_box_widget_2_players_player_1:
      slide: base_slide
      action: remove
    mp_box_widget_2_players_player_2:
      slide: base_slide
      action: remove
    mp_box_widget_3_players_player_1:
      slide: base_slide
      action: add
    mp_box_widget_3_players_player_2:
      slide: base_slide
      action: add
    mp_box_widget_3_players_player_3:
      slide: base_slide
      action: add
  # Start with player1 name, player2 score 0, player3 score 0
    mp_player_widget_2_players_player_1:
      slide: base_slide
      action: remove
    mp_score_widget_2_players_player_2:
      slide: base_slide
      action: remove
    mp_player_widget_3_players_player_1:
      slide: base_slide
      action: add
    mp_score_widget_3_players_player_2:
      slide: base_slide
      action: add
    mp_score_widget_3_players_player_3:
      slide: base_slide
      action: add
  # Player 4 has entered the game
  add_player_4:
    mp_box_widget_3_players_player_1:
      slide: base_slide
      action: remove
    mp_box_widget_3_players_player_2:
      slide: base_slide
      action: remove
    mp_box_widget_3_players_player_3:
      slide: base_slide
      action: remove
    mp_box_widget_4_players_player_1:
      slide: base_slide
      action: add
    mp_box_widget_4_players_player_2:
      slide: base_slide
      action: add
    mp_box_widget_4_players_player_3:
      slide: base_slide
      action: add
    mp_box_widget_4_players_player_4:
      slide: base_slide
      action: add
  # Start with player1 name, player2 score 0, player3 score 0, player 4 score 0
    mp_player_widget_3_players_player_1:
      slide: base_slide
      action: remove
    mp_score_widget_3_players_player_2:
      slide: base_slide
      action: remove
    mp_score_widget_3_players_player_3:
      slide: base_slide
      action: remove
    mp_player_widget_4_players_player_1:
      slide: base_slide
      action: add
    mp_score_widget_4_players_player_2:
      slide: base_slide
      action: add
    mp_score_widget_4_players_player_3:
      slide: base_slide
      action: add
    mp_score_widget_4_players_player_4:
      slide: base_slide
      action: add
  # Player Turns: Swap scores -> names when turn starts, revert when turn ends
  multiplayer_turn_start_1{game.num_players==2}:
    mp_player_widget_2_players_player_1:
      action: add
      slide: base_slide
    mp_score_widget_2_players_player_2:
      action: add
      slide: base_slide
  multiplayer_turn_end_1{game.num_players==2}:
    mp_player_widget_2_players_player_1:
      action: remove
    mp_score_widget_2_players_player_2:
      action: remove
  multiplayer_turn_start_2{game.num_players==2}:
    mp_player_widget_2_players_player_2:
      action: add
      slide: base_slide
    mp_score_widget_2_players_player_1:
      action: add
      slide: base_slide
  multiplayer_turn_end_2{game.num_players==2}:
    mp_player_widget_2_players_player_2:
      action: remove
    mp_score_widget_2_players_player_1:
      action: remove
# 3 players
  multiplayer_turn_start_1{game.num_players==3}:
    mp_player_widget_3_players_player_1:
      action: add
      slide: base_slide
    mp_score_widget_3_players_player_3:
      action: add
      slide: base_slide
  multiplayer_turn_end_1{game.num_players==3}:
    mp_player_widget_3_players_player_1:
      action: remove
    mp_score_widget_3_players_player_2:
      action: remove
  multiplayer_turn_start_2{game.num_players==3}:
    mp_player_widget_3_players_player_2:
      action: add
      slide: base_slide
    mp_score_widget_3_players_player_1:
      action: add
      slide: base_slide
  multiplayer_turn_end_2{game.num_players==3}:
    mp_player_widget_3_players_player_2:
      action: remove
    mp_score_widget_3_players_player_3:
      action: remove
  multiplayer_turn_start_3{game.num_players==3}:
    mp_score_widget_3_players_player_2:
      action: add
      slide: base_slide
    mp_player_widget_3_players_player_3:
      action: add
      slide: base_slide
  multiplayer_turn_end_3{game.num_players==3}:
    mp_score_widget_3_players_player_1:
      action: remove
      slide: base_slide
    mp_player_widget_3_players_player_3:
      action: remove
      slide: base_slide
# 4 players
  multiplayer_turn_start_1{game.num_players==4}:
    mp_player_widget_4_players_player_1:
      action: add
      slide: base_slide
    mp_score_widget_4_players_player_4:
      action: add
      slide: base_slide
  multiplayer_turn_end_1{game.num_players==4}:
    mp_player_widget_4_players_player_1:
      action: remove
    mp_score_widget_4_players_player_2:
      action: remove
  multiplayer_turn_start_2{game.num_players==4}:
    mp_player_widget_4_players_player_2:
      action: add
      slide: base_slide
    mp_score_widget_4_players_player_1:
      action: add
      slide: base_slide
  multiplayer_turn_end_2{game.num_players==4}:
    mp_player_widget_4_players_player_2:
      action: remove
    mp_score_widget_4_players_player_3:
      action: remove
  multiplayer_turn_start_3{game.num_players==4}:
    mp_score_widget_4_players_player_2:
      action: add
      slide: base_slide
    mp_player_widget_4_players_player_3:
      action: add
      slide: base_slide
  multiplayer_turn_end_3{game.num_players==4}:
    mp_player_widget_4_players_player_3:
      action: remove
      slide: base_slide
    mp_score_widget_4_players_player_4:
      action: remove
      slide: base_slide
  multiplayer_turn_start_4{game.num_players==4}:
    mp_score_widget_4_players_player_3:
      action: add
      slide: base_slide
    mp_player_widget_4_players_player_4:
      action: add
      slide: base_slide
  multiplayer_turn_end_4{game.num_players==4}:
    mp_player_widget_4_players_player_4:
      action: remove
      slide: base_slide
    mp_score_widget_4_players_player_1:
      action: remove
      slide: base_slide

slides:
  base_slide: []

# slide_player:
  #commented out 8-13
  # game_started:
  #   base_slide
  # game_ended:
  #   base_slide:
  #     action: remove
  # single_player_ball_started:
  #   base_slide
  # ball_started:
  #   base_slide
  # multi_player_ball_started: multiplayer_slide
  # multiplayer_game:
  #   base_slide:
  #     action: remove
  #   multiplayer_slide:
  #     action: play
  # ball_will_end:
  #   base_slide:
  #     action: remove
  #   multiplayer_slide:
  #     action: play

# slides:
#   singleplayer_slide:
#     widgets:
#       - type: text
#         text: (score)
#         style: score_style_singleplayer
#   multiplayer_slide:
#     widgets:
#       - type: text
#         text: (score)
#         style: score_style_multiplayer

widgets:
  # #commented out 8-13
  # base_screen_outline_widget:
  #   - type: line
  #     points: 10, 20, 10, 700, 1270, 700, 1270, 20, 10, 20
  #     thickness: 3
  #     color: red
  # base_score_widget:
  #   - type: text
  #     text: (score)
  #     style: score_style_singleplayer
  #     x: center
  #     y: center-225
    # - type: text
    #   text: PLAYER (number)
    #   y: 10
    #   x: 10
    #   font_size: 50
    #   anchor_x: left
    #   anchor_y: bottom
    #   color: white
  # base_score_outline_widget:
  #   - type: line
  #     points: 440, 95, 440, 155, 840, 155, 840, 95, 440, 95
  #     thickness: 2
  #     color: red
  # base_ball_widget:
  #   - type: line
  #     points: 580, 700, 580, 650, 700, 650, 700, 700
  #     thickness: 2
  #     color: red
  #   - type: text
  #     text: BALL (ball)
  #     y: top - 45
  #     x: center
  #     font_size: 30
  #     color: white
  mp_box_widget_2_players_player_1:
    - type: line
      points: 440, 30, 440, 70, 640, 70, 640, 30, 440, 30
      thickness: 2
      color: red
  mp_box_widget_2_players_player_2:
    - type: line
      points: 640, 70, 840, 70, 840, 30, 640, 30
      thickness: 2
      color: red
  mp_box_widget_3_players_player_1:
    - type: line
      points: 340, 30, 340, 70, 540, 70, 540, 30, 340, 30
      thickness: 2
      color: red
  mp_box_widget_3_players_player_2:
    - type: line
      points: 540, 70, 740, 70, 740, 30, 540, 30
      thickness: 2
      color: red
  mp_box_widget_3_players_player_3:
    - type: line
      points: 740, 70, 940, 70, 940, 30, 740, 30
      thickness: 2
      color: red
  mp_box_widget_4_players_player_1:
    - type: line
      points: 240, 30, 240, 70, 440, 70, 440, 30, 240, 30
      thickness: 2
      color: red
  mp_box_widget_4_players_player_2:
    - type: line
      points: 440, 70, 640, 70, 640, 30, 440, 30
      thickness: 2
      color: red
  mp_box_widget_4_players_player_3:
    - type: line
      points: 640, 70, 840, 70, 840, 30, 640, 30
      thickness: 2
      color: red
  mp_box_widget_4_players_player_4:
    - type: line
      points: 840, 70, 1040, 70, 1040, 30, 840, 30
      thickness: 2
      color: red
  mp_player_widget_2_players_player_1:
    - type: text
      text: PLAYER (number)
      x: 490
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_player_widget_2_players_player_2:
    - type: text
      text: PLAYER (number)
      x: 690
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_player_widget_3_players_player_1:
    - type: text
      text: PLAYER (number)
      x: 390
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_player_widget_3_players_player_2:
    - type: text
      text: PLAYER (number)
      x: 590
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_player_widget_3_players_player_3:
    - type: text
      text: PLAYER (number)
      x: 790
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_score_widget_2_players_player_1:
    - type: text
      text: (player1|score)
      x: 540
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true
  mp_score_widget_2_players_player_2:
    - type: text
      text: (player2|score)
      x: 740
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true
  mp_score_widget_3_players_player_1:
    - type: text
      text: (player1|score)
      x: 440
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true
  mp_score_widget_3_players_player_2:
    - type: text
      text: (player2|score)
      x: 640
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true
  mp_score_widget_3_players_player_3:
    - type: text
      text: (player3|score)
      x: 840
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true
  mp_player_widget_4_players_player_1:
    - type: text
      text: PLAYER (number)
      x: 290
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_player_widget_4_players_player_2:
    - type: text
      text: PLAYER (number)
      x: 490
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_player_widget_4_players_player_3:
    - type: text
      text: PLAYER (number)
      x: 690
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_player_widget_4_players_player_4:
    - type: text
      text: PLAYER (number)
      x: 890
      y: 35
      font_size: 30
      anchor_x: left
      anchor_y: bottom
      color: white
  mp_score_widget_4_players_player_1:
    - type: text
      text: (player1|score)
      x: 340
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true
  mp_score_widget_4_players_player_2:
    - type: text
      text: (player2|score)
      x: 540
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true
  mp_score_widget_4_players_player_3:
    - type: text
      text: (player3|score)
      x: 740
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true
  mp_score_widget_4_players_player_4:
    - type: text
      text: (player4|score)
      x: 940
      y: 55
      font_size: 30
      # anchor_x: left
      # anchor_y: bottom
      color: red
      number_grouping: true

variable_player:
  game_will_end:
    last_game_num_players:
      action: set_machine
      int: game.num_players
    last_game_player1_combos_made:
      action: set_machine
      int: players[0].combos_made
    last_game_player2_combos_made:
      action: set_machine
      int: players[1].combos_made
    last_game_player3_combos_made:
      action: set_machine
      int: players[3].combos_made
    last_game_player4_combos_made:
      action: set_machine
      int: players[3].combos_made
    last_game_player1_skill_shots_made:
      action: set_machine
      int: players[0].skill_shots_made
    last_game_player2_skill_shots_made:
      action: set_machine
      int: players[1].skill_shots_made
    last_game_player3_skill_shots_made:
      action: set_machine
      int: players[2].skill_shots_made
    last_game_player4_skill_shots_made:
      action: set_machine
      int: players[3].skill_shots_made
    last_game_player1_protoculture:
      action: set_machine
      int: players[0].protoculture_count
    last_game_player2_protoculture:
      action: set_machine
      int: players[1].protoculture_count
    last_game_player3_protoculture:
      action: set_machine
      int: players[2].protoculture_count
    last_game_player4_protoculture:
      action: set_machine
      int: players[3].protoculture_count
