#config_version=5
#Robotech

mode:
    start_events:
      - mode_intro_corg_mode_stopped
    stop_events:
      - ball_save_corg_mode_ball_save_disabled
    priority: 9675

ball_saves:
  corg_mode_ball_save:
    active_time: 15s
    hurry_up_time: 5s
    grace_period: 5s
    timer_start_events:
      - mode_ball_save_corg_mode_started
    auto_launch: true
    balls_to_save: -1
    debug: true

show_player:
  ball_save_corg_mode_ball_save_timer_start:
    fast_flash_show:
      key: corg_mode_save_flash
      speed: 3
      show_tokens:
        leds: l_shoot_again
        color: blue
      action: play
  ball_save_corg_mode_ball_save_hurry_up:
    corg_mode_save_flash:
      action: stop
    fast_flash_show:
      key: corg_mode_hurry_up_flash
      action: play
      speed: 20
      show_tokens:
        leds: l_shoot_again
        color: blue
  ball_save_corg_mode_ball_save_grace_period:
    corg_mode_hurry_up_flash:
      action: stop
