#config_version=5

mode:
   start_events:
     - mode_invid_invasion_stopped #(testing) - ball_starting{current_player.ball==1 and not is_extra_ball} (testing)
     - mode_genesis_pit_stopped
     - mode_the_fortress_stopped
   stop_events:
     - mode_qualified
   restart_on_next_ball: true
   priority: 420

timers:
  check_pre_qualify_a_mode_drop_targets_up_timer:
    debug: True
    start_value: 0
    end_value: 2
    direction: up
    tick_interval: 1s
    control_events:
      - action: start
        event: start_check_pre_qualify_a_mode_drop_targets_up_timer

event_player:
  mode_pre_qualify_a_mode_started:
    - drop_reset_up
    - start_check_pre_qualify_a_mode_drop_targets_up_timer
  mode_rand_mode_stopped:
    - drop_reset_up
    - start_check_pre_qualify_a_mode_drop_targets_up_timer
  mode_annie_mode_stopped:
    - drop_reset_up
    - start_check_pre_qualify_a_mode_drop_targets_up_timer
  mode_rook_mode_stopped:
    - drop_reset_up
    - start_check_pre_qualify_a_mode_drop_targets_up_timer
  mode_lunk_mode_stopped:
    - drop_reset_up
    - start_check_pre_qualify_a_mode_drop_targets_up_timer
  timer_check_pre_qualify_a_mode_drop_targets_up_timer_complete.1{device.switches.s_left_drop_target.state == 1 or device.switches.s_middle_drop_target.state == 1 or device.switches.s_right_drop_target.state == 1}:
    - drop_reset_up
    - enable_pre_qualify_a_mode_drop_targets|.5s
  timer_check_pre_qualify_a_mode_drop_targets_up_timer_complete.2{device.switches.s_left_drop_target.state == 0 and device.switches.s_middle_drop_target.state == 0 and device.switches.s_right_drop_target.state == 0}:
    - enable_pre_qualify_a_mode_drop_targets
  pre_qualify_a_mode_invid_target_group_hit_complete:
    - start_hurry_up_mode_start_ramp
    - mode_qualified

# counters:
#   pre_qualify_a_mode_invid_target_group_made:
#     count_events: pre_qualify_a_mode_invid_target_group_hit_complete
#     starting_count: 0
#     direction: up
#     persist_state: true
#     debug: true

shot_groups:
  pre_qualify_a_mode_invid_target_group:
    shots:
      - pre_qualify_a_mode_left_target
      - pre_qualify_a_mode_middle_target
      - pre_qualify_a_mode_right_target
      - pre_qualify_a_mode_left_drop
      - pre_qualify_a_mode_middle_drop
      - pre_qualify_a_mode_right_drop
    enable_events:
      - enable_pre_qualify_a_mode_drop_targets
    disable_events:
      - mode_intro_rand_mode_started
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
    reset_events: mode_qualified
    debug: true

show_player:
  pre_qualify_a_mode_invid_target_group_hit_complete:
    invid_targets_complete:
      show_tokens:
        color: red

shot_profiles:
  pre_qualify_a_mode_invid_profile:
    show_when_disabled: false
    states:
      - name: flashing
        show: flash_red_show
        speed: 5
        sync_ms: 1500
      - name: hit
        show: color_red_on

shots:
  pre_qualify_a_mode_left_target:
    switch: s_left_target
    profile: pre_qualify_a_mode_invid_profile
    show_tokens:
      leds: l_t1
    debug: true
  pre_qualify_a_mode_middle_target:
    switch: s_middle_target
    profile: pre_qualify_a_mode_invid_profile
    show_tokens:
      leds: l_t2
    debug: true
  pre_qualify_a_mode_right_target:
    switch: s_right_target
    profile: pre_qualify_a_mode_invid_profile
    show_tokens:
      leds: l_t3
    debug: true
  pre_qualify_a_mode_left_drop:
    switch: s_left_drop_target
    profile: pre_qualify_a_mode_invid_profile
    show_tokens:
      leds: l_t4
    debug: true
  pre_qualify_a_mode_middle_drop:
    switch: s_middle_drop_target
    profile: pre_qualify_a_mode_invid_profile
    show_tokens:
      leds: l_t5
    debug: True
  pre_qualify_a_mode_right_drop:
    switch: s_right_drop_target
    profile: pre_qualify_a_mode_invid_profile
    show_tokens:
      leds: l_t6
    debug: true

variable_player:
  pre_qualify_a_mode_invid_target_group_flashing_hit:
    score: 1000 * current_player.pf_multiplier|block

# sound_player:
#   invid_target_group_flashing_hit:
#     spinner_sound4:
#       action: play
