#config_version=5

mode:
  start_events:
    - mode_skill_shot_starting
    #- start_combo_timer
  stop_events:
    - timer_skill_shot_combo_timer_complete
    - skill_shot_combo_made
    - skill_shot_missed
  stop_on_ball_end: true
  priority: 2000

event_player:
  # Super Skill Shot combos
  skill_shot_super_skill_shot_rand_combo_hit:
    - skill_shot_combo_made
  skill_shot_super_skill_shot_annie_combo_hit:
    - skill_shot_combo_made
  skill_shot_super_skill_shot_rook_combo_hit:
    - skill_shot_combo_made
  skill_shot_super_skill_shot_lancer_combo_hit:
    - skill_shot_combo_made
  skill_shot_super_skill_shot_lunk_combo_hit:
    - skill_shot_combo_made
  # Invid Skill Shot combos
  skill_shot_invid_rook_combo_hit:
    - skill_shot_combo_made
  skill_shot_invid_rand_combo_hit:
    - skill_shot_combo_made
  skill_shot_invid_annie_combo_hit:
    - skill_shot_combo_made
  skill_shot_invid_lancer_combo_hit:
    - skill_shot_combo_made
  skill_shot_invid_lunk_combo_hit:
    - skill_shot_combo_made
  # Rand Skill Shot combos
  skill_shot_rand_rook_combo_hit:
    - skill_shot_combo_made
  skill_shot_rand_lancer_combo_hit:
    - skill_shot_combo_made
  skill_shot_rand_lunk_combo_hit:
    - skill_shot_combo_made
  skill_shot_rand_annie_combo_hit:
    - skill_shot_combo_made
  # Rook Skill Shot combos
  skill_shot_rook_rand_combo_hit:
    - skill_shot_combo_made
  skill_shot_rook_annie_combo_hit:
    - skill_shot_combo_made
  skill_shot_rook_lancer_combo_hit:
    - skill_shot_combo_made
  skill_shot_rook_lunk_combo_hit:
    - skill_shot_combo_made
  # Top Lanes Skill Shot combos
  skill_shot_top_lanes_rand_combo_hit:
    - skill_shot_combo_made
  skill_shot_top_lanes_annie_combo_hit:
    - skill_shot_combo_made
  skill_shot_top_lanes_rook_combo_hit:
    - skill_shot_combo_made
  skill_shot_top_lanes_lancer_combo_hit:
    - skill_shot_combo_made
  skill_shot_top_lanes_lunk_combo_hit:
    - skill_shot_combo_made
  # SDF targets Skill Shot combos
  skill_shot_sdf_targets_rand_combo_hit:
    - skill_shot_combo_made
  skill_shot_sdf_targets_annie_combo_hit:
    - skill_shot_combo_made
  skill_shot_sdf_targets_rook_combo_hit:
    - skill_shot_combo_made
  skill_shot_sdf_targets_lancer_combo_hit:
    - skill_shot_combo_made
  # Secret Skill Shot combos
  skill_shot_secret_skill_shot_rand_combo_hit:
    - skill_shot_combo_made
  skill_shot_secret_skill_shot_annie_combo_hit:
    - skill_shot_combo_made
  skill_shot_secret_skill_shot_rook_combo_hit:
    - skill_shot_combo_made
  skill_shot_secret_skill_shot_lancer_combo_hit:
    - skill_shot_combo_made
  skill_shot_secret_skill_shot_lunk_combo_hit:
    - skill_shot_combo_made
  # Top Saucer Skill Shot combos
  skill_shot_top_saucer_rand_combo_hit:
    - skill_shot_combo_made
  skill_shot_top_saucer_annie_combo_hit:
    - skill_shot_combo_made
  skill_shot_top_saucer_rook_combo_hit:
    - skill_shot_combo_made
  skill_shot_top_saucer_lancer_combo_hit:
    - skill_shot_combo_made
  skill_shot_top_saucer_lunk_combo_hit:
    - skill_shot_combo_made

sequence_shots:
  # Super Skill Shot combos
  skill_shot_super_skill_shot_rand_combo:
    event_sequence:
      - super_skill_sequence_hit
      - rand_combo_shot_hit
  skill_shot_super_skill_shot_annie_combo:
    event_sequence:
      - super_skill_sequence_hit
      - annie_combo_shot_hit
  skill_shot_super_skill_shot_rook_combo:
    event_sequence:
      - super_skill_sequence_hit
      - rook_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_super_skill_shot_lancer_combo:
    event_sequence:
      - super_skill_sequence_hit
      - lancer_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_super_skill_shot_lunk_combo:
    event_sequence:
      - super_skill_sequence_hit
      - lunk_combo_shot_hit
    #sequence_timeout: 5s
  # Invid Skill Shot combos
  skill_shot_invid_rook_combo:
    event_sequence:
      - invid_targets_skill_flashing_hit
      - rook_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_invid_rand_combo:
    event_sequence:
      - invid_targets_skill_flashing_hit
      - rand_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_invid_annie_combo:
    event_sequence:
      - invid_targets_skill_flashing_hit
      - annie_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_invid_lancer_combo:
    event_sequence:
      - invid_targets_skill_flashing_hit
      - lancer_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_invid_lunk_combo:
    event_sequence:
      - invid_targets_skill_flashing_hit
      - lunk_combo_shot_hit
    #sequence_timeout: 5s
  # Rand Skill Shot combos
  skill_shot_rand_rook_combo:
    event_sequence:
      - left_saucer_skill_saucer_targets_skill_flashing_hit
      - rook_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_rand_lancer_combo:
    event_sequence:
      - left_saucer_skill_saucer_targets_skill_flashing_hit
      - lancer_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_rand_lunk_combo:
    event_sequence:
      - left_saucer_skill_saucer_targets_skill_flashing_hit
      - lunk_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_rand_annie_combo:
    event_sequence:
      - left_saucer_skill_saucer_targets_skill_flashing_hit
      - annie_combo_shot_hit
    #sequence_timeout: 5s
  # Rook Skill Shot combos
  skill_shot_rook_rand_combo:
    event_sequence:
      - right_saucer_skill_saucer_targets_skill_flashing_hit
      - rand_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_rook_annie_combo:
    event_sequence:
      - right_saucer_skill_saucer_targets_skill_flashing_hit
      - annie_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_rook_lancer_combo:
    event_sequence:
      - right_saucer_skill_saucer_targets_skill_flashing_hit
      - lancer_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_rook_lunk_combo:
    event_sequence:
      - right_saucer_skill_saucer_targets_skill_flashing_hit
      - lunk_combo_shot_hit
    #sequence_timeout: 5s
  # Top Lanes Skill Shot combos
  skill_shot_top_lanes_rand_combo:
    event_sequence:
      - top_lanes_skill_flashing_hit
      - rand_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_top_lanes_annie_combo:
    event_sequence:
      - top_lanes_skill_flashing_hit
      - annie_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_top_lanes_rook_combo:
    event_sequence:
      - top_lanes_skill_flashing_hit
      - rook_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_top_lanes_lancer_combo:
    event_sequence:
      - top_lanes_skill_flashing_hit
      - lancer_combo_shot_hit
  skill_shot_top_lanes_lunk_combo:
    event_sequence:
      - top_lanes_skill_flashing_hit
      - lunk_combo_shot_hit
    #sequence_timeout: 5s
  # SDF targets Skill Shot combos
  skill_shot_sdf_targets_rand_combo:
    event_sequence:
      - sdf_skill_group_flashing_hit
      - rand_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_sdf_targets_annie_combo:
    event_sequence:
      - sdf_skill_group_flashing_hit
      - annie_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_sdf_targets_rook_combo:
    event_sequence:
      - sdf_skill_group_flashing_hit
      - rook_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_sdf_targets_lancer_combo:
    event_sequence:
      - sdf_skill_group_flashing_hit
      - lancer_combo_shot_hit
    #sequence_timeout: 5s
  # Secret Skill Shot combos
  skill_shot_secret_skill_shot_rand_combo:
    event_sequence:
      - secret_skill_shot_flashing_hit
      - rand_combo_shot_hit
  skill_shot_secret_skill_shot_annie_combo:
    event_sequence:
      - secret_skill_shot_flashing_hit
      - annie_combo_shot_hit
  skill_shot_secret_skill_shot_rook_combo:
    event_sequence:
      - secret_skill_shot_flashing_hit
      - rook_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_secret_skill_shot_lancer_combo:
    event_sequence:
      - secret_skill_shot_flashing_hit
      - lancer_combo_shot_hit
    #sequence_timeout: 5s
  skill_shot_secret_skill_shot_lunk_combo:
    event_sequence:
      - secret_skill_shot_flashing_hit
      - lunk_combo_shot_hit
  # Top Saucer Shot combos
  skill_shot_top_saucer_rand_combo:
    event_sequence:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - rand_combo_shot_hit
  skill_shot_top_saucer_annie_combo:
    event_sequence:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - annie_combo_shot_hit
  skill_shot_top_saucer_rook_combo:
    event_sequence:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - rook_combo_shot_hit
  skill_shot_top_saucer_lancer_combo:
    event_sequence:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - lancer_combo_shot_hit
  skill_shot_top_saucer_lunk_combo:
    event_sequence:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - lunk_combo_shot_hit
  lancer_shot_combo_sequence:
    switch_sequence:
      - s_spinner
      - s_gate_top_right
    sequence_timeout: 2s

shots:
  rand_combo_shot:
    switch: s_left_lock_kickout
    profile: combo_profile
    enable_events:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - super_skill_sequence_hit
      - invid_targets_skill_flashing_hit
      - right_saucer_skill_saucer_targets_skill_flashing_hit
      - top_lanes_skill_flashing_hit
      - sdf_skill_group_flashing_hit
      - secret_skill_shot_flashing_hit
    disable_events:
      - mode_skill_shot_starting
      - mode_skill_shot_combo_stopping
      - skill_shot_combo_made
    show_tokens:
      leds: l_llock_arrow
    debug: true
    reset_events: rand_combo_shot_flashing_combo_hit
  annie_combo_shot:
    switch: s_left_orbit
    profile: combo_profile
    enable_events:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - super_skill_sequence_hit
      - invid_targets_skill_flashing_hit
      - left_saucer_skill_saucer_targets_skill_flashing_hit
      - right_saucer_skill_saucer_targets_skill_flashing_hit
      - top_lanes_skill_flashing_hit
      - sdf_skill_group_flashing_hit
      - secret_skill_shot_flashing_hit
    disable_events:
      - mode_skill_shot_starting
      - mode_skill_shot_combo_stopping
      - skill_shot_combo_made
    show_tokens:
      leds: l_annie_arrow
    debug: true
    reset_events: annie_combo_shot_flashing_combo_hit
  rook_combo_shot:
    switch: s_right_lock_kickout
    profile: combo_profile
    enable_events:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - super_skill_shot_flashing_hit #super_skill_sequence_hit
      - left_saucer_skill_saucer_targets_skill_flashing_hit
      - invid_targets_skill_flashing_hit
      - top_lanes_skill_flashing_hit
      - sdf_skill_group_flashing_hit
      - secret_skill_shot_flashing_hit
    disable_events:
      - mode_skill_shot_starting
      - mode_skill_shot_combo_stopping
      - skill_shot_combo_made
    show_tokens:
      leds: l_rlock_arrow
    debug: true
    reset_events: rook_combo_shot_flashing_combo_hit
  lancer_combo_shot:
    hit_events: lancer_shot_combo_sequence_hit
    profile: combo_profile
    enable_events:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      #- super_skill_sequence_hit
      - left_saucer_skill_saucer_targets_skill_flashing_hit
      - invid_targets_skill_flashing_hit
      - right_saucer_skill_saucer_targets_skill_flashing_hit
      - top_lanes_skill_flashing_hit
      - sdf_skill_group_flashing_hit
      - secret_skill_shot_flashing_hit
    disable_events:
      - mode_skill_shot_starting
      - mode_skill_shot_combo_stopping
      - skill_shot_combo_made
    show_tokens:
      leds: l_right_orbit_arrow
    debug: true
    reset_events: lancer_combo_shot_flashing_combo_hit
  lunk_combo_shot:
    switch: s_d_target
    profile: combo_profile
    enable_events:
      - top_saucer_skill_saucer_targets_skill_flashing_hit
      - super_skill_sequence_hit
      - left_saucer_skill_saucer_targets_skill_flashing_hit
      - invid_targets_skill_flashing_hit
      - right_saucer_skill_saucer_targets_skill_flashing_hit
      - top_lanes_skill_flashing_hit
      - secret_skill_shot_flashing_hit
    disable_events:
      - mode_skill_shot_starting
      - mode_skill_shot_combo_stopping
      - skill_shot_combo_made
    show_tokens:
      leds: l_sdf_arrow_led
    debug: true
    reset_events: lunk_combo_shot_flashing_combo_hit

shot_profiles:
  combo_profile:
    advance_on_hit: true
    show_when_disabled: false
    states:
    - name: flashing_combo
      show: flash_blue_show
      loops: -1
      speed: 10
    - name: hit
      show: off

timers:
  skill_shot_combo_timer:
    debug: true
    start_value: 5
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: start_combo_timer #skill_shot_made
      - action: add
        event: top_saucer_skill_saucer_targets_skill_flashing_hit
        value: 3
      - action: add
        event: top_lanes_skill_flashing_hit
        value: 2

variable_player:
  skill_shot_combo_made:
    combo_value:
      int: 10000 + (current_player.combos_made * 1250)
      action: set
    score: 10000 + (current_player.combos_made * 1250)
    combos_made: 1

sound_player:
  skill_shot_combo_made:
    combo:
      action: play
