#config_version=5

mode:
  start_events:
    - mode_invid_invasion_stopped #mode_end_invid_invasion_stopped
  stop_events:
    - rand_collected
  restart_on_next_ball: true
  priority: 1200

event_player:
  mode_skill_shot_stopped.1:
    - post_rand_image
  mode_skill_shot_stopped.2{device.counters.rand_hit_counter.value==1}:
    - post_rand_r
  mode_skill_shot_stopped.3{device.counters.rand_hit_counter.value==2}:
    - post_rand_r
    - post_rand_a
  mode_skill_shot_stopped.4{device.counters.rand_hit_counter.value==3}:
    - post_rand_r
    - post_rand_a
    - post_rand_n
  r_shot_flashing_rand_hit:
    - post_rand_r
  ra_shot_flashing_rand_hit:
    - post_rand_a
  ran_shot_flashing_rand_hit:
    - post_rand_n
  rand_shot_flashing_rand_hit:
    - post_rand_d

widget_player:
  post_rand_image:
    rand_qualify_image:
      action: add
      slide: base_slide
      priority: 1201
  post_rand_r:
    rand_r_widget:
      action: add
      slide: base_slide
      priority: 1202
  post_rand_a:
    rand_a_widget:
      action: add
      slide: base_slide
      priority: 1203
  post_rand_n:
    rand_n_widget:
      action: add
      slide: base_slide
      priority: 1204
  post_rand_d:
    rand_d_widget:
      action: add
      slide: base_slide
      priority: 1205

widgets:
  rand_qualify_image:
    - type: image
      image: rand_qualify
      x: center - 560
      y: center + 275
  rand_r_widget:
    - type: text
      text: R
      color: red
      font_size: 35
      x: center - 595
      y: center + 200
  rand_a_widget:
    - type: text
      text: A
      color: red
      font_size: 35
      x: center - 575
      y: center + 200
  rand_n_widget:
    - type: text
      text: N
      color: red
      font_size: 35
      x: center - 555
      y: center + 200
  rand_d_widget:
    - type: text
      text: D
      color: red
      font_size: 35
      x: center - 535
      y: center + 200

shot_groups:
  rand_shot_group:
    shots:
      - r_shot
      - ra_shot
      - ran_shot
      - rand_shot
    debug: true

shots:
  r_shot:
    switch: s_left_lock_kickout
    profile: rand_profile
    enable_events:
      - mode_annie_mode_stopped{device.counters.rand_hit_counter.value==0}
      - mode_rook_mode_stopped{device.counters.rand_hit_counter.value==0}
      - mode_lunk_mode_stopped{device.counters.rand_hit_counter.value==0}
      - mode_skill_shot_stopped{device.counters.rand_hit_counter.value==0}
      - mode_corg_mode_stopped{device.counters.rand_hit_counter.value==0}
      # - mode_genesis_pit_stopped{device.counters.rand_hit_counter.value==0}
      # - mode_the_fortress_stopped{device.counters.rand_hit_counter.value==0}
      # - mode_big_apple_stopped{device.counters.rand_hit_counter.value==0}
    disable_events:
      - r_shot_flashing_rand_hit
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
      - mode_intro_genesis_pit_started
      - mode_intro_the_fortress_started
      - mode_intro_big_apple_started
      - mode_intro_corg_mode_started
    debug: true
  ra_shot:
    switch: s_left_lock_kickout
    profile: rand_profile
    enable_events:
      - r_shot_flashing_rand_hit
      - mode_annie_mode_stopped{device.counters.rand_hit_counter.value==1}
      - mode_rook_mode_stopped{device.counters.rand_hit_counter.value==1}
      - mode_lunk_mode_stopped{device.counters.rand_hit_counter.value==1}
      - mode_skill_shot_stopped{device.counters.rand_hit_counter.value==1}
      - mode_corg_mode_stopped{device.counters.rand_hit_counter.value==1}
      # - mode_genesis_pit_stopped{device.counters.rand_hit_counter.value==1}
      # - mode_the_fortress_stopped{device.counters.rand_hit_counter.value==1}
      # - mode_big_apple_stopped{device.counters.rand_hit_counter.value==1}
    disable_events:
      - ra_shot_flashing_rand_hit
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
      - mode_intro_genesis_pit_started
      - mode_intro_the_fortress_started
      - mode_intro_big_apple_started
      - mode_intro_corg_mode_started
    debug: true
  ran_shot:
    switch: s_left_lock_kickout
    profile: rand_profile
    enable_events:
      - ra_shot_flashing_rand_hit
      - mode_annie_mode_stopped{device.counters.rand_hit_counter.value==2}
      - mode_rook_mode_stopped{device.counters.rand_hit_counter.value==2}
      - mode_lunk_mode_stopped{device.counters.rand_hit_counter.value==2}
      - mode_skill_shot_stopped{device.counters.rand_hit_counter.value==2}
      - mode_corg_mode_stopped{device.counters.rand_hit_counter.value==2}
      # - mode_genesis_pit_stopped{device.counters.rand_hit_counter.value==2}
      # - mode_the_fortress_stopped{device.counters.rand_hit_counter.value==2}
      # - mode_big_apple_stopped{device.counters.rand_hit_counter.value==2}
    disable_events:
      - ran_shot_flashing_rand_hit
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
      - mode_intro_genesis_pit_started
      - mode_intro_the_fortress_started
      - mode_intro_big_apple_started
      - mode_intro_corg_mode_started
    debug: true
  rand_shot:
    switch: s_left_lock_kickout
    profile: rand_profile
    enable_events:
      - ran_shot_flashing_rand_hit
      - mode_annie_mode_stopped{device.counters.rand_hit_counter.value==3}
      - mode_rook_mode_stopped{device.counters.rand_hit_counter.value==3}
      - mode_lunk_mode_stopped{device.counters.rand_hit_counter.value==3}
      - mode_skill_shot_stopped{device.counters.rand_hit_counter.value==3}
      - mode_corg_mode_stopped{device.counters.rand_hit_counter.value==3}
      # - mode_genesis_pit_stopped{device.counters.rand_hit_counter.value==3}
      # - mode_the_fortress_stopped{device.counters.rand_hit_counter.value==3}
      # - mode_big_apple_stopped{device.counters.rand_hit_counter.value==3}
    disable_events:
      - rand_shot_flashing_rand_hit
      - mode_intro_annie_mode_started
      - mode_intro_rook_mode_started
      - mode_lunk_mode_started
      - mode_skill_shot_started
      - mode_intro_genesis_pit_started
      - mode_intro_the_fortress_started
      - mode_intro_big_apple_started
      - mode_intro_corg_mode_started
    debug: true


shot_profiles:
  rand_profile:
    advance_on_hit: true #false
    states:
    # - name: unlit
    #   show: off
    - name: flashing_rand
      show: flash_rand_show
      sync_ms: 1500
      loops: -1
      speed: 5
    - name: hit
      show: off

counters:

  rand_hit_counter:
    count_events:
      - rand_shot_group_flashing_rand_hit
    starting_count: current_player.rand_start_count
    direction: up
    count_complete_value: 4
    reset_on_complete: false
    events_when_complete: rand_collected
    persist_state: true
    debug: true

variable_player:
  rand_collected:
    team_members_collected: 1
