#config_version=5

mode:
  start_events:
    - start_qualify_rand
  stop_events:
    - rand_collected
  restart_on_next_ball: true
  priority: 1200

event_player:
  mode_qualify_rand_started{device.counters.rand_hit_counter.value==1}:
    - post_rand_r
  mode_qualify_rand_started{device.counters.rand_hit_counter.value==2}:
    - post_rand_r
    - post_rand_a
  mode_qualify_rand_started{device.counters.rand_hit_counter.value==3}:
    - post_rand_r
    - post_rand_a
    - post_rand_n
  r_shot_flashing_rand_hit:
    - post_rand_r
  ra_shot_flashing_rand_hit:
    - post_rand_a
  ran_shot_flashing_rand_hit:
    - post_rand_n
  rand_shot_flashing_rand_hit:
    - post_rand_d

widget_player:
  post_rand_r:
    rand_r_widget:
      action: add
      slide: base_slide
  post_rand_a:
    rand_a_widget:
      action: add
      slide: base_slide
  post_rand_n:
    rand_n_widget:
      action: add
      slide: base_slide
  post_rand_d:
    rand_d_widget:
      action: add
      slide: base_slide
  mode_qualify_rand_started:
    rand_qualify_image:
      action: add
      slide: base_slide
  rand_collected:
    rand_qualify_image:
      action: remove

widgets:
  rand_qualify_image:
    - type: image
      image: rand_qualify
      x: center - 580
      y: center + 275
  rand_r_widget:
    - type: text
      text: R
      color: red
      font_size: 40
      x: center - 620
      y: center + 200
  rand_a_widget:
    - type: text
      text: A
      color: red
      font_size: 40
      x: center - 595
      y: center + 200
  rand_n_widget:
    - type: text
      text: N
      color: red
      font_size: 40
      x: center - 570
      y: center + 200
  rand_d_widget:
    - type: text
      text: D
      color: red
      font_size: 40
      x: center - 545
      y: center + 200

shot_groups:
  rand_shot_group:
    shots: r_shot, ra_shot, ran_shot, rand_shot
    enable_events: mode_annie_mode_stopped
    disable_events:  mode_annie_mode_started
    debug: true

shots:
  r_shot:
    switch: s_left_lock_kickout
    profile: rand_profile
    enable_events: mode_qualify_rand_started{device.counters.rand_hit_counter.value==0}
    disable_events: r_shot_flashing_rand_hit
    advance_events: r_shot_flashing_rand_hit, qualify_rand_1st_time{device.counters.rand_hit_counter.value==0}
    debug: true
  ra_shot:
    switch: s_left_lock_kickout
    profile: rand_profile
    enable_events: r_shot_flashing_rand_hit, mode_qualify_rand_started{device.counters.rand_hit_counter.value==1}
    disable_events: ra_shot_flashing_rand_hit, mode_qualify_rand_started{device.counters.rand_hit_counter.value<1 or device.counters.rand_hit_counter.value>1}
    advance_events: r_shot_flashing_rand_hit, ra_shot_flashing_rand_hit, qualify_rand_1st_time{device.counters.rand_hit_counter.value==1}
    debug: true
  ran_shot:
    switch: s_left_lock_kickout
    profile: rand_profile
    enable_events: ra_shot_flashing_rand_hit, mode_qualify_rand_started{device.counters.rand_hit_counter.value==2}
    disable_events: ran_shot_flashing_rand_hit, mode_qualify_rand_started{device.counters.rand_hit_counter.value<2 or device.counters.rand_hit_counter.value>2}
    advance_events: ra_shot_flashing_rand_hit, ran_shot_flashing_rand_hit, qualify_rand_1st_time{device.counters.rand_hit_counter.value==2}
    debug: true
  rand_shot:
    switch: s_left_lock_kickout
    profile: rand_profile
    enable_events: ran_shot_flashing_rand_hit, mode_qualify_rand_started{device.counters.rand_hit_counter.value==3}
    disable_events: rand_shot_flashing_rand_hit, mode_qualify_rand_started{device.counters.rand_hit_counter.value<3}
    advance_events: ran_shot_flashing_rand_hit, rand_shot_flashing_rand_hit, qualify_rand_1st_time{device.counters.rand_hit_counter.value==3}
    debug: true


shot_profiles:
  rand_profile:
    advance_on_hit: false
    states:
    - name: unlit
      show: off
    - name: flashing_rand
      show: flash_rand_show
      sync_ms: 1500
      loops: -1
      speed: 5
    - name: hit
      show: off

counters:
  rand_started_first_time_counter:
    count_events:
      - mode_qualify_rand_started
    starting_count: 0
    direction: up
    count_complete_value: 1
    reset_on_complete: false
    events_when_complete: qualify_rand_1st_time
    persist_state: true
    debug: true
  rand_hit_counter:
    count_events:
      - r_shot_flashing_rand_hit
      - ra_shot_flashing_rand_hit
      - ran_shot_flashing_rand_hit
      - rand_shot_flashing_rand_hit
    starting_count: current_player.rand_start_count
    direction: up
    count_complete_value: 4
    reset_on_complete: false
    events_when_complete: rand_collected
    persist_state: true
    debug: true

variable_player:
  rand_collected:
    team_members_collected: 1
