#config_version=5

mode:
  start_events:
    - start_intro_big_apple
  stop_events:
    - stop_intro_big_apple_mode
  restart_on_next_ball: false
  priority: 8350

queue_event_player:
  mode_intro_big_apple_started:
    queue_event: my_queue_big_apple
    events_when_finished: stop_intro_big_apple_mode

queue_relay_player:
  my_queue_big_apple:
    post: start_big_apple_intro
    wait_for: intro_big_apple_show_ended
  balldevice_bd_trough_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: intro_big_apple_show_ended
  balldevice_bd_right_lock_ball_eject_attempt:
    post: wait_for_instructions
    wait_for: intro_big_apple_show_ended

shows:
  big_apple_intro:
    - duration: 15
      slides:
        intro_big_apple_slide:
          widgets:
            - type: text
              text: THE BIG APPLE !!!
              color: white
              font_size: 80
              x: center
              y: center+300
            - type: video
              video: intro_big_apple_video
            - type: text
              text: Collect Protoculture, Destroy The Hive, lits Jackpot
              color: white
              x: center
              y: center-300
              font_size: 50

light_player:
  mode_intro_big_apple_started{game.balls_in_play == 1}:
    gi_string:
      color: off
    playfield:
      color: off
      priority: 9900

show_player:
  start_big_apple_intro:
    big_apple_intro:
      loops: 0
      events_when_stopped: intro_big_apple_show_ended
  flipper_cancel:
    big_apple_intro:
      action: stop
